-- Amaal Phase 007 Computers & Laptops. Additive/idempotent only. Never resets catalogue data.
BEGIN;
INSERT INTO brands(name,slug,status,website_visibility) VALUES
 ('HP','hp','Active','Published'),('Lenovo','lenovo','Active','Published'),('Apple','apple','Active','Published')
ON CONFLICT(slug) DO NOTHING;
INSERT INTO product_categories(name,slug,status,website_visibility) VALUES
 ('Computers','computers','Active','Published')
ON CONFLICT DO NOTHING;
INSERT INTO product_categories(parent_id,name,slug,status,website_visibility)
SELECT c.id,x.name,x.slug,'Active','Published' FROM product_categories c CROSS JOIN (VALUES
 ('Laptops','computers-laptops'),('Desktops','computers-desktops'),('All-in-One','computers-all-in-one'),('Gaming Laptops','computers-gaming-laptops')
) x(name,slug) WHERE c.slug='computers' AND NOT EXISTS (SELECT 1 FROM product_categories pc WHERE pc.parent_id=c.id AND lower(pc.name)=lower(x.name)) ON CONFLICT DO NOTHING;
INSERT INTO product_categories(parent_id,name,slug,status,website_visibility)
SELECT c.id,x.name,x.slug,'Active','Published' FROM product_categories c CROSS JOIN (VALUES
 ('Laptops HP','computers-laptops-hp'),('Laptops Lenovo','computers-laptops-lenovo'),('Laptops Apple','computers-laptops-apple')
) x(name,slug) WHERE c.slug='computers-laptops' AND NOT EXISTS (SELECT 1 FROM product_categories pc WHERE pc.parent_id=c.id AND lower(pc.name)=lower(x.name)) ON CONFLICT DO NOTHING;
INSERT INTO product_categories(parent_id,name,slug,status,website_visibility)
SELECT c.id,'Desktop Brands','computers-desktops-brands','Active','Published' FROM product_categories c WHERE c.slug='computers-desktops' ON CONFLICT DO NOTHING;
WITH x(name,slug,brand,cat,short,descr,specs) AS (VALUES
 ('HP 15 Laptop','hp-15','hp','computers-laptops','A practical everyday laptop for study, work and home computing.','The HP 15 family is designed for everyday productivity, study, browsing and general home computing. Exact configurations vary by model and region.','{"Screen":"15.6-inch","Processor":"Intel Core or AMD Ryzen, configuration dependent","Memory":"8GB–16GB, configuration dependent","Storage":"256GB–512GB SSD, configuration dependent","Graphics":"Integrated Intel or AMD graphics","Operating system":"Windows 11"}'),
 ('HP ProBook 440','hp-probook-440','hp','computers-laptops-hp','A compact business laptop for professional work.','The HP ProBook 440 family combines a compact 14-inch format with business-focused features. Specifications vary by generation and regional configuration.','{"Screen":"14-inch","Processor":"Intel Core / Core Ultra, generation dependent","Memory":"Up to 32GB on supported configurations","Storage":"SSD, configuration dependent","Graphics":"Integrated Intel graphics","Operating system":"Windows 11 Pro / Windows 11"}'),
 ('HP ProBook 450','hp-probook-450','hp','computers-laptops-hp','A larger business laptop for office and professional use.','The HP ProBook 450 family offers a 15.6-inch business format with multiple processor, memory and graphics configurations.','{"Screen":"15.6-inch","Processor":"Intel Core / Core Ultra, generation dependent","Memory":"Up to 32GB on supported configurations","Storage":"SSD, configuration dependent","Graphics":"Integrated Intel graphics; selected configurations vary","Operating system":"Windows 11 Pro / Windows 11"}'),
 ('HP ProBook 445','hp-probook-445','hp','computers-laptops-hp','A 14-inch AMD business laptop for productive work.','The HP ProBook 445 family uses AMD Ryzen processors in selected generations and is aimed at professional productivity.','{"Screen":"14-inch","Processor":"AMD Ryzen, generation dependent","Memory":"Up to 32GB on supported configurations","Storage":"SSD, configuration dependent","Graphics":"Integrated AMD Radeon graphics","Operating system":"Windows 11 Pro / Windows 11"}'),
 ('HP EliteBook 840','hp-elitebook-840','hp','computers-laptops-hp','A premium 14-inch business laptop for professionals.','The HP EliteBook 840 family is a premium business line with modern Intel processor options and professional security features.','{"Screen":"14-inch, WUXGA options","Processor":"Intel Core Ultra / Intel Core, generation dependent","Memory":"Configuration dependent","Storage":"SSD, configuration dependent","Graphics":"Integrated Intel graphics","Operating system":"Windows 11 Pro"}'),
 ('HP Pavilion 15 Laptop','hp-pavilion-15','hp','computers-laptops-hp','A versatile everyday laptop for school, work and entertainment.','HP Pavilion 15 models sit between basic everyday machines and premium consumer laptops.','{"Screen":"15.6-inch","Processor":"Intel Core or AMD Ryzen, generation dependent","Memory":"Configuration dependent","Storage":"SSD, configuration dependent","Operating system":"Windows 11"}'),
 ('HP Envy 14 Laptop','hp-envy-14','hp','computers-laptops-hp','A refined premium laptop for creators and professionals.','HP Envy 14 models are positioned as premium consumer machines with stronger displays, materials and performance.','{"Screen":"14-inch, configuration dependent","Processor":"Intel Core / Core Ultra, generation dependent","Memory":"Configuration dependent","Storage":"SSD, configuration dependent","Operating system":"Windows 11"}'),
 ('Lenovo IdeaPad Slim 3 15','lenovo-ideapad-slim-3-15','lenovo','computers-laptops-lenovo','A dependable 15-inch laptop for everyday productivity.','The IdeaPad Slim 3 15 family is available in Intel and AMD configurations.','{"Screen":"15.6-inch FHD, configuration dependent","Processor":"AMD Ryzen 5 7520U example configuration","Memory":"8GB LPDDR5 example; 16GB configurations available","Storage":"512GB SSD example configuration","Graphics":"AMD Radeon 610M on Ryzen 5 7520U configuration","Operating system":"Windows 11"}'),
 ('Lenovo IdeaPad Slim 3i 15','lenovo-ideapad-slim-3i-15','lenovo','computers-laptops-lenovo','A slim 15-inch Intel laptop for everyday use.','The IdeaPad Slim 3i 15 family provides Intel-powered configurations in a practical 15-inch design.','{"Screen":"15.6-inch FHD, configuration dependent","Processor":"Intel Core, generation dependent","Memory":"8GB–16GB, configuration dependent","Storage":"256GB–1TB SSD, configuration dependent","Graphics":"Integrated Intel graphics","Operating system":"Windows 11"}'),
 ('Lenovo V15','lenovo-v15','lenovo','computers-laptops-lenovo','A straightforward business-value laptop for office work.','The Lenovo V15 is a practical 15.6-inch business-value laptop with Intel and AMD configurations across generations.','{"Screen":"15.6-inch FHD options","Processor":"Intel Core or AMD Ryzen, generation dependent","Memory":"Up to 16GB on documented configurations","Storage":"SSD, configuration dependent","Graphics":"Integrated graphics","Operating system":"Windows 11"}'),
 ('Lenovo ThinkBook 14','lenovo-thinkbook-14','lenovo','computers-laptops-lenovo','A modern business laptop balancing professional features and portability.','ThinkBook 14 models are designed for small business and professional users.','{"Screen":"14-inch, configuration dependent","Processor":"Intel Core / Core Ultra or AMD Ryzen, generation dependent","Memory":"Configuration dependent","Storage":"SSD, configuration dependent","Operating system":"Windows 11 Pro / Windows 11"}'),
 ('Lenovo ThinkPad E14','lenovo-thinkpad-e14','lenovo','computers-laptops-lenovo','A proven 14-inch business laptop for professionals and organizations.','ThinkPad E14 models focus on business productivity, durability and security.','{"Screen":"14-inch, WUXGA options","Processor":"Intel Core Ultra / Intel Core or AMD Ryzen, generation dependent","Memory":"Configuration dependent","Storage":"SSD, configuration dependent","Operating system":"Windows 11 Pro"}'),
 ('Lenovo ThinkPad T14','lenovo-thinkpad-t14','lenovo','computers-laptops-lenovo','A premium professional ThinkPad for serious business workloads.','ThinkPad T14 is a premium business family designed around portability, manageability and security.','{"Screen":"14-inch, configuration dependent","Processor":"Intel Core Ultra / Intel Core or AMD Ryzen PRO, generation dependent","Memory":"Configuration dependent","Storage":"SSD, configuration dependent","Operating system":"Windows 11 Pro"}'),
 ('Lenovo LOQ 15 Gaming Laptop','lenovo-loq-15','lenovo','computers-gaming-laptops','A gaming laptop family built for high-performance play.','Lenovo LOQ 15 combines performance-oriented processors and dedicated NVIDIA graphics on selected configurations.','{"Screen":"15.6-inch, high-refresh options","Processor":"Intel Core / AMD Ryzen, generation dependent","Memory":"Configuration dependent","Storage":"SSD, configuration dependent","Graphics":"NVIDIA GeForce RTX options","Operating system":"Windows 11"}'),
 ('Lenovo Legion 5 Gaming Laptop','lenovo-legion-5','lenovo','computers-gaming-laptops','A premium gaming laptop for demanding games and performance work.','Legion 5 models target gamers and performance users with high-performance processors, dedicated graphics and fast displays.','{"Screen":"15/16-inch, generation dependent","Processor":"Intel Core / AMD Ryzen, generation dependent","Memory":"Configuration dependent","Storage":"SSD, configuration dependent","Graphics":"NVIDIA GeForce RTX options","Operating system":"Windows 11"}'),
 ('MacBook Neo','macbook-neo-13','apple','computers-laptops-apple','Apple’s compact Mac laptop for everyday computing.','MacBook Neo is positioned as an accessible Mac notebook with Apple silicon performance.','{"Processor":"Apple A18 Pro","Display":"13-inch class","Memory":"Configuration dependent","Storage":"Configuration dependent","Graphics":"Integrated Apple GPU","Operating system":"macOS"}'),
 ('MacBook Air 13-inch with M5','macbook-air-13-m5','apple','computers-laptops-apple','A thin, light MacBook Air for work, study and creation.','The 13-inch MacBook Air with M5 combines Apple silicon performance with a thin design and Liquid Retina display.','{"Display":"13.6-inch Liquid Retina","Chip":"Apple M5","Memory":"16GB unified memory starting point","Storage":"512GB starting configuration","Operating system":"macOS"}'),
 ('MacBook Air 15-inch with M5','macbook-air-15-m5','apple','computers-laptops-apple','A larger-screen MacBook Air with M5 performance.','The 15-inch MacBook Air with M5 offers a larger Liquid Retina canvas while retaining the thin Air design.','{"Display":"15.3-inch Liquid Retina","Chip":"Apple M5","Memory":"16GB unified memory starting point","Storage":"512GB starting configuration","Operating system":"macOS"}'),
 ('MacBook Pro 14-inch with M5','macbook-pro-14-m5','apple','computers-laptops-apple','A professional 14-inch MacBook for demanding workloads.','The 14-inch MacBook Pro with M5 is designed for professional users who need sustained performance and Liquid Retina XDR.','{"Display":"14.2-inch Liquid Retina XDR","Chip":"Apple M5","Memory":"16GB unified memory starting point","Storage":"1TB starting configuration","Operating system":"macOS"}'),
 ('MacBook Pro 14-inch with M5 Pro','macbook-pro-14-m5-pro','apple','computers-laptops-apple','A high-performance 14-inch MacBook Pro for demanding work.','The M5 Pro configuration targets professionals working with code, media, design and data.','{"Display":"14.2-inch Liquid Retina XDR","Chip":"Apple M5 Pro","Memory":"Configuration dependent","Storage":"Configuration dependent","Operating system":"macOS"}'),
 ('MacBook Pro 16-inch with M5 Pro','macbook-pro-16-m5-pro','apple','computers-laptops-apple','A large-screen professional MacBook Pro.','The 16-inch M5 Pro MacBook Pro is built for professionals who value a large workspace and sustained performance.','{"Display":"16.2-inch Liquid Retina XDR","Chip":"Apple M5 Pro","Memory":"Configuration dependent","Storage":"Configuration dependent","Operating system":"macOS"}'),
 ('MacBook Pro 16-inch with M5 Max','macbook-pro-16-m5-max','apple','computers-laptops-apple','A high-end notebook for the most demanding professional workflows.','The M5 Max 16-inch MacBook Pro sits at the top of the Mac notebook range.','{"Display":"16.2-inch Liquid Retina XDR","Chip":"Apple M5 Max","Memory":"Configuration dependent","Storage":"Configuration dependent","Operating system":"macOS"}')
)
INSERT INTO products(name,slug,brand_id,category_id,product_type,short_description,description,specifications,status,website_visibility,featured)
SELECT x.name,x.slug,b.id,c.id,'Laptop',x.short,x.descr,x.specs::jsonb,'Active','Hidden',false FROM x JOIN brands b ON b.slug=x.brand JOIN product_categories c ON c.slug=x.cat ON CONFLICT(slug) DO NOTHING;
INSERT INTO product_variants(product_id,sku,variant_name,cost_price,selling_price,wholesale_price,track_inventory,serialized,status)
SELECT p.id,upper(regexp_replace(p.slug,'[^a-zA-Z0-9]+','-','g')),'Default',0,0,0,true,false,'Active' FROM products p JOIN product_categories c ON c.id=p.category_id WHERE c.slug LIKE 'computers-%' OR c.slug='computers' ON CONFLICT(sku) DO NOTHING;
COMMIT;
