export function registerCustomersCrm({app,auth,need,q,pool,audit}){
  const text=v=>String(v??'').trim(); const n=v=>Number(v||0);
  const customerNo=()=>`CUS-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;
  const validType=v=>['Individual','Business','Corporate'].includes(v);
  app.get('/api/customers/summary',auth,need('customers.view'),async(req,res)=>{
    const [tot,active,biz,new30,openCases,balance]=await Promise.all([
      q('SELECT count(*)::int c FROM customers'),q("SELECT count(*)::int c FROM customers WHERE status='Active'"),q("SELECT count(*)::int c FROM customers WHERE customer_type IN ('Business','Corporate')"),q("SELECT count(*)::int c FROM customers WHERE created_at>=now()-interval '30 days'"),q("SELECT count(*)::int c FROM support_cases WHERE status NOT IN ('Resolved','Closed')"),q("SELECT COALESCE(sum(balance),0)::numeric total FROM customer_balances")]);
    res.json({customers:tot[0].c,active:active[0].c,businessCustomers:biz[0].c,new30d:new30[0].c,openCases:openCases[0].c,outstandingBalance:balance[0].total});
  });
  app.get('/api/customers',auth,need('customers.view'),async(req,res)=>{const limit=Math.min(n(req.query.limit)||100,200),offset=Math.max(n(req.query.offset)||0,0),params=[];let where='';if(req.query.q){params.push('%'+text(req.query.q)+'%');where=`WHERE c.customer_no ILIKE $${params.length} OR c.name ILIKE $${params.length} OR c.email ILIKE $${params.length} OR c.phone ILIKE $${params.length}`;}params.push(limit,offset);res.json(await q(`SELECT c.*,COALESCE(b.balance,0)::numeric outstanding_balance,(SELECT count(*) FROM customer_interactions i WHERE i.customer_id=c.id)::int interactions,(SELECT count(*) FROM support_cases sc WHERE sc.customer_id=c.id AND sc.status NOT IN ('Resolved','Closed'))::int open_cases FROM customers c LEFT JOIN customer_balances b ON b.customer_id=c.id ${where} ORDER BY c.created_at DESC LIMIT $${params.length-1} OFFSET $${params.length}` ,params));});
  app.post('/api/customers',auth,need('customers.manage'),async(req,res)=>{const b=req.body||{};if(!text(b.name)||!text(b.phone))return res.status(400).json({error:'Name and phone are required'});if(!validType(b.customerType||'Individual'))return res.status(400).json({error:'Invalid customer type'});try{const c=(await q(`INSERT INTO customers(customer_no,name,customer_type,company_name,email,phone,alternate_phone,tax_number,country_code,preferred_currency,address_line1,address_line2,city,region,postal_code,status,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,'Active',$16,$17) RETURNING *`,[customerNo(),text(b.name),b.customerType||'Individual',text(b.companyName),text(b.email).toLowerCase(),text(b.phone),text(b.alternatePhone),text(b.taxNumber),text(b.countryCode)||'UG',text(b.preferredCurrency)||'UGX',text(b.addressLine1),text(b.addressLine2),text(b.city),text(b.region),text(b.postalCode),text(b.notes),req.user.id]))[0];await pool.query('INSERT INTO customer_balances(customer_id,balance,credit_limit) VALUES($1,0,0)',[c.id]);await audit(req.user,'CUSTOMER_CREATED','Customer',c.id,`Created customer ${c.customer_no}`,null,c,req.req);res.status(201).json(c)}catch(e){res.status(400).json({error:e.code==='23505'?'Customer email/phone already exists':e.message})}});
  app.get('/api/customers/:id',auth,need('customers.view'),async(req,res)=>{const c=(await q('SELECT c.*,COALESCE(b.balance,0)::numeric outstanding_balance,COALESCE(b.credit_limit,0)::numeric credit_limit FROM customers c LEFT JOIN customer_balances b ON b.customer_id=c.id WHERE c.id=$1',[req.params.id]))[0];if(!c)return res.status(404).json({error:'Customer not found'});const [addresses,contacts,interactions,cases,tags]=await Promise.all([q('SELECT * FROM customer_addresses WHERE customer_id=$1 ORDER BY is_default DESC,created_at DESC',[c.id]),q('SELECT * FROM customer_contacts WHERE customer_id=$1 ORDER BY created_at DESC',[c.id]),q('SELECT * FROM customer_interactions WHERE customer_id=$1 ORDER BY created_at DESC LIMIT 200',[c.id]),q('SELECT * FROM support_cases WHERE customer_id=$1 ORDER BY created_at DESC LIMIT 100',[c.id]),q('SELECT t.* FROM customer_tags t JOIN customer_tag_assignments a ON a.tag_id=t.id WHERE a.customer_id=$1 ORDER BY t.name',[c.id])]);res.json({...c,addresses,contacts,interactions,cases,tags})});
  app.patch('/api/customers/:id',auth,need('customers.manage'),async(req,res)=>{const old=(await q('SELECT * FROM customers WHERE id=$1',[req.params.id]))[0];if(!old)return res.status(404).json({error:'Customer not found'});const b=req.body||{};const c=(await q(`UPDATE customers SET name=COALESCE($1,name),customer_type=COALESCE($2,customer_type),company_name=COALESCE($3,company_name),email=COALESCE($4,email),phone=COALESCE($5,phone),alternate_phone=COALESCE($6,alternate_phone),tax_number=COALESCE($7,tax_number),country_code=COALESCE($8,country_code),preferred_currency=COALESCE($9,preferred_currency),address_line1=COALESCE($10,address_line1),address_line2=COALESCE($11,address_line2),city=COALESCE($12,city),region=COALESCE($13,region),postal_code=COALESCE($14,postal_code),status=COALESCE($15,status),notes=COALESCE($16,notes),updated_at=now(),updated_by=$17 WHERE id=$18 RETURNING *`,[b.name,b.customerType,b.companyName,b.email,b.phone,b.alternatePhone,b.taxNumber,b.countryCode,b.preferredCurrency,b.addressLine1,b.addressLine2,b.city,b.region,b.postalCode,b.status,b.notes,req.user.id,old.id]))[0];await audit(req.user,'CUSTOMER_UPDATED','Customer',c.id,'Updated customer profile',old,c,req.req);res.json(c)});
  app.post('/api/customers/:id/addresses',auth,need('customers.manage'),async(req,res)=>{const b=req.body||{};if(!text(b.addressLine1)||!text(b.city))return res.status(400).json({error:'Address and city are required'});const client=await pool.connect();try{await client.query('BEGIN');if(b.isDefault)await client.query('UPDATE customer_addresses SET is_default=false WHERE customer_id=$1',[req.params.id]);const a=(await client.query('INSERT INTO customer_addresses(customer_id,label,address_line1,address_line2,city,region,postal_code,country_code,is_default) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[req.params.id,text(b.label)||'Address',text(b.addressLine1),text(b.addressLine2),text(b.city),text(b.region),text(b.postalCode),text(b.countryCode)||'UG',Boolean(b.isDefault)])).rows[0];await client.query('COMMIT');await audit(req.user,'CUSTOMER_ADDRESS_CREATED','CustomerAddress',a.id,'Added customer address',null,a,req.req);res.status(201).json(a)}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
  app.post('/api/customers/:id/contacts',auth,need('customers.manage'),async(req,res)=>{if(!text(req.body?.name)||!text(req.body?.phone))return res.status(400).json({error:'Contact name and phone are required'});const c=(await q('INSERT INTO customer_contacts(customer_id,name,role,email,phone,is_primary) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[req.params.id,text(req.body.name),text(req.body.role),text(req.body.email).toLowerCase(),text(req.body.phone),Boolean(req.body.isPrimary)]))[0];await audit(req.user,'CUSTOMER_CONTACT_CREATED','CustomerContact',c.id,'Added customer contact',null,c,req.req);res.status(201).json(c)});
  app.post('/api/customers/:id/interactions',auth,need('crm.manage'),async(req,res)=>{if(!text(req.body?.type)||!text(req.body?.summary))return res.status(400).json({error:'Interaction type and summary are required'});const i=(await q('INSERT INTO customer_interactions(customer_id,type,subject,summary,channel,outcome,next_follow_up,assigned_to,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[req.params.id,text(req.body.type),text(req.body.subject),text(req.body.summary),text(req.body.channel),text(req.body.outcome),req.body.nextFollowUp||null,req.body.assignedTo||null,req.user.id]))[0];await audit(req.user,'CRM_INTERACTION_CREATED','CustomerInteraction',i.id,'Recorded customer interaction',null,i,req.req);res.status(201).json(i)});
  app.get('/api/crm/tasks',auth,need('crm.view'),async(req,res)=>res.json(await q("SELECT i.*,c.customer_no,c.name customer_name FROM customer_interactions i JOIN customers c ON c.id=i.customer_id WHERE i.next_follow_up IS NOT NULL AND i.next_follow_up>=current_date ORDER BY i.next_follow_up LIMIT 200")));
  app.get('/api/customer-tags',auth,need('crm.view'),async(req,res)=>res.json(await q('SELECT * FROM customer_tags ORDER BY name')));
  app.post('/api/customer-tags',auth,need('crm.manage'),async(req,res)=>{if(!text(req.body?.name))return res.status(400).json({error:'Tag name required'});const t=(await q('INSERT INTO customer_tags(name,description) VALUES($1,$2) RETURNING *',[text(req.body.name),text(req.body.description)]))[0];await audit(req.user,'CUSTOMER_TAG_CREATED','CustomerTag',t.id,'Created customer segment tag',null,t,req.req);res.status(201).json(t)});
  app.post('/api/customers/:id/tags/:tagId',auth,need('crm.manage'),async(req,res)=>{await pool.query('INSERT INTO customer_tag_assignments(customer_id,tag_id,assigned_by) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[req.params.id,req.params.tagId,req.user.id]);res.json({ok:true})});
  app.delete('/api/customers/:id/tags/:tagId',auth,need('crm.manage'),async(req,res)=>{await pool.query('DELETE FROM customer_tag_assignments WHERE customer_id=$1 AND tag_id=$2',[req.params.id,req.params.tagId]);res.json({ok:true})});
  app.post('/api/customers/:id/cases',auth,need('support.manage'),async(req,res)=>{const b=req.body||{};if(!text(b.title)||!text(b.description))return res.status(400).json({error:'Case title and description are required'});const c=(await q("INSERT INTO support_cases(case_no,customer_id,title,description,priority,channel,status,assigned_to,created_by) VALUES($1,$2,$3,$4,$5,$6,'Open',$7,$8) RETURNING *",[`CASE-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`,req.params.id,text(b.title),text(b.description),['Low','Normal','High','Urgent'].includes(b.priority)?b.priority:'Normal',text(b.channel)||'Phone',b.assignedTo||null,req.user.id]))[0];await audit(req.user,'SUPPORT_CASE_CREATED','SupportCase',c.id,`Created case ${c.case_no}`,null,c,req.req);res.status(201).json(c)});
  app.patch('/api/support/cases/:id',auth,need('support.manage'),async(req,res)=>{const old=(await q('SELECT * FROM support_cases WHERE id=$1',[req.params.id]))[0];if(!old)return res.status(404).json({error:'Case not found'});const b=req.body||{};const c=(await q("UPDATE support_cases SET status=COALESCE($1,status),priority=COALESCE($2,priority),assigned_to=COALESCE($3,assigned_to),resolution=COALESCE($4,resolution),resolved_at=CASE WHEN $1 IN ('Resolved','Closed') THEN now() ELSE resolved_at END,updated_at=now() WHERE id=$5 RETURNING *",[b.status,b.priority,b.assignedTo,b.resolution,old.id]))[0];await audit(req.user,'SUPPORT_CASE_UPDATED','SupportCase',c.id,'Updated support case',old,c,req.req);res.json(c)});
  app.get('/api/support/cases',auth,need('support.view'),async(req,res)=>res.json(await q(`SELECT s.*,c.customer_no,c.name customer_name,u.email assignee_email FROM support_cases s JOIN customers c ON c.id=s.customer_id LEFT JOIN users u ON u.id=s.assigned_to ORDER BY s.created_at DESC LIMIT 300`)));
  app.get('/api/customers/:id/privacy',auth,need('customers.privacy'),async(req,res)=>{const c=(await q('SELECT id,customer_no,name,email,phone,status FROM customers WHERE id=$1',[req.params.id]))[0];if(!c)return res.status(404).json({error:'Customer not found'});res.json({customer:c,consent:(await q('SELECT * FROM customer_consents WHERE customer_id=$1 ORDER BY consent_type',[c.id]))})});
  app.put('/api/customers/:id/consent',auth,need('customers.privacy'),async(req,res)=>{const b=req.body||{};if(!text(b.consentType))return res.status(400).json({error:'Consent type required'});const c=(await q('INSERT INTO customer_consents(customer_id,consent_type,granted,source,recorded_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(customer_id,consent_type) DO UPDATE SET granted=EXCLUDED.granted,source=EXCLUDED.source,recorded_by=EXCLUDED.recorded_by,updated_at=now() RETURNING *',[req.params.id,text(b.consentType),Boolean(b.granted),text(b.source)||'Admin',req.user.id]))[0];await audit(req.user,'CUSTOMER_CONSENT_UPDATED','CustomerConsent',c.id,'Updated customer consent',null,c,req.req);res.json(c)});
  app.post('/api/customers/:id/anonymize',auth,need('customers.privacy'),async(req,res)=>{const c=(await q('SELECT * FROM customers WHERE id=$1',[req.params.id]))[0];if(!c)return res.status(404).json({error:'Customer not found'});if(!['ANONYMIZE','DELETE'].includes(req.body?.confirmation))return res.status(400).json({error:'Explicit confirmation required'});const anon=`ANON-${c.id.slice(0,8)}`;const updated=(await q("UPDATE customers SET name=$1,email='',phone='',alternate_phone='',company_name='',tax_number='',address_line1='',address_line2='',city='',region='',postal_code='',notes='',status='Anonymized',updated_at=now(),updated_by=$2 WHERE id=$3 RETURNING id,customer_no,name,email,phone,status",[anon,req.user.id,c.id]))[0];await audit(req.user,'CUSTOMER_ANONYMIZED','Customer',c.id,'Anonymized customer personal data',c,updated,req.req);res.json(updated)});
  app.get('/api/customers/export',auth,need('customers.export'),async(req,res)=>{const rows=await q('SELECT customer_no,name,customer_type,company_name,email,phone,country_code,preferred_currency,status,created_at FROM customers ORDER BY created_at DESC');const esc=v=>{const x=String(v??'');return /[",\n]/.test(x)?`"${x.replace(/"/g,'""')}"`:x};res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename=amaal-customers.csv');res.send(['customer_no,name,customer_type,company_name,email,phone,country,currency,status,created_at',...rows.map(r=>[r.customer_no,r.name,r.customer_type,r.company_name,r.email,r.phone,r.country_code,r.preferred_currency,r.status,r.created_at].map(esc).join(','))].join('\n'))});
}
