-- Phase 39: Global Search, UX & Operational Polish. Safe additive indexes.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_products_search_name_trgm ON products USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_products_search_slug_trgm ON products USING gin (slug gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_customers_search_name_trgm ON customers USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_customers_search_phone_trgm ON customers USING gin (phone gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_customers_search_email_trgm ON customers USING gin (email gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_suppliers_search_legal_name_trgm ON suppliers USING gin (legal_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_suppliers_search_code_trgm ON suppliers USING gin (supplier_code gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_sales_search_sale_no ON sales(sale_no);
CREATE INDEX IF NOT EXISTS idx_orders_search_order_no ON orders(order_no);
CREATE INDEX IF NOT EXISTS idx_serialized_units_search_serial_trgm ON serialized_units USING gin (serial_number gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_serialized_units_search_imei1_trgm ON serialized_units USING gin (imei1 gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_serialized_units_search_imei2_trgm ON serialized_units USING gin (imei2 gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_documents_search_name_trgm ON documents USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_purchase_requisitions_search_no ON purchase_requisitions(requisition_no);
CREATE INDEX IF NOT EXISTS idx_supplier_invoices_search_no ON supplier_invoices(invoice_no);
CREATE INDEX IF NOT EXISTS idx_delivery_shipments_search_no ON delivery_shipments(shipment_no);
CREATE INDEX IF NOT EXISTS idx_warranty_claims_search_no ON warranty_claims(claim_no);
CREATE INDEX IF NOT EXISTS idx_return_requests_search_no ON return_requests(return_no);
CREATE INDEX IF NOT EXISTS idx_credit_accounts_search_no ON credit_accounts(account_no);
CREATE INDEX IF NOT EXISTS idx_finance_journals_search_no ON finance_journals(journal_no);
