import crypto from 'crypto';
import dns from 'dns/promises';

export function registerIntegrationHub({app,auth,need,q,pool,audit,superAdminOnly}){
  const key=process.env.INTEGRATION_ENCRYPTION_KEY||process.env.JWT_SECRET||'';
  const keyBytes=crypto.createHash('sha256').update(key||'amaal-integration-fallback').digest();
  const encrypt=v=>{if(!v)return '';const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',keyBytes,iv);const out=Buffer.concat([c.update(String(v),'utf8'),c.final()]);return `${iv.toString('base64url')}.${c.getAuthTag().toString('base64url')}.${out.toString('base64url')}`};
  const decrypt=v=>{if(!v)return '';try{const [iv,tag,data]=String(v).split('.');const d=crypto.createDecipheriv('aes-256-gcm',keyBytes,Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([d.update(Buffer.from(data,'base64url')),d.final()]).toString('utf8')}catch{return ''}};
  const text=v=>String(v??'').trim();
  function safeUrl(value){const u=new URL(text(value));if(u.protocol!=='https:')throw new Error('Integration URLs must use HTTPS');if(!u.hostname)throw new Error('Integration URL is required');return u}
  function isPrivateIp(ip){return /^(10\.|127\.|169\.254\.|192\.168\.|0\.)/.test(ip)||/^172\.(1[6-9]|2\d|3[0-1])\./.test(ip)||/^::1$|^fc|^fd|^fe80:/i.test(ip)}
  async function assertPublicHost(host){if(['localhost','localhost.localdomain'].includes(host.toLowerCase()))throw new Error('Private integration hosts are blocked');const records=await dns.lookup(host,{all:true});if(records.some(r=>isPrivateIp(r.address)))throw new Error('Private or link-local integration destinations are blocked')}
  function publicRow(r){return {...r,secret_encrypted:undefined,secretConfigured:Boolean(r.secret_encrypted)}}
  async function emit(eventType,sourceModule,resourceType,resourceId,payload={}){
    const e=(await q('INSERT INTO integration_events(event_type,source_module,resource_type,resource_id,payload) VALUES($1,$2,$3,$4,$5) RETURNING *',[eventType,sourceModule,resourceType||null,resourceId||null,JSON.stringify(payload||{})]))[0];
    const hooks=await q("SELECT * FROM integration_webhooks WHERE active=true AND direction='Outbound'");
    for(const h of hooks){const types=Array.isArray(h.event_types)?h.event_types:[];if(types.length&&!types.includes(eventType))continue;try{const u=safeUrl(h.url);await assertPublicHost(u.hostname);const body=JSON.stringify({eventId:e.id,eventType,sourceModule,resourceType,resourceId,payload});const secret=decrypt(h.secret_encrypted);const headers={'Content-Type':'application/json','X-Amaal-Event':eventType,'X-Amaal-Event-Id':e.id};if(secret)headers['X-Amaal-Signature']='sha256='+crypto.createHmac('sha256',secret).update(body).digest('hex');const started=Date.now();const r=await fetch(u,{method:'POST',headers,body,redirect:'error'});const responseMs=Date.now()-started;await pool.query('INSERT INTO integration_deliveries(webhook_id,event_id,status_code,response_ms,error_message) VALUES($1,$2,$3,$4,$5)',[h.id,e.id,r.status,responseMs,r.ok?'':'Webhook returned an error']);await pool.query('UPDATE integration_webhooks SET last_delivery_at=now(),last_status_code=$2,last_error=$3,updated_at=now() WHERE id=$1',[h.id,r.status,r.ok?'':'Webhook returned an error']);
      }catch(err){await pool.query('INSERT INTO integration_deliveries(webhook_id,event_id,error_message) VALUES($1,$2,$3)',[h.id,e.id,err.message]);await pool.query('UPDATE integration_webhooks SET last_delivery_at=now(),last_status_code=NULL,last_error=$2,updated_at=now() WHERE id=$1',[h.id,err.message])}}
    await pool.query("UPDATE integration_events SET status=CASE WHEN EXISTS(SELECT 1 FROM integration_deliveries d WHERE d.event_id=$1 AND d.status_code BETWEEN 200 AND 299) THEN 'Delivered' ELSE 'Recorded' END WHERE id=$1",[e.id]);
    return e;
  }
  app.get('/api/integrations',auth,need('integrations.view'),async(req,res)=>res.json((await q('SELECT * FROM integration_connections ORDER BY name')).map(publicRow)));
  app.post('/api/integrations',auth,need('integrations.manage'),async(req,res)=>{const b=req.body||{};if(!text(b.name)||!text(b.provider))return res.status(400).json({error:'Name and provider are required'});let base='';if(b.baseUrl){try{base=safeUrl(b.baseUrl).toString();await assertPublicHost(new URL(base).hostname)}catch(e){return res.status(400).json({error:e.message})}}const r=(await q('INSERT INTO integration_connections(name,provider,connection_type,base_url,auth_type,auth_header,secret_encrypted,config_json,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) RETURNING *',[text(b.name).slice(0,160),text(b.provider).slice(0,120),text(b.connectionType||'REST'),base,text(b.authType||'None'),text(b.authHeader||'Authorization'),encrypt(b.secret||''),JSON.stringify(b.config||{}),req.user.id]))[0];await audit(req.user,'INTEGRATION_CREATED','Integration',r.id,'Created integration connection',null,publicRow(r),req.req);res.status(201).json(publicRow(r))});
  app.patch('/api/integrations/:id',auth,need('integrations.manage'),async(req,res)=>{const old=(await q('SELECT * FROM integration_connections WHERE id=$1',[req.params.id]))[0];if(!old)return res.status(404).json({error:'Integration not found'});const b=req.body||{};let base=b.baseUrl===undefined?old.base_url:'';if(b.baseUrl!==undefined){try{base=safeUrl(b.baseUrl).toString();await assertPublicHost(new URL(base).hostname)}catch(e){return res.status(400).json({error:e.message})}}const secret=b.secret===undefined?old.secret_encrypted:encrypt(b.secret);const r=(await q('UPDATE integration_connections SET name=COALESCE($1,name),provider=COALESCE($2,provider),connection_type=COALESCE($3,connection_type),base_url=$4,auth_type=COALESCE($5,auth_type),auth_header=COALESCE($6,auth_header),secret_encrypted=$7,config_json=COALESCE($8,config_json),updated_by=$9,updated_at=now() WHERE id=$10 RETURNING *',[b.name?text(b.name).slice(0,160):null,b.provider?text(b.provider):null,b.connectionType?text(b.connectionType):null,base,b.authType?text(b.authType):null,b.authHeader?text(b.authHeader):null,secret,b.config?JSON.stringify(b.config):null,req.user.id,req.params.id]))[0];await audit(req.user,'INTEGRATION_UPDATED','Integration',r.id,'Updated integration connection',publicRow(old),publicRow(r),req.req);res.json(publicRow(r))});
  app.delete('/api/integrations/:id',auth,need('integrations.manage'),async(req,res)=>{const old=(await q('DELETE FROM integration_connections WHERE id=$1 RETURNING *',[req.params.id]))[0];if(!old)return res.status(404).json({error:'Integration not found'});await audit(req.user,'INTEGRATION_DELETED','Integration',old.id,'Deleted integration connection',publicRow(old),null,req.req);res.json({ok:true})});
  app.post('/api/integrations/:id/test',auth,need('integrations.manage'),async(req,res)=>{const r=(await q('SELECT * FROM integration_connections WHERE id=$1',[req.params.id]))[0];if(!r)return res.status(404).json({error:'Integration not found'});try{const u=safeUrl(r.base_url);await assertPublicHost(u.hostname);const headers={};const secret=decrypt(r.secret_encrypted);if(secret&&r.auth_type==='Bearer')headers[r.auth_header||'Authorization']=`Bearer ${secret}`;else if(secret&&r.auth_type==='API Key')headers[r.auth_header||'X-API-Key']=secret;else if(secret&&r.auth_type==='Basic')headers[r.auth_header||'Authorization']=`Basic ${Buffer.from(secret).toString('base64')}`;const started=Date.now();const response=await fetch(u,{headers,redirect:'error',signal:AbortSignal.timeout(10000)});const ms=Date.now()-started;await pool.query('UPDATE integration_connections SET status=$2,last_tested_at=now(),last_error=$3,updated_at=now() WHERE id=$1',[r.id,response.ok?'Active':'Error',response.ok?'':`HTTP ${response.status}`]);res.json({ok:response.ok,status:response.status,responseMs:ms})}catch(e){await pool.query("UPDATE integration_connections SET status='Error',last_tested_at=now(),last_error=$2,updated_at=now() WHERE id=$1",[r.id,e.message]);res.status(502).json({error:e.message})}});

  app.get('/api/integration-webhooks',auth,need('integrations.view'),async(req,res)=>res.json((await q('SELECT * FROM integration_webhooks ORDER BY name')).map(r=>({...r,secret_encrypted:undefined,secretConfigured:Boolean(r.secret_encrypted)}))));
  app.post('/api/integration-webhooks',auth,need('integrations.webhooks'),async(req,res)=>{const b=req.body||{};if(!text(b.name)||!text(b.endpointKey))return res.status(400).json({error:'Name and endpoint key are required'});const keyName=text(b.endpointKey).toLowerCase().replace(/[^a-z0-9_-]/g,'-').slice(0,100);let url='';if(b.url){try{url=safeUrl(b.url).toString();await assertPublicHost(new URL(url).hostname)}catch(e){return res.status(400).json({error:e.message})}}const r=(await q('INSERT INTO integration_webhooks(name,endpoint_key,direction,url,event_types,secret_encrypted,active,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8) RETURNING *',[text(b.name).slice(0,160),keyName,text(b.direction||'Outbound'),url,JSON.stringify(Array.isArray(b.eventTypes)?b.eventTypes:[]),encrypt(b.secret||''),b.active===undefined?true:Boolean(b.active),req.user.id]))[0];await audit(req.user,'INTEGRATION_WEBHOOK_CREATED','IntegrationWebhook',r.id,'Created integration webhook',null,r,req.req);res.status(201).json({...r,secret_encrypted:undefined,secretConfigured:Boolean(r.secret_encrypted)})});
  app.patch('/api/integration-webhooks/:id',auth,need('integrations.webhooks'),async(req,res)=>{const old=(await q('SELECT * FROM integration_webhooks WHERE id=$1',[req.params.id]))[0];if(!old)return res.status(404).json({error:'Webhook not found'});const b=req.body||{};let url=b.url===undefined?old.url:'';if(b.url!==undefined&&b.url){try{url=safeUrl(b.url).toString();await assertPublicHost(new URL(url).hostname)}catch(e){return res.status(400).json({error:e.message})}}const r=(await q('UPDATE integration_webhooks SET name=COALESCE($1,name),endpoint_key=COALESCE($2,endpoint_key),direction=COALESCE($3,direction),url=$4,event_types=COALESCE($5,event_types),secret_encrypted=$6,active=COALESCE($7,active),updated_by=$8,updated_at=now() WHERE id=$9 RETURNING *',[b.name?text(b.name).slice(0,160):null,b.endpointKey?text(b.endpointKey):null,b.direction?text(b.direction):null,url,b.eventTypes?JSON.stringify(b.eventTypes):null,b.secret===undefined?old.secret_encrypted:encrypt(b.secret),b.active===undefined?null:Boolean(b.active),req.user.id,req.params.id]))[0];res.json({...r,secret_encrypted:undefined,secretConfigured:Boolean(r.secret_encrypted)})});
  app.delete('/api/integration-webhooks/:id',auth,need('integrations.webhooks'),async(req,res)=>{const old=(await q('DELETE FROM integration_webhooks WHERE id=$1 RETURNING *',[req.params.id]))[0];if(!old)return res.status(404).json({error:'Webhook not found'});await audit(req.user,'INTEGRATION_WEBHOOK_DELETED','IntegrationWebhook',old.id,'Deleted integration webhook',old,null,req.req);res.json({ok:true})});
  app.get('/api/integration-events',auth,need('integrations.view'),async(req,res)=>res.json(await q('SELECT * FROM integration_events ORDER BY created_at DESC LIMIT 200')));
  app.get('/api/integration-deliveries',auth,need('integrations.view'),async(req,res)=>res.json(await q('SELECT d.*,w.name webhook_name FROM integration_deliveries d LEFT JOIN integration_webhooks w ON w.id=d.webhook_id ORDER BY d.attempted_at DESC LIMIT 200')));
  app.post('/api/integration-events/test',auth,need('integrations.manage'),async(req,res)=>{const b=req.body||{};const e=await emit(text(b.eventType||'test.event'),text(b.sourceModule||'Integration Hub'),'Test',null,b.payload||{});res.status(201).json(e)});

  app.post('/webhooks/integrations/:endpointKey',async(req,res)=>{
    const h=(await q("SELECT * FROM integration_webhooks WHERE endpoint_key=$1 AND direction='Inbound' AND active=true",[req.params.endpointKey]))[0];if(!h)return res.status(404).json({error:'Webhook not found'});
    const raw=req.rawBody||Buffer.from(JSON.stringify(req.body||{})), secret=decrypt(h.secret_encrypted), signature=text(req.get('x-amaan-signature')||req.get('x-amaal-signature'));
    if(secret){const expected='sha256='+crypto.createHmac('sha256',secret).update(raw).digest('hex');if(!signature||signature.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return res.status(401).json({error:'Invalid webhook signature'})}
    const e=await emit('integration.inbound', 'Integration Hub','InboundWebhook',h.id,{endpointKey:h.endpoint_key,body:req.body||{}});res.status(202).json({accepted:true,eventId:e.id});
  });
  let dispatchRunning=false;
  async function dispatchPending(){
    if(dispatchRunning)return; dispatchRunning=true;
    try{
      const events=await q("SELECT e.* FROM integration_events e WHERE e.status='Recorded' AND EXISTS(SELECT 1 FROM integration_webhooks w WHERE w.active=true AND w.direction='Outbound' AND (jsonb_array_length(w.event_types)=0 OR w.event_types ? e.event_type)) ORDER BY e.created_at LIMIT 25");
      for(const e of events){
        const hooks=await q("SELECT * FROM integration_webhooks WHERE active=true AND direction='Outbound' AND (jsonb_array_length(event_types)=0 OR event_types ? $1)",[e.event_type]);
        for(const h of hooks){
          if((await q('SELECT 1 FROM integration_deliveries WHERE webhook_id=$1 AND event_id=$2 LIMIT 1',[h.id,e.id])).length)continue;
          try{
            const u=safeUrl(h.url);await assertPublicHost(u.hostname);const body=JSON.stringify({eventId:e.id,eventType:e.event_type,sourceModule:e.source_module,resourceType:e.resource_type,resourceId:e.resource_id,payload:e.payload});const secret=decrypt(h.secret_encrypted);const headers={'Content-Type':'application/json','X-Amaal-Event':e.event_type,'X-Amaal-Event-Id':e.id};if(secret)headers['X-Amaal-Signature']='sha256='+crypto.createHmac('sha256',secret).update(body).digest('hex');const started=Date.now();const r=await fetch(u,{method:'POST',headers,body,redirect:'error',signal:AbortSignal.timeout(10000)});await pool.query('INSERT INTO integration_deliveries(webhook_id,event_id,status_code,response_ms,error_message) VALUES($1,$2,$3,$4,$5)',[h.id,e.id,r.status,Date.now()-started,r.ok?'':'Webhook returned an error']);await pool.query('UPDATE integration_webhooks SET last_delivery_at=now(),last_status_code=$2,last_error=$3,updated_at=now() WHERE id=$1',[h.id,r.status,r.ok?'':'Webhook returned an error']);
          }catch(err){await pool.query('INSERT INTO integration_deliveries(webhook_id,event_id,error_message) VALUES($1,$2,$3)',[h.id,e.id,err.message]);await pool.query('UPDATE integration_webhooks SET last_delivery_at=now(),last_status_code=NULL,last_error=$2,updated_at=now() WHERE id=$1',[h.id,err.message])}
        }
        const success=(await q("SELECT 1 FROM integration_deliveries WHERE event_id=$1 AND status_code BETWEEN 200 AND 299 LIMIT 1",[e.id])).length;
        const attempted=(await q('SELECT 1 FROM integration_deliveries WHERE event_id=$1 LIMIT 1',[e.id])).length;
        await pool.query('UPDATE integration_events SET status=$2 WHERE id=$1',[e.id,success?'Delivered':attempted?'Failed':'Recorded']);
      }
    }finally{dispatchRunning=false}
  }
  setInterval(()=>dispatchPending().catch(()=>{}),15000).unref();
  setTimeout(()=>dispatchPending().catch(()=>{}),5000).unref();
  return {emit};
}
