import crypto from 'crypto';
import dns from 'dns/promises';

export function registerIntegrationHub({app,auth,need,q,pool,audit}){
  const key=process.env.INTEGRATION_ENCRYPTION_KEY||process.env.JWT_SECRET||'';
  const keyBytes=crypto.createHash('sha256').update(key||'amaal-integration-fallback').digest();
  const encrypt=v=>{if(!v)return '';const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',keyBytes,iv);const out=Buffer.concat([c.update(String(v),'utf8'),c.final()]);return `${iv.toString('base64url')}.${c.getAuthTag().toString('base64url')}.${out.toString('base64url')}`};
  const decrypt=v=>{if(!v)return '';try{const [iv,tag,data]=String(v).split('.');if(!iv||!tag||!data)throw new Error('Invalid encrypted secret');const d=crypto.createDecipheriv('aes-256-gcm',keyBytes,Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([d.update(Buffer.from(data,'base64url')),d.final()]).toString('utf8')}catch{return ''}};
  const text=v=>String(v??'').trim();
  const jsonObject=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
  const payloadValue=v=>v===undefined?{}:v;
  function safeUrl(value){const u=new URL(text(value));if(u.protocol!=='https:')throw new Error('Integration URLs must use HTTPS');if(!u.hostname)throw new Error('Integration URL is required');return u}
  function isPrivateIp(ip){return /^(10\.|127\.|169\.254\.|192\.168\.|0\.)/.test(ip)||/^172\.(1[6-9]|2\d|3[0-1])\./.test(ip)||/^::1$|^fc|^fd|^fe80:/i.test(ip)}
  async function assertPublicHost(host){const h=host.toLowerCase();if(['localhost','localhost.localdomain'].includes(h))throw new Error('Private integration hosts are blocked');const records=await dns.lookup(h,{all:true});if(!records.length||records.some(r=>isPrivateIp(r.address)))throw new Error('Private or link-local integration destinations are blocked')}
  function publicRow(r){const x={...r};delete x.secret_encrypted;return {...x,secretConfigured:Boolean(r.secret_encrypted)}}
  const needSecret=(req,res,next)=>req.permissions?.has('integrations.secrets')?next():res.status(403).json({error:'Integration secret permission required'});
  function retryDelay(attempt){return Math.min(30*60*1000,Math.pow(2,Math.max(0,attempt-1))*15000)}
  function inboundSignature(req,raw,secret){const signature=text(req.get('x-amaal-signature')||req.get('x-amaan-signature'));if(!secret)return true;const expected='sha256='+crypto.createHmac('sha256',secret).update(raw).digest('hex');return Boolean(signature)&&signature.length===expected.length&&crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected))}

  async function createEvent({eventType,sourceModule,resourceType=null,resourceId=null,payload={},idempotencyKey=null}){
    const keyValue=text(idempotencyKey)||null;
    if(keyValue){const existing=(await q('SELECT * FROM integration_events WHERE event_key=$1 LIMIT 1',[keyValue]))[0];if(existing)return existing;}
    const e=(await q("INSERT INTO integration_events(event_type,source_module,resource_type,resource_id,payload,event_key,status) VALUES($1,$2,$3,$4,$5,$6,'Recorded') ON CONFLICT(event_key) DO UPDATE SET event_key=EXCLUDED.event_key RETURNING *",[text(eventType).slice(0,160),text(sourceModule).slice(0,120),resourceType?text(resourceType).slice(0,120):null,resourceId?text(resourceId).slice(0,200):null,JSON.stringify(payloadValue(payload)),keyValue]))[0];
    return e;
  }
  async function emit(eventType,sourceModule,resourceType,resourceId,payload={},idempotencyKey=null){return createEvent({eventType,sourceModule,resourceType,resourceId,payload,idempotencyKey})}

  async function deliverOne(h,e){
    const existing=(await q('SELECT * FROM integration_delivery_state WHERE webhook_id=$1 AND event_id=$2',[h.id,e.id]))[0];
    if(existing?.status==='Delivered')return existing;
    const attempt=(existing?.attempt_count||0)+1;
    try{
      const u=safeUrl(h.url);await assertPublicHost(u.hostname);
      const body=JSON.stringify({eventId:e.id,eventType:e.event_type,sourceModule:e.source_module,resourceType:e.resource_type,resourceId:e.resource_id,payload:e.payload});
      const secret=decrypt(h.secret_encrypted);const headers={'Content-Type':'application/json','X-Amaal-Event':e.event_type,'X-Amaal-Event-Id':e.id,'X-Amaal-Delivery-Attempt':String(attempt)};if(secret)headers['X-Amaal-Signature']='sha256='+crypto.createHmac('sha256',secret).update(body).digest('hex');
      const started=Date.now();const r=await fetch(u,{method:'POST',headers,body,redirect:'error',signal:AbortSignal.timeout(10000)});const ms=Date.now()-started;
      const ok=r.status>=200&&r.status<300;const retryable=!ok&&(r.status===408||r.status===425||r.status===429||r.status>=500);
      const next=retryable&&attempt<5?new Date(Date.now()+retryDelay(attempt)):null;
      await pool.query('INSERT INTO integration_deliveries(webhook_id,event_id,status_code,response_ms,error_message) VALUES($1,$2,$3,$4,$5)',[h.id,e.id,r.status,ms,ok?'':`Webhook returned HTTP ${r.status}`]);
      const row=(await q(`INSERT INTO integration_delivery_state(webhook_id,event_id,status,attempt_count,next_attempt_at,delivered_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(webhook_id,event_id) DO UPDATE SET status=EXCLUDED.status,attempt_count=EXCLUDED.attempt_count,next_attempt_at=EXCLUDED.next_attempt_at,delivered_at=EXCLUDED.delivered_at,updated_at=now() RETURNING *`,[h.id,e.id,ok?'Delivered':retryable&&attempt<5?'Pending':'Failed',attempt,next,ok?new Date():null]))[0];
      await pool.query('UPDATE integration_webhooks SET last_delivery_at=now(),last_status_code=$2,last_error=$3,updated_at=now() WHERE id=$1',[h.id,r.status,ok?'':`HTTP ${r.status}`]);
      return row;
    }catch(err){
      const retryable=attempt<5;const next=retryable?new Date(Date.now()+retryDelay(attempt)):null;
      await pool.query('INSERT INTO integration_deliveries(webhook_id,event_id,error_message) VALUES($1,$2,$3)',[h.id,e.id,String(err.message||err).slice(0,500)]);
      const row=(await q(`INSERT INTO integration_delivery_state(webhook_id,event_id,status,attempt_count,next_attempt_at) VALUES($1,$2,$3,$4,$5) ON CONFLICT(webhook_id,event_id) DO UPDATE SET status=EXCLUDED.status,attempt_count=EXCLUDED.attempt_count,next_attempt_at=EXCLUDED.next_attempt_at,updated_at=now() RETURNING *`,[h.id,e.id,retryable?'Pending':'Failed',attempt,next]))[0];
      await pool.query('UPDATE integration_webhooks SET last_delivery_at=now(),last_status_code=NULL,last_error=$2,updated_at=now() WHERE id=$1',[h.id,String(err.message||err).slice(0,500)]);return row;
    }
  }
  async function refreshEventStatus(eventId){
    const hooks=await q("SELECT id FROM integration_webhooks WHERE active=true AND direction='Outbound' AND (jsonb_array_length(event_types)=0 OR event_types ? (SELECT event_type FROM integration_events WHERE id=$1))",[eventId]);
    if(!hooks.length)return;
    const deliveries=await q('SELECT s.status FROM integration_delivery_state s WHERE s.event_id=$1',[eventId]);
    const delivered=new Set(deliveries.filter(d=>d.status==='Delivered').map((_,i)=>i));
    const hasPending=deliveries.some(d=>d.status==='Pending');
    const allDelivered=deliveries.length>=hooks.length&&deliveries.every(d=>d.status==='Delivered');
    const anyDelivered=delivered.size>0;
    const status=allDelivered?'Delivered':hasPending?'Recorded':anyDelivered?'Delivered':'Failed';
    await pool.query('UPDATE integration_events SET status=$2 WHERE id=$1',[eventId,status]);
  }

  app.get('/api/integrations',auth,need('integrations.view'),async(req,res)=>res.json((await q('SELECT * FROM integration_connections ORDER BY name')).map(publicRow)));
  app.post('/api/integrations',auth,need('integrations.manage'),needSecret,async(req,res)=>{try{const b=req.body||{};if(!text(b.name)||!text(b.provider))return res.status(400).json({error:'Name and provider are required'});if(b.secret&&!key)return res.status(500).json({error:'Integration encryption is not configured'});let base='';if(b.baseUrl){const u=safeUrl(b.baseUrl);await assertPublicHost(u.hostname);base=u.toString()}const config=jsonObject(b.config);const r=(await q('INSERT INTO integration_connections(name,provider,connection_type,base_url,auth_type,auth_header,secret_encrypted,config_json,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) RETURNING *',[text(b.name).slice(0,160),text(b.provider).slice(0,120),text(b.connectionType||'REST').slice(0,40),base,text(b.authType||'None'),text(b.authHeader||'Authorization').slice(0,120),encrypt(b.secret||''),JSON.stringify(config),req.user.id]))[0];await audit(req.user,'INTEGRATION_CREATED','Integration',r.id,'Created integration connection',null,publicRow(r),req.req);res.status(201).json(publicRow(r))}catch(e){res.status(400).json({error:e.message})}});
  app.patch('/api/integrations/:id',auth,need('integrations.manage'),needSecret,async(req,res)=>{try{const old=(await q('SELECT * FROM integration_connections WHERE id=$1',[req.params.id]))[0];if(!old)return res.status(404).json({error:'Integration not found'});const b=req.body||{};let base=b.baseUrl===undefined?old.base_url:'';if(b.baseUrl!==undefined&&b.baseUrl){const u=safeUrl(b.baseUrl);await assertPublicHost(u.hostname);base=u.toString()}if(b.secret!==undefined&&!key)return res.status(500).json({error:'Integration encryption is not configured'});const secret=b.secret===undefined?old.secret_encrypted:encrypt(b.secret);const config=b.config===undefined?old.config_json:JSON.stringify(jsonObject(b.config));const r=(await q('UPDATE integration_connections SET name=COALESCE($1,name),provider=COALESCE($2,provider),connection_type=COALESCE($3,connection_type),base_url=$4,auth_type=COALESCE($5,auth_type),auth_header=COALESCE($6,auth_header),secret_encrypted=$7,config_json=$8,updated_by=$9,updated_at=now() WHERE id=$10 RETURNING *',[b.name?text(b.name).slice(0,160):null,b.provider?text(b.provider).slice(0,120):null,b.connectionType?text(b.connectionType).slice(0,40):null,base,b.authType?text(b.authType):null,b.authHeader?text(b.authHeader).slice(0,120):null,secret,config,req.user.id,req.params.id]))[0];await audit(req.user,'INTEGRATION_UPDATED','Integration',r.id,'Updated integration connection',publicRow(old),publicRow(r),req.req);res.json(publicRow(r))}catch(e){res.status(400).json({error:e.message})}});
  app.delete('/api/integrations/:id',auth,need('integrations.manage'),async(req,res)=>{const old=(await q('SELECT * FROM integration_connections WHERE id=$1',[req.params.id]))[0];if(!old)return res.status(404).json({error:'Integration not found'});const updated=(await q("UPDATE integration_connections SET status='Suspended',updated_at=now(),updated_by=$1 WHERE id=$2 RETURNING *",[req.user.id,old.id]))[0];await audit(req.user,'INTEGRATION_SUSPENDED','Integration',old.id,'Suspended integration instead of deleting its connection record',publicRow(old),publicRow(updated),req.req);res.json({ok:true,archived:true,status:updated.status})});
  app.post('/api/integrations/:id/test',auth,need('integrations.manage'),needSecret,async(req,res)=>{const r=(await q('SELECT * FROM integration_connections WHERE id=$1',[req.params.id]))[0];if(!r)return res.status(404).json({error:'Integration not found'});try{if(!r.base_url)return res.status(400).json({error:'Integration base URL is not configured'});const u=safeUrl(r.base_url);await assertPublicHost(u.hostname);const headers={};const secret=decrypt(r.secret_encrypted);if(secret&&r.auth_type==='Bearer')headers[r.auth_header||'Authorization']=`Bearer ${secret}`;else if(secret&&r.auth_type==='API Key')headers[r.auth_header||'X-API-Key']=secret;else if(secret&&r.auth_type==='Basic')headers[r.auth_header||'Authorization']=`Basic ${Buffer.from(secret).toString('base64')}`;const started=Date.now();const response=await fetch(u,{headers,redirect:'error',signal:AbortSignal.timeout(10000)});const ms=Date.now()-started;await pool.query('UPDATE integration_connections SET status=$2,last_tested_at=now(),last_error=$3,updated_at=now() WHERE id=$1',[r.id,response.ok?'Active':'Error',response.ok?'':`HTTP ${response.status}`]);res.json({ok:response.ok,status:response.status,responseMs:ms})}catch(e){await pool.query("UPDATE integration_connections SET status='Error',last_tested_at=now(),last_error=$2,updated_at=now() WHERE id=$1",[r.id,String(e.message||e).slice(0,500)]);res.status(502).json({error:e.message})}});

  app.get('/api/integration-webhooks',auth,need('integrations.view'),async(req,res)=>res.json((await q('SELECT * FROM integration_webhooks ORDER BY name')).map(publicRow)));
  app.post('/api/integration-webhooks',auth,need('integrations.webhooks'),needSecret,async(req,res)=>{try{const b=req.body||{};if(!text(b.name)||!text(b.endpointKey))return res.status(400).json({error:'Name and endpoint key are required'});const direction=text(b.direction||'Outbound');if(!['Inbound','Outbound'].includes(direction))return res.status(400).json({error:'Invalid webhook direction'});if(direction==='Inbound'&&!text(b.secret))return res.status(400).json({error:'Inbound webhooks require a signing secret'});const keyName=text(b.endpointKey).toLowerCase().replace(/[^a-z0-9_-]/g,'-').slice(0,100);if(!keyName)return res.status(400).json({error:'Invalid endpoint key'});let url='';if(b.url){const u=safeUrl(b.url);await assertPublicHost(u.hostname);url=u.toString()}const types=Array.isArray(b.eventTypes)?[...new Set(b.eventTypes.map(text).filter(Boolean).slice(0,100))]:[];const r=(await q('INSERT INTO integration_webhooks(name,endpoint_key,direction,url,event_types,secret_encrypted,active,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8) RETURNING *',[text(b.name).slice(0,160),keyName,direction,url,JSON.stringify(types),encrypt(b.secret||''),b.active===undefined?true:Boolean(b.active),req.user.id]))[0];await audit(req.user,'INTEGRATION_WEBHOOK_CREATED','IntegrationWebhook',r.id,'Created integration webhook',null,publicRow(r),req.req);res.status(201).json(publicRow(r))}catch(e){res.status(400).json({error:e.message})}});
  app.patch('/api/integration-webhooks/:id',auth,need('integrations.webhooks'),needSecret,async(req,res)=>{try{const old=(await q('SELECT * FROM integration_webhooks WHERE id=$1',[req.params.id]))[0];if(!old)return res.status(404).json({error:'Webhook not found'});const b=req.body||{};const direction=b.direction===undefined?old.direction:text(b.direction);if(!['Inbound','Outbound'].includes(direction))return res.status(400).json({error:'Invalid webhook direction'});if(direction==='Inbound'&&b.secret!==undefined&&!text(b.secret))return res.status(400).json({error:'Inbound webhooks require a signing secret'});let url=b.url===undefined?old.url:'';if(b.url!==undefined&&b.url){const u=safeUrl(b.url);await assertPublicHost(u.hostname);url=u.toString()}const secret=b.secret===undefined?old.secret_encrypted:encrypt(b.secret);const types=b.eventTypes===undefined?old.event_types:JSON.stringify(Array.isArray(b.eventTypes)?[...new Set(b.eventTypes.map(text).filter(Boolean).slice(0,100))]:[]);const r=(await q('UPDATE integration_webhooks SET name=COALESCE($1,name),endpoint_key=COALESCE($2,endpoint_key),direction=$3,url=$4,event_types=$5,secret_encrypted=$6,active=COALESCE($7,active),updated_by=$8,updated_at=now() WHERE id=$9 RETURNING *',[b.name?text(b.name).slice(0,160):null,b.endpointKey?text(b.endpointKey).toLowerCase().replace(/[^a-z0-9_-]/g,'-').slice(0,100):null,direction,url,types,secret,b.active===undefined?null:Boolean(b.active),req.user.id,req.params.id]))[0];if(direction==='Inbound'&&!r.secret_encrypted)throw new Error('Inbound webhooks require a signing secret');res.json(publicRow(r))}catch(e){res.status(400).json({error:e.message})}});
  app.delete('/api/integration-webhooks/:id',auth,need('integrations.webhooks'),async(req,res)=>{const old=(await q('SELECT * FROM integration_webhooks WHERE id=$1',[req.params.id]))[0];if(!old)return res.status(404).json({error:'Webhook not found'});const updated=(await q("UPDATE integration_webhooks SET active=false,updated_at=now(),updated_by=$1 WHERE id=$2 RETURNING *",[req.user.id,old.id]))[0];await audit(req.user,'INTEGRATION_WEBHOOK_SUSPENDED','IntegrationWebhook',old.id,'Disabled webhook instead of deleting its record',publicRow(old),publicRow(updated),req.req);res.json({ok:true,archived:true,active:updated.active})});
  app.get('/api/integration-events',auth,need('integrations.view'),async(req,res)=>{const limit=Math.min(500,Math.max(1,Number(req.query.limit)||200));res.json(await q('SELECT * FROM integration_events ORDER BY created_at DESC LIMIT $1',[limit]))});
  app.get('/api/integration-health',auth,need('integrations.view'),async(req,res)=>{const connections=(await q("SELECT count(*)::int total,count(*) FILTER(WHERE status='Active')::int active,count(*) FILTER(WHERE status='Error')::int errors FROM integration_connections"))[0];const webhooks=(await q("SELECT count(*)::int total,count(*) FILTER(WHERE active) FILTER(WHERE direction='Outbound')::int outbound,count(*) FILTER(WHERE active) FILTER(WHERE direction='Inbound')::int inbound FROM integration_webhooks"))[0];const events=(await q("SELECT count(*)::int total,count(*) FILTER(WHERE status='Failed')::int failed,count(*) FILTER(WHERE status='Recorded')::int pending FROM integration_events WHERE created_at>now()-interval '24 hours'"))[0];const deliveries=(await q("SELECT count(*)::int pending FROM integration_delivery_state WHERE status='Pending'"))[0];res.json({ok:true,connections,webhooks,events,deliveries})});
  app.get('/api/integration-deliveries',auth,need('integrations.view'),async(req,res)=>{const limit=Math.min(500,Math.max(1,Number(req.query.limit)||200));res.json(await q('SELECT d.*,w.name webhook_name FROM integration_deliveries d LEFT JOIN integration_webhooks w ON w.id=d.webhook_id ORDER BY d.attempted_at DESC LIMIT $1',[limit]))});
  app.post('/api/integration-events/test',auth,need('integrations.manage'),async(req,res)=>{const b=req.body||{};const e=await emit(text(b.eventType||'test.event'),text(b.sourceModule||'Integration Hub'),'Test',null,payloadValue(b.payload),text(b.idempotencyKey)||null);res.status(201).json(e)});
  app.post('/api/integration-events/:id/replay',auth,need('integrations.manage'),async(req,res)=>{const e=(await q('SELECT * FROM integration_events WHERE id=$1',[req.params.id]))[0];if(!e)return res.status(404).json({error:'Event not found'});await pool.query("UPDATE integration_delivery_state SET status='Failed',next_attempt_at=now(),updated_at=now() WHERE event_id=$1 AND status<>'Delivered'",[e.id]);await pool.query("UPDATE integration_events SET status='Recorded' WHERE id=$1",[e.id]);await audit(req.user,'INTEGRATION_EVENT_REPLAYED','IntegrationEvent',e.id,'Requested event replay',null,{eventType:e.event_type},req.req);res.status(202).json({accepted:true,eventId:e.id})});

  app.post('/webhooks/integrations/:endpointKey',async(req,res)=>{
    const h=(await q("SELECT * FROM integration_webhooks WHERE endpoint_key=$1 AND direction='Inbound' AND active=true",[req.params.endpointKey]))[0];if(!h)return res.status(404).json({error:'Webhook not found'});
    const raw=req.rawBody||Buffer.from(JSON.stringify(req.body||{}));const secret=decrypt(h.secret_encrypted);if(!inboundSignature(req,raw,secret))return res.status(401).json({error:'Invalid webhook signature'});
    const idem=text(req.get('x-idempotency-key')||req.get('x-amaal-event-id'));const eventKey=idem?`inbound:${h.id}:${idem}`:null;if(eventKey){const prior=(await q('SELECT id FROM integration_events WHERE event_key=$1',[eventKey]))[0];if(prior)return res.status(200).json({accepted:true,eventId:prior.id,duplicate:true})}
    const e=await createEvent({eventType:'integration.inbound',sourceModule:'Integration Hub',resourceType:'InboundWebhook',resourceId:h.id,payload:{endpointKey:h.endpoint_key,body:payloadValue(req.body)},idempotencyKey:eventKey});res.status(202).json({accepted:true,eventId:e.id});
  });

  let dispatchRunning=false;
  async function dispatchPending(){
    if(dispatchRunning)return;dispatchRunning=true;
    try{
      const events=await q("SELECT e.* FROM integration_events e WHERE e.status IN ('Recorded','Failed') AND EXISTS(SELECT 1 FROM integration_webhooks w WHERE w.active=true AND w.direction='Outbound' AND (jsonb_array_length(w.event_types)=0 OR w.event_types ? e.event_type)) ORDER BY e.created_at LIMIT 50");
      for(const e of events){
        const hooks=await q("SELECT * FROM integration_webhooks WHERE active=true AND direction='Outbound' AND (jsonb_array_length(event_types)=0 OR event_types ? $1)",[e.event_type]);
        for(const h of hooks){const d=(await q('SELECT * FROM integration_delivery_state WHERE webhook_id=$1 AND event_id=$2',[h.id,e.id]))[0];if(d?.status==='Delivered')continue;if(d?.next_attempt_at&&new Date(d.next_attempt_at).getTime()>Date.now())continue;await deliverOne(h,e)}
        await refreshEventStatus(e.id);
      }
    }finally{dispatchRunning=false}
  }
  setInterval(()=>dispatchPending().catch(()=>{}),15000).unref();setTimeout(()=>dispatchPending().catch(()=>{}),5000).unref();
  return {emit,dispatchPending};
}
