export function registerPricingPromotions({app,auth,need,q,pool,audit}){
 const text=v=>String(v??'').trim(); const money=v=>{const n=Number(v);if(!Number.isFinite(n)||n<0)throw new Error('Invalid monetary value');return Math.round(n*100)/100};
 const iso=v=>v?new Date(v):null;
 app.get('/api/pricing/summary',auth,need('pricing.view'),async(req,res)=>{const [lists,promos,coupons,items]=await Promise.all([q("SELECT count(*)::int c FROM price_lists WHERE status='Active'"),q("SELECT count(*)::int c FROM promotions WHERE status IN ('Active','Scheduled') AND (starts_at IS NULL OR starts_at<=now()) AND (ends_at IS NULL OR ends_at>now())"),q("SELECT count(*)::int c FROM coupons WHERE status='Active'"),q('SELECT count(*)::int c FROM price_list_items')]);res.json({activePriceLists:lists[0].c,activePromotions:promos[0].c,activeCoupons:coupons[0].c,pricedVariants:items[0].c})});
 app.get('/api/pricing/lists',auth,need('pricing.view'),async(req,res)=>res.json(await q('SELECT l.*,count(i.id)::int item_count FROM price_lists l LEFT JOIN price_list_items i ON i.price_list_id=l.id GROUP BY l.id ORDER BY l.priority,l.name')));
 app.post('/api/pricing/lists',auth,need('pricing.manage'),async(req,res)=>{const b=req.body||{};if(!text(b.name)||!text(b.code))return res.status(400).json({error:'Name and code are required'});const x=(await q('INSERT INTO price_lists(name,code,customer_type,currency,priority,status,valid_from,valid_to,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[text(b.name),text(b.code).toUpperCase(),text(b.customerType)||'Retail',text(b.currency)||'UGX',Number(b.priority)||100,text(b.status)||'Active',iso(b.validFrom),iso(b.validTo),req.user.id]))[0];await audit(req.user,'PRICE_LIST_CREATED','PriceList',x.id,`Created price list ${x.name}`,null,x,req.req);res.status(201).json(x)});
 app.patch('/api/pricing/lists/:id',auth,need('pricing.manage'),async(req,res)=>{const old=(await q('SELECT * FROM price_lists WHERE id=$1',[req.params.id]))[0];if(!old)return res.status(404).json({error:'Price list not found'});const x=(await q('UPDATE price_lists SET name=COALESCE($1,name),customer_type=COALESCE($2,customer_type),currency=COALESCE($3,currency),priority=COALESCE($4,priority),status=COALESCE($5,status),valid_from=$6,valid_to=$7,updated_at=now() WHERE id=$8 RETURNING *',[text(req.body.name)||null,text(req.body.customerType)||null,text(req.body.currency)||null,req.body.priority==null?null:Number(req.body.priority),text(req.body.status)||null,req.body.validFrom?iso(req.body.validFrom):old.valid_from,req.body.validTo?iso(req.body.validTo):old.valid_to,req.params.id]))[0];await audit(req.user,'PRICE_LIST_UPDATED','PriceList',x.id,'Updated price list',old,x,req.req);res.json(x)});
 app.get('/api/pricing/lists/:id/items',auth,need('pricing.view'),async(req,res)=>res.json(await q('SELECT i.*,v.sku,v.variant_name,p.name product_name FROM price_list_items i JOIN product_variants v ON v.id=i.variant_id JOIN products p ON p.id=v.product_id WHERE i.price_list_id=$1 ORDER BY p.name,v.variant_name',[req.params.id])));
 app.post('/api/pricing/lists/:id/items',auth,need('pricing.manage'),async(req,res)=>{const price=money(req.body.price);const x=(await q('INSERT INTO price_list_items(price_list_id,variant_id,price,compare_at_price) VALUES($1,$2,$3,$4) ON CONFLICT(price_list_id,variant_id) DO UPDATE SET price=EXCLUDED.price,compare_at_price=EXCLUDED.compare_at_price,updated_at=now() RETURNING *',[req.params.id,req.body.variantId,price,req.body.compareAtPrice==null?null:money(req.body.compareAtPrice)]))[0];await audit(req.user,'PRICE_LIST_ITEM_UPSERTED','PriceListItem',x.id,'Updated price list item',null,x,req.req);res.status(201).json(x)});
 app.delete('/api/pricing/lists/:id/items/:itemId',auth,need('pricing.manage'),async(req,res)=>{const x=(await q('DELETE FROM price_list_items WHERE id=$1 AND price_list_id=$2 RETURNING *',[req.params.itemId,req.params.id]))[0];if(!x)return res.status(404).json({error:'Price item not found'});await audit(req.user,'PRICE_LIST_ITEM_REMOVED','PriceListItem',x.id,'Removed price list item',x,null,req.req);res.json({ok:true})});
 app.get('/api/pricing/variants',auth,need('pricing.view'),async(req,res)=>{const t=`%${text(req.query.q)}%`;res.json(await q(`SELECT v.id,v.sku,v.variant_name,v.selling_price,p.name product_name FROM product_variants v JOIN products p ON p.id=v.product_id WHERE p.status='Active' AND v.status='Active' AND ($1='' OR p.name ILIKE $2 OR v.sku ILIKE $2 OR v.variant_name ILIKE $2) ORDER BY p.name,v.variant_name LIMIT 100`,[text(req.query.q),t]))});
 app.get('/api/pricing/effective/:variantId',auth,need('pricing.view'),async(req,res)=>{const r=(await q('SELECT * FROM amaal_effective_variant_price($1,$2)',[req.params.variantId,text(req.query.customerType)||'Retail']))[0];if(!r)return res.status(404).json({error:'Variant not found'});res.json(r)});
 app.get('/api/promotions',auth,need('promotions.view'),async(req,res)=>res.json(await q('SELECT p.*,count(DISTINCT pp.product_id)::int product_count,count(DISTINCT pc.category_id)::int category_count,count(DISTINCT pb.brand_id)::int brand_count FROM promotions p LEFT JOIN promotion_products pp ON pp.promotion_id=p.id LEFT JOIN promotion_categories pc ON pc.promotion_id=p.id LEFT JOIN promotion_brands pb ON pb.promotion_id=p.id GROUP BY p.id ORDER BY p.priority,p.created_at DESC')));
 app.post('/api/promotions',auth,need('promotions.manage'),async(req,res)=>{const b=req.body||{};if(!text(b.name)||!['Percentage','Fixed Amount'].includes(b.type))return res.status(400).json({error:'Promotion name and type are required'});const value=money(b.value);if(b.type==='Percentage'&&value>100)return res.status(400).json({error:'Percentage cannot exceed 100'});const x=(await q('INSERT INTO promotions(name,code,type,value,scope_type,starts_at,ends_at,status,priority,stackable,max_uses,per_customer_limit,banner_text,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *',[text(b.name),text(b.code)||null,text(b.type),value,text(b.scopeType)||'All',iso(b.startsAt),iso(b.endsAt),text(b.status)||'Draft',Number(b.priority)||100,b.stackable==='true'||b.stackable===true,b.maxUses?Number(b.maxUses):null,b.perCustomerLimit?Number(b.perCustomerLimit):null,text(b.bannerText),req.user.id]))[0];await audit(req.user,'PROMOTION_CREATED','Promotion',x.id,`Created promotion ${x.name}`,null,x,req.req);res.status(201).json(x)});
 app.patch('/api/promotions/:id',auth,need('promotions.manage'),async(req,res)=>{const old=(await q('SELECT * FROM promotions WHERE id=$1',[req.params.id]))[0];if(!old)return res.status(404).json({error:'Promotion not found'});const x=(await q('UPDATE promotions SET name=COALESCE($1,name),code=COALESCE($2,code),type=COALESCE($3,type),value=COALESCE($4,value),scope_type=COALESCE($5,scope_type),starts_at=$6,ends_at=$7,status=COALESCE($8,status),priority=COALESCE($9,priority),stackable=COALESCE($10,stackable),max_uses=$11,per_customer_limit=$12,banner_text=COALESCE($13,banner_text),updated_at=now() WHERE id=$14 RETURNING *',[text(req.body.name)||null,text(req.body.code)||null,text(req.body.type)||null,req.body.value==null?null:money(req.body.value),text(req.body.scopeType)||null,req.body.startsAt?iso(req.body.startsAt):old.starts_at,req.body.endsAt?iso(req.body.endsAt):old.ends_at,text(req.body.status)||null,req.body.priority==null?null:Number(req.body.priority),req.body.stackable==null?null:Boolean(req.body.stackable),req.body.maxUses==null?null:Number(req.body.maxUses),req.body.perCustomerLimit==null?null:Number(req.body.perCustomerLimit),req.body.bannerText==null?null:text(req.body.bannerText),req.params.id]))[0];await audit(req.user,'PROMOTION_UPDATED','Promotion',x.id,'Updated promotion',old,x,req.req);res.json(x)});
 async function attach(req,res,type){const map={product:['promotion_products','product_id'],category:['promotion_categories','category_id'],brand:['promotion_brands','brand_id']};const [table,col]=map[type];const id=req.body?.targetId;if(!id)return res.status(400).json({error:'Target is required'});await pool.query(`INSERT INTO ${table}(promotion_id,${col}) VALUES($1,$2) ON CONFLICT DO NOTHING`,[req.params.id,id]);await audit(req.user,'PROMOTION_TARGET_ATTACHED','Promotion',req.params.id,`Attached ${type} target`,null,{type,targetId:id},req.req);res.status(201).json({ok:true})}
 app.post('/api/promotions/:id/targets/:type',auth,need('promotions.manage'),(req,res)=>attach(req,res,req.params.type));
 app.delete('/api/promotions/:id/targets/:type/:targetId',auth,need('promotions.manage'),async(req,res)=>{const map={product:['promotion_products','product_id'],category:['promotion_categories','category_id'],brand:['promotion_brands','brand_id']};if(!map[req.params.type])return res.status(400).json({error:'Invalid target type'});const [table,col]=map[req.params.type];await pool.query(`DELETE FROM ${table} WHERE promotion_id=$1 AND ${col}=$2`,[req.params.id,req.params.targetId]);res.json({ok:true})});
 app.get('/api/promotions/:id/targets',auth,need('promotions.view'),async(req,res)=>{const id=req.params.id;const [products,categories,brands]=await Promise.all([q('SELECT p.id,p.name FROM promotion_products x JOIN products p ON p.id=x.product_id WHERE x.promotion_id=$1',[id]),q('SELECT c.id,c.name FROM promotion_categories x JOIN product_categories c ON c.id=x.category_id WHERE x.promotion_id=$1',[id]),q('SELECT b.id,b.name FROM promotion_brands x JOIN brands b ON b.id=x.brand_id WHERE x.promotion_id=$1',[id])]);res.json({products,categories,brands})});
 app.get('/api/coupons',auth,need('promotions.view'),async(req,res)=>res.json(await q('SELECT c.*,p.name promotion_name FROM coupons c JOIN promotions p ON p.id=c.promotion_id ORDER BY c.created_at DESC')));
 app.post('/api/coupons',auth,need('promotions.manage'),async(req,res)=>{const code=text(req.body.code).toUpperCase();if(!code||!req.body.promotionId)return res.status(400).json({error:'Coupon code and promotion are required'});const x=(await q('INSERT INTO coupons(code,promotion_id,status,max_redemptions,per_customer_limit,starts_at,ends_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[code,req.body.promotionId,text(req.body.status)||'Active',req.body.maxRedemptions?Number(req.body.maxRedemptions):null,req.body.perCustomerLimit?Number(req.body.perCustomerLimit):null,iso(req.body.startsAt),iso(req.body.endsAt),req.user.id]))[0];await audit(req.user,'COUPON_CREATED','Coupon',x.id,`Created coupon ${x.code}`,null,x,req.req);res.status(201).json(x)});
 app.get('/api/pricing/export',auth,need('pricing.export'),async(req,res)=>{const rows=await q(`SELECT p.name product_name,v.sku,v.variant_name,v.selling_price,COALESCE((SELECT i.price FROM price_list_items i JOIN price_lists l ON l.id=i.price_list_id WHERE i.variant_id=v.id AND l.status='Active' AND l.customer_type='Retail' ORDER BY l.priority,l.updated_at DESC LIMIT 1),v.selling_price) retail_price FROM product_variants v JOIN products p ON p.id=v.product_id ORDER BY p.name,v.variant_name`);const csv=v=>{const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s};res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename=amaal-pricing-export.csv');res.send(['product,sku,variant,selling_price,retail_price',...rows.map(r=>[r.product_name,r.sku,r.variant_name,r.selling_price,r.retail_price].map(csv).join(','))].join('\n'))});
}
