import crypto from "crypto";
export function registerPhase7({app,auth,need,q,pool,audit,changeStock}){
  const text=v=>String(v??'').trim();
  const money=v=>Math.round((Number(v)||0)*100)/100;
  const orderNo=()=>`WEB-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;
  const allowedTransitions={
    'Pending Payment':['Paid','Cancelled'],
    'Paid':['Processing','Cancelled','Refunded'],
    'Processing':['Packed','Cancelled'],
    'Packed':['Ready for Dispatch','Cancelled'],
    'Ready for Dispatch':['Dispatched','Cancelled'],
    'Dispatched':['Delivered'],
    'Delivered':[],
    'Cancelled':[], 'Refunded':[], 'Returned':[]
  };
  async function orderById(id){
    const o=(await q(`SELECT o.*,c.name customer_name,c.customer_no,c.phone customer_phone,c.email customer_email,l.name location_name,u.email created_by_email
      FROM orders o LEFT JOIN customers c ON c.id=o.customer_id JOIN inventory_locations l ON l.id=o.location_id LEFT JOIN users u ON u.id=o.created_by WHERE o.id=$1`,[id]))[0];
    if(!o)return null;
    o.lines=await q(`SELECT ol.*,v.sku,v.variant_name,v.serialized,p.name product_name FROM order_lines ol JOIN product_variants v ON v.id=ol.variant_id JOIN products p ON p.id=v.product_id WHERE ol.order_id=$1 ORDER BY ol.created_at`,[id]);
    o.serials=await q(`SELECT os.*,su.serial_number,su.imei1,su.imei2,ol.variant_id FROM order_serial_units os JOIN serialized_units su ON su.id=os.serialized_unit_id JOIN order_lines ol ON ol.id=os.order_line_id WHERE ol.order_id=$1 ORDER BY os.created_at`,[id]);
    o.payments=await q(`SELECT * FROM order_payments WHERE order_id=$1 ORDER BY created_at`,[id]);
    o.statusHistory=await q(`SELECT h.*,u.email actor_email FROM order_status_history h LEFT JOIN users u ON u.id=h.actor_id WHERE h.order_id=$1 ORDER BY h.created_at`,[id]);
    o.fulfillments=await q(`SELECT f.*,u.email assigned_email FROM order_fulfillments f LEFT JOIN users u ON u.id=f.assigned_to WHERE f.order_id=$1 ORDER BY f.created_at DESC`,[id]);
    return o;
  }
  async function releaseOrderReservations(client,id,status='Cancelled'){
    const rows=(await client.query("SELECT id FROM inventory_reservations WHERE reference_type='Order' AND reference_id=$1 AND status='Active' FOR UPDATE",[id])).rows;
    for(const r of rows)await client.query("UPDATE inventory_reservations SET status=$1,released_at=now() WHERE id=$2",[status==='Cancelled'?'Cancelled':'Released',r.id]);
  }
  app.get('/api/orders/summary',auth,need('orders.view'),async(req,res)=>{
    const [all,pending,paid,processing,dispatch,delivered,revenue]=await Promise.all([
      q('SELECT count(*)::int c FROM orders'),q("SELECT count(*)::int c FROM orders WHERE status='Pending Payment'"),q("SELECT count(*)::int c FROM orders WHERE status='Paid'"),q("SELECT count(*)::int c FROM orders WHERE status IN ('Processing','Packed','Ready for Dispatch')"),q("SELECT count(*)::int c FROM orders WHERE status='Dispatched'"),q("SELECT count(*)::int c FROM orders WHERE status='Delivered'"),q("SELECT COALESCE(sum(grand_total),0)::numeric total FROM orders WHERE status NOT IN ('Cancelled','Refunded') AND created_at>=date_trunc('month',now())")
    ]);res.json({total:all[0].c,pending:pending[0].c,paid:paid[0].c,processing:processing[0].c,dispatched:dispatch[0].c,delivered:delivered[0].c,monthRevenue:revenue[0].total});
  });
  app.get('/api/orders',auth,need('orders.view'),async(req,res)=>{
    const limit=Math.min(Math.max(Number(req.query.limit)||100,1),200);const params=[];const where=[];const qtext=text(req.query.q);if(qtext){params.push(`%${qtext}%`);where.push(`(o.order_no ILIKE $${params.length} OR COALESCE(c.name,'') ILIKE $${params.length} OR COALESCE(c.phone,'') ILIKE $${params.length})`)}if(req.query.status){params.push(req.query.status);where.push(`o.status=$${params.length}`)}params.push(limit);
    const rows=await q(`SELECT o.id,o.order_no,o.status,o.payment_status,o.fulfillment_status,o.currency,o.grand_total,o.created_at,o.updated_at,c.name customer_name,c.customer_no,l.name location_name,COUNT(ol.id)::int line_count,COALESCE(SUM(ol.quantity),0)::numeric units FROM orders o LEFT JOIN customers c ON c.id=o.customer_id JOIN inventory_locations l ON l.id=o.location_id LEFT JOIN order_lines ol ON ol.order_id=o.id ${where.length?'WHERE '+where.join(' AND '):''} GROUP BY o.id,c.name,c.customer_no,l.name ORDER BY o.created_at DESC LIMIT $${params.length}`,params);res.json(rows);
  });
  app.get('/api/orders/:id',auth,need('orders.view'),async(req,res)=>{const o=await orderById(req.params.id);if(!o)return res.status(404).json({error:'Order not found'});res.json(o)});
  app.post('/api/orders',auth,need('orders.create'),async(req,res)=>{
    const b=req.body||{},lines=Array.isArray(b.lines)?b.lines:[];if(!b.locationId||!lines.length)return res.status(400).json({error:'Selling location and at least one order line are required'});
    const client=await pool.connect();try{await client.query('BEGIN');const loc=(await client.query("SELECT id,status FROM inventory_locations WHERE id=$1 FOR SHARE",[b.locationId])).rows[0];if(!loc||loc.status!=='Active')throw new Error('Selling location is not active');
      if(b.customerId){const c=(await client.query('SELECT id,status FROM customers WHERE id=$1 FOR SHARE',[b.customerId])).rows[0];if(!c)throw new Error('Customer not found');if(c.status==='Anonymized')throw new Error('Anonymized customers cannot be used for orders')}
      let subtotal=0,discount=0,tax=0;const prepared=[];
      for(const raw of lines){const qty=Number(raw.quantity);if(!raw.variantId||!(qty>0))throw new Error('Every order line requires a valid variant and positive quantity');const v=(await client.query(`SELECT v.*,p.name product_name FROM product_variants v JOIN products p ON p.id=v.product_id WHERE v.id=$1 AND v.status='Active' FOR SHARE`,[raw.variantId])).rows[0];if(!v)throw new Error('Product variant not found');const unit=raw.unitPrice===undefined?money(v.selling_price):money(raw.unitPrice);if(unit<0)throw new Error('Unit price cannot be negative');const disc=Math.min(Math.max(money(raw.discountAmount||0),0),money(unit*qty));const taxable=Math.max(0,money(unit*qty-disc));const rate=raw.taxRate===undefined?money(v.tax_rate):Math.max(0,money(raw.taxRate));const tx=money(taxable*rate/100);const total=money(taxable+tx);if(v.track_inventory){const bal=(await client.query('SELECT on_hand,reserved FROM inventory_balances WHERE variant_id=$1 AND location_id=$2 FOR UPDATE',[v.id,b.locationId])).rows[0];const available=bal?Number(bal.on_hand)-Number(bal.reserved):0;if(available+1e-9<qty)throw new Error(`Insufficient available stock for ${v.product_name} (${v.sku})`)}prepared.push({v,qty,unit,disc,rate,tx,total});subtotal=money(subtotal+unit*qty);discount=money(discount+disc);tax=money(tax+tx)}
      const shipping=money(b.shippingAmount||0);const grand=money(subtotal-discount+tax+shipping);const o=(await client.query(`INSERT INTO orders(order_no,customer_id,location_id,status,payment_status,fulfillment_status,subtotal,discount_amount,tax_amount,shipping_amount,grand_total,currency,shipping_name,shipping_phone,shipping_email,shipping_address,notes,created_by) VALUES($1,$2,$3,'Pending Payment','Pending','Unfulfilled',$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`,[orderNo(),b.customerId||null,b.locationId,subtotal,discount,tax,shipping,grand,text(b.currency)||'UGX',text(b.shippingName),text(b.shippingPhone),text(b.shippingEmail),text(b.shippingAddress),text(b.notes),req.user.id])).rows[0];
      for(const x of prepared){const line=(await client.query(`INSERT INTO order_lines(order_id,variant_id,quantity,unit_price,discount_amount,tax_rate,tax_amount,line_total,cost_price) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[o.id,x.v.id,x.qty,x.unit,x.disc,x.rate,x.tx,x.total,money(x.v.cost_price)])).rows[0];if(x.v.track_inventory){await client.query(`INSERT INTO inventory_reservations(variant_id,location_id,quantity,status,reference_type,reference_id,expires_at,created_by) VALUES($1,$2,$3,'Active','Order',$4,now()+interval '24 hours',$5)`,[x.v.id,b.locationId,x.qty,o.id,req.user.id])}}
      await client.query("INSERT INTO order_status_history(order_id,status,actor_id,notes) VALUES($1,'Pending Payment',$2,$3)",[o.id,req.user.id,'Order created']);await client.query('COMMIT');await audit(req.user,'ORDER_CREATED','Order',o.id,`Created order ${o.order_no}`,null,o,req.req);res.status(201).json(await orderById(o.id));
    }catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}
  });
  app.post('/api/orders/:id/payment',auth,need('orders.manage'),async(req,res)=>{const amount=money(req.body?.amount),method=text(req.body?.method);if(amount<=0||!method)return res.status(400).json({error:'Payment method and positive amount are required'});const client=await pool.connect();try{await client.query('BEGIN');const o=(await client.query("SELECT * FROM orders WHERE id=$1 FOR UPDATE",[req.params.id])).rows[0];if(!o)throw new Error('Order not found');if(['Cancelled','Refunded','Delivered','Returned'].includes(o.status))throw new Error('Order cannot receive payment in its current status');const paid=(await client.query("SELECT COALESCE(sum(amount),0)::numeric total FROM order_payments WHERE order_id=$1 AND status='Completed'",[o.id])).rows[0].total;const due=money(Number(o.grand_total)-Number(paid));if(amount>due+0.009)throw new Error(`Payment exceeds balance of ${due}`);await client.query('INSERT INTO order_payments(order_id,method,amount,reference,status,received_by) VALUES($1,$2,$3,$4,\'Completed\',$5)',[o.id,method,amount,text(req.body?.reference),req.user.id]);const newPaid=money(Number(paid)+amount);const ps=Math.abs(newPaid-Number(o.grand_total))<0.009?'Paid':'Partially Paid';const status=ps==='Paid'&&o.status==='Pending Payment'?'Paid':o.status;const u=(await client.query('UPDATE orders SET payment_status=$1,status=$2,updated_at=now() WHERE id=$3 RETURNING *',[ps,status,o.id])).rows[0];if(status!==o.status)await client.query('INSERT INTO order_status_history(order_id,status,actor_id,notes) VALUES($1,$2,$3,$4)',[o.id,status,req.user.id,'Payment received']);await client.query('COMMIT');await audit(req.user,'ORDER_PAYMENT_RECORDED','Order',o.id,`Recorded ${method} payment for ${o.order_no}`,o,u,req.req);res.json(await orderById(o.id));}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
  app.post('/api/orders/:id/serials',auth,need('orders.manage'),async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const o=(await client.query("SELECT * FROM orders WHERE id=$1 AND status IN ('Paid','Processing','Packed','Ready for Dispatch') FOR UPDATE",[req.params.id])).rows[0];if(!o)throw new Error('Order is not available for serial assignment');const line=(await client.query('SELECT * FROM order_lines WHERE id=$1 AND order_id=$2 FOR SHARE',[req.body?.orderLineId,o.id])).rows[0];if(!line)throw new Error('Order line not found');const v=(await client.query('SELECT serialized FROM product_variants WHERE id=$1',[line.variant_id])).rows[0];if(!v?.serialized)throw new Error('This order line is not serialized');const assigned=(await client.query('SELECT count(*)::int c FROM order_serial_units WHERE order_line_id=$1',[line.id])).rows[0].c;if(assigned>=Number(line.quantity))throw new Error('All required serial units are already assigned');const su=(await client.query("SELECT * FROM serialized_units WHERE id=$1 AND variant_id=$2 AND location_id=$3 AND status='In Stock' FOR UPDATE",[req.body?.serializedUnitId,line.variant_id,o.location_id])).rows[0];if(!su)throw new Error('Serialized unit is not available at the order location');const r=(await client.query('INSERT INTO order_serial_units(order_line_id,serialized_unit_id,assigned_by) VALUES($1,$2,$3) RETURNING *',[line.id,su.id,req.user.id])).rows[0];await client.query('COMMIT');await audit(req.user,'ORDER_SERIAL_ASSIGNED','Order',o.id,`Assigned serial/IMEI to ${o.order_no}`,null,r,req.req);res.status(201).json(r)}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
  app.post('/api/orders/:id/status',auth,need('orders.manage'),async(req,res)=>{const next=text(req.body?.status),client=await pool.connect();try{await client.query('BEGIN');const o=(await client.query('SELECT * FROM orders WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!o)throw new Error('Order not found');if(!Object.prototype.hasOwnProperty.call(allowedTransitions,o.status)||!allowedTransitions[o.status].includes(next))throw new Error(`Cannot move order from ${o.status} to ${next}`);if(['Processing','Packed','Ready for Dispatch','Dispatched','Delivered'].includes(next)&&o.payment_status!=='Paid')throw new Error('Order must be fully paid before fulfillment');if(next==='Cancelled')await releaseOrderReservations(client,o.id,'Cancelled');if(next==='Delivered'){const lines=(await client.query('SELECT ol.*,v.serialized FROM order_lines ol JOIN product_variants v ON v.id=ol.variant_id WHERE ol.order_id=$1',[o.id])).rows;for(const line of lines){if(line.serialized){const assigned=(await client.query('SELECT count(*)::int c FROM order_serial_units WHERE order_line_id=$1',[line.id])).rows[0].c;if(assigned!==Number(line.quantity))throw new Error('Every serialized order line must have all serial/IMEI units assigned before delivery')}}const reservations=(await client.query("SELECT * FROM inventory_reservations WHERE reference_type='Order' AND reference_id=$1 AND status='Active' FOR UPDATE",[o.id])).rows;for(const r of reservations){await changeStock(client,{variantId:r.variant_id,locationId:r.location_id,delta:-Number(r.quantity),type:'ORDER_FULFILLMENT',actorId:req.user.id,referenceType:'Order',referenceId:o.id,reason:`Order ${o.order_no} delivered`,unitCost:0});await client.query("UPDATE inventory_reservations SET status='Consumed',released_at=now() WHERE id=$1",[r.id])}const serials=(await client.query('SELECT su.id FROM order_serial_units os JOIN serialized_units su ON su.id=os.serialized_unit_id JOIN order_lines ol ON ol.id=os.order_line_id WHERE ol.order_id=$1 FOR UPDATE',[o.id])).rows;for(const su of serials)await client.query("UPDATE serialized_units SET status='Sold',location_id=NULL,sold_at=now(),updated_at=now() WHERE id=$1",[su.id])}
      const fulStatus=['Processing','Packed','Ready for Dispatch','Dispatched','Delivered'].includes(next)?next:'Unfulfilled';const u=(await client.query('UPDATE orders SET status=$1,fulfillment_status=$2,updated_at=now(),cancelled_at=CASE WHEN $1=\'Cancelled\' THEN now() ELSE cancelled_at END WHERE id=$3 RETURNING *',[next,fulStatus,o.id])).rows[0];await client.query('INSERT INTO order_status_history(order_id,status,actor_id,notes) VALUES($1,$2,$3,$4)',[o.id,next,req.user.id,text(req.body?.notes)||`Order moved to ${next}`]);await client.query('COMMIT');await audit(req.user,'ORDER_STATUS_CHANGED','Order',o.id,`Moved ${o.order_no} to ${next}`,o,u,req.req);res.json(await orderById(o.id));}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
  app.post('/api/orders/:id/fulfillment',auth,need('orders.manage'),async(req,res)=>{const o=(await q('SELECT id,status FROM orders WHERE id=$1',[req.params.id]))[0];if(!o)return res.status(404).json({error:'Order not found'});const f=(await q('INSERT INTO order_fulfillments(order_id,method,tracking_number,carrier,assigned_to,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[o.id,text(req.body?.method)||'Delivery',text(req.body?.trackingNumber),text(req.body?.carrier),req.body?.assignedTo||null,text(req.body?.status)||'Pending',text(req.body?.notes)]))[0];await audit(req.user,'ORDER_FULFILLMENT_CREATED','OrderFulfillment',f.id,`Created fulfillment for order ${o.id}`,null,f,req.req);res.status(201).json(f)});
  app.get('/api/orders/export',auth,need('orders.export'),async(req,res)=>{const rows=await q(`SELECT o.order_no,o.status,o.payment_status,o.fulfillment_status,o.created_at,c.customer_no,c.name customer_name,l.name location,o.grand_total,o.currency FROM orders o LEFT JOIN customers c ON c.id=o.customer_id JOIN inventory_locations l ON l.id=o.location_id ORDER BY o.created_at DESC LIMIT 10000`);const csv=v=>{const x=String(v??'');return /[",\n]/.test(x)?`"${x.replace(/"/g,'""')}"`:x};res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename=amaal-orders-export.csv');res.send(['order_no,status,payment_status,fulfillment_status,created_at,customer_no,customer_name,location,total,currency',...rows.map(r=>[r.order_no,r.status,r.payment_status,r.fulfillment_status,r.created_at,r.customer_no,r.customer_name,r.location,r.grand_total,r.currency].map(csv).join(','))].join('\n'))});
}
