import express from 'express';
import pg from 'pg';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import {fileURLToPath} from 'url';

const {Pool}=pg; const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express(); app.use(express.json({limit:'1mb'}));
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('sslmode=require')?{rejectUnauthorized:false}:undefined});
const JWT_SECRET=process.env.JWT_SECRET; if(!JWT_SECRET) console.warn('JWT_SECRET is not set');
const perms=[['dashboard.view','View dashboard'],['staff.view','View staff'],['staff.manage','Manage staff'],['roles.view','View roles'],['roles.manage','Manage roles'],['branches.view','View branches'],['branches.manage','Manage branches'],['settings.view','View settings'],['settings.manage','Manage settings'],['audit.view','View audit logs'],['notifications.view','View notifications'],['notifications.manage','Manage notifications']];
const baseSettings={currency:'UGX',timezone:'Africa/Kampala',sessionMinutes:60,maxLoginAttempts:5,lockoutMinutes:15};
const requestId=()=>crypto.randomUUID();
async function q(text,params=[]){return (await pool.query(text,params)).rows}
async function init(){const schema=fs.readFileSync(path.join(__dirname,'schema.sql'),'utf8'); await pool.query(schema); for(const [id,description] of perms) await pool.query('INSERT INTO permissions(id,description) VALUES($1,$2) ON CONFLICT(id) DO NOTHING',[id,description]); const roles=[['Super Admin','Full administrative access.',true],['Administrator','Administrative operations.',true],['Manager','Dashboard and operational visibility.',true]]; for(const r of roles){const rr=await q('INSERT INTO roles(name,description,system) VALUES($1,$2,$3) ON CONFLICT(name) DO UPDATE SET description=EXCLUDED.description RETURNING id',[...r]); const role=rr[0]; let allowed=perms.map(x=>x[0]); if(r[0]==='Administrator') allowed=['dashboard.view','staff.view','staff.manage','roles.view','branches.view','branches.manage','settings.view','audit.view','notifications.view','notifications.manage']; if(r[0]==='Manager') allowed=['dashboard.view','branches.view','notifications.view']; for(const p of allowed) await pool.query('INSERT INTO role_permissions(role_id,permission_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[role.id,p]);}}
async function audit(actor,action,type,id,detail,before=null,after=null,req={}){await pool.query('INSERT INTO audit_logs(actor_id,action,resource_type,resource_id,detail,before_json,after_json,request_id,ip,user_agent) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[actor?.id||null,action,type,id,detail,before,after,req.id||requestId(),req.ip,req.ua])}
function sign(user,sessionId){return jwt.sign({sub:user.id,sid:sessionId},JWT_SECRET,{expiresIn:'12h'})}
async function auth(req,res,next){try{const h=req.headers.authorization||''; if(!h.startsWith('Bearer ')) return res.status(401).json({error:'Authentication required'}); const p=jwt.verify(h.slice(7),JWT_SECRET); const s=(await q('SELECT * FROM sessions WHERE id=$1 AND user_id=$2 AND revoked_at IS NULL AND expires_at>now()',[p.sid,p.sub]))[0]; if(!s)return res.status(401).json({error:'Session expired'}); const u=(await q('SELECT id,name,email,status,created_at FROM users WHERE id=$1',[p.sub]))[0]; if(!u||u.status!=='Active')return res.status(401).json({error:'Account inactive'}); await pool.query('UPDATE sessions SET last_seen_at=now() WHERE id=$1',[s.id]); req.user=u; req.session=s; req.permissions=new Set((await q('SELECT rp.permission_id FROM role_permissions rp JOIN user_roles ur ON ur.role_id=rp.role_id WHERE ur.user_id=$1',[u.id])).map(x=>x.permission_id)); req.req={id:requestId(),ip:req.ip,ua:req.get('user-agent')}; next()}catch(e){return res.status(401).json({error:'Invalid or expired session'})}}
const need=p=> (req,res,next)=>req.permissions.has(p)?next():res.status(403).json({error:'Permission denied'});
app.get('/api/health',async(req,res)=>{try{await q('SELECT 1');res.json({ok:true})}catch(e){res.status(503).json({ok:false})}});
app.post('/api/setup',async(req,res)=>{const existing=await q('SELECT count(*)::int c FROM users');if(existing[0].c>0)return res.status(409).json({error:'Administrator already configured'});const {companyName='Amaal Telecoms',email,password,phone='',address=''}=req.body;if(!email||!password||password.length<10)return res.status(400).json({error:'Email and a password of at least 10 characters are required'});const role=(await q("SELECT id FROM roles WHERE name='Super Admin'"))[0];const hash=await bcrypt.hash(password,12);const u=(await q('INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email,status,created_at',['Administrator',email.toLowerCase().trim(),hash]))[0];await pool.query('INSERT INTO user_roles(user_id,role_id) VALUES($1,$2)',[u.id,role.id]);for(const [k,v] of Object.entries({...baseSettings,companyName,companyEmail:u.email,companyPhone:phone,companyAddress:address})) await pool.query('INSERT INTO settings(key,value_json) VALUES($1,$2) ON CONFLICT(key) DO NOTHING',[k,JSON.stringify(v)]);await audit(u,'INITIAL_SETUP','System',null,'Created the first administrator',null,{email:u.email});const sid=crypto.randomUUID();await pool.query('INSERT INTO sessions(id,user_id,token_hash,expires_at,ip,user_agent) VALUES($1,$2,$3,now()+interval \'12 hours\',$4,$5)',[sid,u.id,crypto.createHash('sha256').update(sid+JWT_SECRET).digest('hex'),req.ip,req.get('user-agent')]);res.json({token:sign(u,sid),user:u})});
app.post('/api/login',async(req,res)=>{const {email,password}=req.body;const u=(await q('SELECT * FROM users WHERE email=$1',[String(email||'').toLowerCase().trim()]))[0];if(!u)return res.status(401).json({error:'Invalid credentials'});if(u.status!=='Active')return res.status(403).json({error:'Account inactive'});if(u.locked_until&&new Date(u.locked_until)>new Date())return res.status(423).json({error:'Account temporarily locked'});const ok=await bcrypt.compare(password||'',u.password_hash);if(!ok){const attempts=u.failed_attempts+1;const limit=Number((await q("SELECT value_json FROM settings WHERE key='maxLoginAttempts'"))[0]?.value_json||5);const locked=attempts>=limit?new Date(Date.now()+15*60000):null;await pool.query('UPDATE users SET failed_attempts=$1,locked_until=$2,updated_at=now() WHERE id=$3',[attempts,locked,u.id]);await audit(u,'LOGIN_FAILED','Authentication',u.id,locked?'Account locked after failed attempts':'Invalid credentials',null,null,{id:requestId(),ip:req.ip,ua:req.get('user-agent')});return res.status(401).json({error:locked?'Too many attempts. Account temporarily locked.':'Invalid credentials'})}await pool.query('UPDATE users SET failed_attempts=0,locked_until=null WHERE id=$1',[u.id]);const sid=crypto.randomUUID();await pool.query('INSERT INTO sessions(id,user_id,token_hash,expires_at,ip,user_agent) VALUES($1,$2,$3,now()+interval \'12 hours\',$4,$5)',[sid,u.id,crypto.createHash('sha256').update(sid+JWT_SECRET).digest('hex'),req.ip,req.get('user-agent')]);await audit(u,'LOGIN','Authentication',u.id,'Administrator signed in',null,null,{id:requestId(),ip:req.ip,ua:req.get('user-agent')});res.json({token:sign(u,sid),user:{id:u.id,name:u.name,email:u.email,status:u.status}})});
app.post('/api/logout',auth,async(req,res)=>{await pool.query('UPDATE sessions SET revoked_at=now() WHERE id=$1',[req.session.id]);await audit(req.user,'LOGOUT','Authentication',req.user.id,'Administrator signed out',null,null,req.req);res.json({ok:true})});
app.get('/api/me',auth,async(req,res)=>{res.json({user:req.user,permissions:[...req.permissions]})});
app.get('/api/dashboard',auth,need('dashboard.view'),async(req,res)=>{const [users,branches,audits,notes]=await Promise.all([q('SELECT count(*)::int c FROM users'),q("SELECT count(*)::int c FROM branches WHERE status='Active'"),q('SELECT count(*)::int c FROM audit_logs'),q('SELECT count(*)::int c FROM notifications WHERE read_at IS NULL AND (user_id=$1 OR user_id IS NULL)',[req.user.id])]);res.json({users:users[0].c,activeBranches:branches[0].c,auditEvents:audits[0].c,unreadNotifications:notes[0].c})});
app.get('/api/staff',auth,need('staff.view'),async(req,res)=>res.json(await q('SELECT u.id,u.name,u.email,u.status,u.created_at,COALESCE(json_agg(DISTINCT r.name) FILTER(WHERE r.id IS NOT NULL),\'[]\') roles,COALESCE(json_agg(DISTINCT b.name) FILTER(WHERE b.id IS NOT NULL),\'[]\') branches FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id LEFT JOIN user_branches ub ON ub.user_id=u.id LEFT JOIN branches b ON b.id=ub.branch_id GROUP BY u.id ORDER BY u.created_at DESC')));
app.get('/api/roles',auth,need('roles.view'),async(req,res)=>res.json(await q('SELECT r.*,COALESCE(array_agg(rp.permission_id) FILTER(WHERE rp.permission_id IS NOT NULL),ARRAY[]::text[]) permissions FROM roles r LEFT JOIN role_permissions rp ON rp.role_id=r.id GROUP BY r.id ORDER BY r.name')));
app.get('/api/permissions',auth,need('roles.view'),async(req,res)=>res.json(await q('SELECT * FROM permissions ORDER BY id')));
app.post('/api/roles',auth,need('roles.manage'),async(req,res)=>{const {name,description='',permissions=[]}=req.body;if(!name)return res.status(400).json({error:'Role name required'});const r=(await q('INSERT INTO roles(name,description,system) VALUES($1,$2,false) RETURNING *',[name.trim(),description.trim()]))[0];for(const p of permissions)await pool.query('INSERT INTO role_permissions(role_id,permission_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[r.id,p]);await audit(req.user,'ROLE_CREATED','Role',r.id,`Created ${r.name}`,null,{...r,permissions},req.req);res.status(201).json(r)});
app.get('/api/branches',auth,need('branches.view'),async(req,res)=>res.json(await q('SELECT * FROM branches ORDER BY name')));
app.post('/api/branches',auth,need('branches.manage'),async(req,res)=>{const {name,address=''}=req.body;if(!name)return res.status(400).json({error:'Branch name required'});const b=(await q('INSERT INTO branches(name,address) VALUES($1,$2) RETURNING *',[name.trim(),address.trim()]))[0];await audit(req.user,'BRANCH_CREATED','Branch',b.id,`Created ${b.name}`,null,b,req.req);res.status(201).json(b)});
app.patch('/api/branches/:id',auth,need('branches.manage'),async(req,res)=>{const old=(await q('SELECT * FROM branches WHERE id=$1',[req.params.id]))[0];if(!old)return res.status(404).json({error:'Branch not found'});const b=(await q('UPDATE branches SET name=COALESCE($1,name),address=COALESCE($2,address),status=COALESCE($3,status) WHERE id=$4 RETURNING *',[req.body.name,req.body.address,req.body.status,req.params.id]))[0];await audit(req.user,'BRANCH_UPDATED','Branch',b.id,'Updated branch',old,b,req.req);res.json(b)});
app.get('/api/audit',auth,need('audit.view'),async(req,res)=>res.json(await q('SELECT a.*,u.email actor_email,b.name branch_name FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_id LEFT JOIN branches b ON b.id=a.branch_id ORDER BY a.created_at DESC LIMIT 500')));
app.get('/api/notifications',auth,need('notifications.view'),async(req,res)=>res.json(await q('SELECT * FROM notifications WHERE user_id=$1 OR user_id IS NULL ORDER BY created_at DESC LIMIT 200',[req.user.id])));
app.post('/api/notifications',auth,need('notifications.manage'),async(req,res)=>{const n=(await q('INSERT INTO notifications(user_id,title,body) VALUES($1,$2,$3) RETURNING *',[req.body.userId||null,req.body.title||'Notification',req.body.body||'']))[0];await audit(req.user,'NOTIFICATION_CREATED','Notification',n.id,'Created notification',null,n,req.req);res.status(201).json(n)});
app.patch('/api/notifications/:id/read',auth,need('notifications.view'),async(req,res)=>{const n=(await q('UPDATE notifications SET read_at=now() WHERE id=$1 AND (user_id=$2 OR user_id IS NULL) RETURNING *',[req.params.id,req.user.id]))[0];res.json(n||null)});
app.get('/api/settings',auth,need('settings.view'),async(req,res)=>{const rows=await q('SELECT key,value_json FROM settings');res.json(Object.fromEntries(rows.map(x=>[x.key,x.value_json])))});
app.put('/api/settings',auth,need('settings.manage'),async(req,res)=>{const before=Object.fromEntries((await q('SELECT key,value_json FROM settings')).map(x=>[x.key,x.value_json]));for(const [k,v] of Object.entries(req.body||{}))await pool.query('INSERT INTO settings(key,value_json,updated_by) VALUES($1,$2,$3) ON CONFLICT(key) DO UPDATE SET value_json=EXCLUDED.value_json,updated_by=EXCLUDED.updated_by,updated_at=now()',[k,JSON.stringify(v),req.user.id]);const after=Object.fromEntries((await q('SELECT key,value_json FROM settings')).map(x=>[x.key,x.value_json]));await audit(req.user,'SETTINGS_UPDATED','Settings',null,'Updated system settings',before,after,req.req);res.json(after)});
app.patch('/api/users/:id/status',auth,need('staff.manage'),async(req,res)=>{const old=(await q('SELECT id,name,email,status FROM users WHERE id=$1',[req.params.id]))[0];if(!old)return res.status(404).json({error:'User not found'});if(old.id===req.user.id)return res.status(400).json({error:'You cannot suspend your own account'});const u=(await q("UPDATE users SET status=$1,updated_at=now() WHERE id=$2 RETURNING id,name,email,status",[req.body.status,req.params.id]))[0];await audit(req.user,'STAFF_STATUS_CHANGED','User',u.id,'Changed staff status',old,u,req.req);res.json(u)});
app.post('/api/users',auth,need('staff.manage'),async(req,res)=>{const {name,email,password,roleId,branchIds=[]}=req.body;if(!name||!email||!password||password.length<10)return res.status(400).json({error:'Name, email and password of at least 10 characters are required'});const hash=await bcrypt.hash(password,12);const u=(await q('INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email,status,created_at',[name.trim(),email.toLowerCase().trim(),hash]))[0];if(roleId)await pool.query('INSERT INTO user_roles(user_id,role_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[u.id,roleId]);for(const b of branchIds)await pool.query('INSERT INTO user_branches(user_id,branch_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[u.id,b]);await audit(req.user,'STAFF_CREATED','User',u.id,'Created staff account',null,u,req.req);res.status(201).json(u)});
app.get('/api/sessions',auth,async(req,res)=>res.json(await q('SELECT id,created_at,last_seen_at,expires_at,ip,user_agent FROM sessions WHERE user_id=$1 AND revoked_at IS NULL ORDER BY created_at DESC',[req.user.id])));
app.delete('/api/sessions/:id',auth,async(req,res)=>{await pool.query('UPDATE sessions SET revoked_at=now() WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true})});
app.use(express.static(path.join(__dirname,'public'))); app.get('/{*splat}',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
init().then(()=>app.listen(process.env.PORT||4000,()=>console.log(`Amaal Admin listening on ${process.env.PORT||4000}`))).catch(e=>{console.error(e);process.exit(1)});
