'use client';
import Link from 'next/link';import {useMemo,useState} from 'react';
import type {ComputerProduct} from '../lib/computer-catalogue';
export default function ComputerCatalogueClient({items}:{items:ComputerProduct[]}){
 const [q,setQ]=useState('');const [brand,setBrand]=useState('All');const [tier,setTier]=useState('All');const [size,setSize]=useState('All sizes');const [sort,setSort]=useState('Featured');
 const brands=useMemo(()=>Array.from(new Set(items.map(x=>x.brand))),[items]);
 const filtered=useMemo(()=>{let a=items.filter(p=>(brand==='All'||p.brand===brand)&&(tier==='All'||p.tier===tier)&&(size==='All sizes'||p.specs.Screen?.toLowerCase().includes(size.toLowerCase())||p.specs.Display?.toLowerCase().includes(size.toLowerCase()))&&(!q||`${p.name} ${p.brand} ${p.family} ${p.type}`.toLowerCase().includes(q.toLowerCase())));if(sort==='A–Z')a=[...a].sort((x,y)=>x.name.localeCompare(y.name));if(sort==='Brand')a=[...a].sort((x,y)=>x.brand.localeCompare(y.brand)||x.name.localeCompare(y.name));return a},[items,brand,tier,size,q,sort]);
 return <div className="catalogue-shell"><div className="catalogue-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search laptops, MacBook, ThinkPad…" aria-label="Search computers"/><select value={brand} onChange={e=>setBrand(e.target.value)}><option>All</option>{brands.map(b=><option key={b}>{b}</option>)}</select><select value={tier} onChange={e=>setTier(e.target.value)}><option>All</option><option value="EVERYDAY">Everyday</option><option value="PREMIUM">Premium</option><option value="GAMING">Gaming</option></select><select value={size} onChange={e=>setSize(e.target.value)}><option>All sizes</option><option>13</option><option>14</option><option>15</option><option>16</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option>Featured</option><option>A–Z</option><option>Brand</option></select></div><div className="results-line"><span>{filtered.length} {filtered.length===1?'computer':'computers'}</span>{(q||brand!=='All'||tier!=='All'||size!=='All sizes'||sort!=='Featured')&&<button onClick={()=>{setQ('');setBrand('All');setTier('All');setSize('All sizes');setSort('Featured')}}>Clear</button>}</div>{filtered.length?<div className="product-grid computerGrid">{filtered.map(p=><Link href={`/categories/computers/laptops/${p.slug}`} className="computerCard" key={p.slug}><div className="computerCardMedia"><span>AMAAL</span><strong>{p.name}</strong><small>Product image</small></div><div className="computerCardBody"><small>{p.tier}</small><h3>{p.name}</h3><p>{p.shortDescription}</p><div>{p.quickSpecs.slice(0,4).map(s=><span key={s}>{s}</span>)}</div><strong className="comingSoon">Price coming soon</strong></div></Link>)}</div>:<div className="catalogue-empty"><h3>No computers match those choices.</h3><p>Try a different brand, performance level or screen size.</p></div>}</div>
}
