'use client';
import Link from 'next/link';import {Bell,MapPin,Package,RefreshCw,ShieldCheck,Truck} from 'lucide-react';import {useEffect,useState} from 'react';import {getLocalOrders} from '../lib/commerce';
const KEY='amaal_customer_token_v1';
const api=()=>process.env.NEXT_PUBLIC_API_BASE_URL||process.env.AMAAL_API_BASE_URL||'';
export default function CustomerPortal(){const [token,setToken]=useState('');const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [address,setAddress]=useState({label:'Home',addressLine1:'',addressLine2:'',city:'Kampala',region:'Central',postalCode:'',isDefault:true});const [message,setMessage]=useState('');
 useEffect(()=>{const t=localStorage.getItem(KEY)||'';setToken(t);if(t)load(t)},[]);
 async function load(t=token){if(!t)return;setError('');const r=await fetch(`${api()}/api/public/account`,{headers:{'X-Amaal-Customer-Token':t}});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||'Customer access has expired.');return}setData(d)}
 if(!token&&!data)return <div className="customer-access"><div><p className="eyebrow">MY AMAAL</p><h2>Keep your orders and care journeys together.</h2><p>After checkout, Amaal gives you a private access token for this account on this device. Paste it below if you are returning from another device.</p><input value={token} onChange={e=>setToken(e.target.value.trim())} placeholder="Customer access token"/><button className="button gold" onClick={()=>{localStorage.setItem(KEY,token);load(token)}}>Open my account</button><small>Your order number and phone can still be used for tracking without an account.</small></div></div>;
 if(error)return <div className="customer-access"><h2>Account access needs attention.</h2><p>{error}</p><button className="button outline" onClick={()=>{localStorage.removeItem(KEY);setToken('');setData(null);setError('')}}>Use another access token</button></div>;
 if(!data)return <div className="customer-access"><RefreshCw className="spin"/><p>Loading your Amaal account…</p></div>;
 const local=getLocalOrders();return <div className="customer-portal"><div className="portal-head"><div><p className="eyebrow">WELCOME BACK</p><h1>{data.customer.name}</h1><p>{data.customer.phone}{data.customer.email?` · ${data.customer.email}`:''}</p></div><button className="button outline" onClick={()=>load()}>Refresh</button></div><div className="portal-grid"><section className="portal-card"><Package/><h2>Orders</h2><p>{data.orders.length} saved order{data.orders.length===1?'':'s'}.</p>{data.orders.slice(0,5).map((o:any)=><Link key={o.id} href={`/tracking?order=${encodeURIComponent(o.order_no)}`} className="portal-row"><span><b>{o.order_no}</b><small>{o.status} · {o.delivery_status||'Delivery pending'}</small></span><strong>UGX {Number(o.grand_total||0).toLocaleString('en-UG')}</strong></Link>)}{local.length>0&&<small>Recent orders placed on this device are also available in <Link href="/account/orders">Order history</Link>.</small>}</section><section className="portal-card"><MapPin/><h2>Saved addresses</h2>{data.addresses.map((a:any)=><div className="portal-row" key={a.id}><span><b>{a.label}</b><small>{[a.address_line1,a.address_line2,a.city,a.region].filter(Boolean).join(', ')}</small></span>{a.is_default&&<strong>Default</strong>}</div>)}<div className="address-form"><input placeholder="Address" value={address.addressLine1} onChange={e=>setAddress({...address,addressLine1:e.target.value})}/><input placeholder="City" value={address.city} onChange={e=>setAddress({...address,city:e.target.value})}/><button className="button outline" onClick={async()=>{const r=await fetch(`${api()}/api/public/account/addresses`,{method:'POST',headers:{'Content-Type':'application/json','X-Amaal-Customer-Token':token},body:JSON.stringify(address)});const d=await r.json().catch(()=>({}));setMessage(r.ok?'Address saved.':d.error||'Unable to save address.');if(r.ok)load()}}>Save address</button></div>{message&&<small>{message}</small>}</section><section className="portal-card"><Truck/><h2>Delivery</h2><p>Track every order from confirmation to delivery.</p><Link className="portal-link" href="/tracking">Open tracking <span>→</span></Link></section><section className="portal-card"><ShieldCheck/><h2>Care & warranty</h2><p>Keep returns, warranty requests and repairs in one place.</p><Link className="portal-link" href="/services">Open service centre <span>→</span></Link></section><section className="portal-card"><Bell/><h2>Updates</h2>{data.notifications.length?data.notifications.slice(0,5).map((n:any)=><div className="notification-row" key={n.id}><b>{n.title}</b><p>{n.body}</p></div>):<p>No account updates yet.</p>}</section></div></div>}
