
'use client';
import {useEffect,useState} from 'react';
import {LockKeyhole,LogIn,ShieldCheck,UserPlus} from 'lucide-react';
import {activateWithAccessToken,customerRequest,googleSignInUrl,login,logout,register,CUSTOMER_AUTH_EVENT} from '../lib/customer-auth';import {mergeGuestCartWithCustomer,mergeWishlistWithCustomer} from '../lib/commerce';
export default function CustomerAuthPanel(){
 const [mode,setMode]=useState<'login'|'register'|'activate'>('login');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [customer,setCustomer]=useState<any>(null);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const [form,setForm]=useState({name:'',email:'',phone:'',identifier:'',password:'',confirm:'',accessToken:''});
 async function refresh(){setLoading(true);try{const d=await customerRequest('/api/public/auth/me');setCustomer(d.authenticated?d.customer:null)}catch{setCustomer(null)}finally{setLoading(false)}}
 useEffect(()=>{refresh();const fn=()=>refresh();window.addEventListener(CUSTOMER_AUTH_EVENT,fn);return()=>window.removeEventListener(CUSTOMER_AUTH_EVENT,fn)},[]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const result=params.get('google');if(result){window.history.replaceState({},'',window.location.pathname);if(result==='success'){Promise.all([mergeGuestCartWithCustomer(),mergeWishlistWithCustomer()]).then(()=>refresh());setMessage('You are signed in with Google.')}else setError(params.get('message')||'Google sign-in could not be completed.')}},[]);
 async function submit(e:any){e.preventDefault();setBusy(true);setError('');setMessage('');try{if(mode==='login'){await login(form.identifier,form.password, true);await Promise.all([mergeGuestCartWithCustomer(),mergeWishlistWithCustomer()]);setMessage('You are signed in.');}else if(mode==='register'){if(form.password!==form.confirm)throw new Error('Passwords do not match.');await register({name:form.name,email:form.email||undefined,phone:form.phone||undefined,password:form.password,remember:true});await Promise.all([mergeGuestCartWithCustomer(),mergeWishlistWithCustomer()]);setMessage('Your Amaal account is ready.');}else{if(form.password!==form.confirm)throw new Error('Passwords do not match.');await activateWithAccessToken(form.accessToken,form.password,form.name||undefined);await Promise.all([mergeGuestCartWithCustomer(),mergeWishlistWithCustomer()]);setMessage('Your Amaal account has been activated.');}await refresh();}catch(err:any){setError(err.message||'Unable to complete this request.')}finally{setBusy(false)}}
 if(loading)return <div className="customer-auth-card"><p className="eyebrow">MY AMAAL</p><p>Checking your account…</p></div>;
 if(customer)return <div className="customer-auth-card signed-in"><div><p className="eyebrow">SIGNED IN</p><h2>{customer.name}</h2><p>{customer.email||customer.phone}</p><small>Your private account session is active on this device.</small></div><button className="button outline" onClick={()=>logout()}>Sign out</button></div>;
 return <div className="customer-auth-card"><div className="auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}><LogIn size={16}/> Sign in</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}><UserPlus size={16}/> Create account</button><button className={mode==='activate'?'active':''} onClick={()=>setMode('activate')}><ShieldCheck size={16}/> Activate</button></div><div className="auth-copy"><p className="eyebrow">PRIVATE CUSTOMER ACCOUNT</p><h2>{mode==='login'?'Welcome back.':mode==='register'?'Create your Amaal account.':'Already shopped with Amaal?'}</h2><p>{mode==='activate'?'Use the private access token from a previous Amaal checkout to set a password and move your order history into a secure account.':'Keep orders, addresses, saved products and after-sales care together.'}</p></div><a className="button outline google-auth-button" href={googleSignInUrl('/account')}>Continue with Google</a><div className="auth-divider"><span>or</span></div><form onSubmit={submit} className="auth-form">{mode!=='login'&&<input required={mode==='register'} placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>} {mode==='register'&&<><input type="email" placeholder="Email address" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Phone number" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></>} {mode==='login'&&<input required placeholder="Email or phone" autoComplete="username" value={form.identifier} onChange={e=>setForm({...form,identifier:e.target.value})}/>} {mode==='activate'&&<input required placeholder="Amaal access token" value={form.accessToken} onChange={e=>setForm({...form,accessToken:e.target.value})}/>} <input required type="password" minLength={12} placeholder="Password" autoComplete={mode==='login'?'current-password':'new-password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{mode!=='login'&&<input required type="password" minLength={12} placeholder="Confirm password" value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/>}<button className="button gold" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':mode==='register'?'Create account':'Activate account'}</button></form>{error&&<p className="auth-error">{error}</p>}{message&&<p className="auth-success">{message}</p>}<div className="auth-note"><LockKeyhole size={15}/><span>Passwords are protected server-side. Your customer account is separate from Amaal staff access.</span></div></div>
}
