'use client';
import {useMemo} from 'react';
import Link from 'next/link';
import WishlistButton from './WishlistButton';
import AddToBag from './AddToBag';
import {image,type Product} from '../lib/catalog';
export default function DatabaseProductDetail({product}:{product:Product}){
 const primary=image(product); const variant=product.variants?.[0]; const price=variant?.sellingPrice??0;
 const specs=useMemo(()=>{const a=Array.isArray(product.attributes)?product.attributes:[];if(a.length)return a.map(x=>({key:x.key,value:x.value,unit:typeof x==='object'&&x!==null&&'unit' in x&&typeof x.unit==='string'?x.unit:undefined}));const s=product.specifications;return s&&typeof s==='object'&&!Array.isArray(s)?Object.entries(s as Record<string,unknown>).filter(([k])=>!k.startsWith('_')).map(([key,value])=>({key,value:String(value)})):[]},[product]);
 return <><section className="section product-detail"><div className="detail-media"><div className="detail-image">{primary?<img src={primary} alt={product.images?.find(x=>x.primary)?.altText||product.name} />:<div className="detail-placeholder"><span>AMAAL</span><strong>Product image</strong><small>Product image</small></div>}</div></div><div className="detail-copy"><p className="eyebrow">{product.brand_name||'AMAAL'}{product.category_name?` · ${product.category_name}`:''}</p><div className="detail-title-row"><h1>{product.name}</h1><WishlistButton id={product.slug}/></div><div className="detail-price">{price>0?new Intl.NumberFormat('en-UG',{style:'currency',currency:'UGX',maximumFractionDigits:0}).format(Number(price)):'Price coming soon'}</div><p className="detail-note">{product.description||product.short_description||'Product details will be confirmed by Amaal before publication.'}</p><div className="quick-specs">{specs.slice(0,8).map(x=><span key={x.key}>{x.key}: {x.value}{x.unit?` ${x.unit}`:''}</span>)}</div>{price>0&&variant&&<AddToBag id={product.id} variantId={variant.code} name={product.name} brand={product.brand_name} slug={product.slug} price="" numericPrice={Number(price)}/>}<Link className="button" href={`/contact?product=${encodeURIComponent(product.name)}`}>Ask about this product</Link><div className="detail-trust"><span>Genuine product information</span><span>Warranty support</span><span>Reliable delivery information</span></div></div></section></>
}
