'use client';
import Link from 'next/link';
import { Menu, Search, ShoppingBag, UserRound, X } from 'lucide-react';
import Image from 'next/image';
import { useEffect, useState } from 'react';import {getCart,syncServerCart,serverCartToLegacy} from '../lib/commerce';import {buildCategoryNavigation, type CategoryNavNode} from '../lib/category-navigation';import SearchAssist from './SearchAssist';import CartDrawer from './CartDrawer';
export default function SiteHeader(){
 const [open,setOpen]=useState(false); const [bagOpen,setBagOpen]=useState(false); const [catOpen,setCatOpen]=useState(false); const [bagCount,setBagCount]=useState(0); const [categoryNav,setCategoryNav]=useState<CategoryNavNode[]>([]); useEffect(()=>{const sync=()=>setBagCount(getCart().reduce((n,x)=>n+x.qty,0));sync();syncServerCart().then(data=>{const next=serverCartToLegacy(data);localStorage.setItem('amaal_cart_v3',JSON.stringify(next));setBagCount(next.reduce((n,x)=>n+x.qty,0))}).catch(()=>{});window.addEventListener('amaal-commerce-updated',sync);return()=>window.removeEventListener('amaal-commerce-updated',sync)},[]); useEffect(()=>{const base=process.env.NEXT_PUBLIC_API_BASE_URL||process.env.AMAAL_API_BASE_URL||'';fetch(`${base}/api/public/catalog`,{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>setCategoryNav(buildCategoryNavigation(d?.categories||[]))).catch(()=>{});},[]);
 return <>
  <div className="topline">Genuine products <span>·</span> Trusted brands <span>·</span> Delivery across Uganda</div>
  <header className="site-header"><Link className="brand" href="/" aria-label="Amaal home"><Image src="/assets/amaal/logo-official.png" alt="Amaal" width={172} height={27} priority /></Link>
   <nav className="desktop-nav" aria-label="Primary"><Link href="/shop">Shop</Link><Link href="/categories">Categories</Link><Link href="/brands">Brands</Link><Link href="/collections">Collections</Link><Link href="/deals">Deals</Link><Link href="/bundles">Bundles</Link><Link href="/services">Services</Link><Link href="/guides">Guides</Link></nav>
   <div className="nav-actions"><Link href="/search" aria-label="Search"><Search size={19}/></Link><Link href="/account" aria-label="Account"><UserRound size={19}/></Link><button className="bag-trigger" onClick={()=>setBagOpen(true)} aria-label="Open shopping bag"><ShoppingBag size={19}/><span className="bag-count">{bagCount}</span></button><button className="mobile-menu" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu size={21}/></button></div>
  </header><div className="header-search-assist"><SearchAssist/></div>
  <CartDrawer open={bagOpen} onClose={()=>setBagOpen(false)}/>{open&&<div className="mobile-drawer"><div className="drawer-head"><Link className="brand" href="/" onClick={()=>setOpen(false)} aria-label="Amaal home"><Image src="/assets/amaal/logo-official.png" alt="Amaal" width={172} height={27} /></Link><button onClick={()=>setOpen(false)} aria-label="Close menu"><X/></button></div><nav><Link onClick={()=>setOpen(false)} href="/shop">Shop</Link><div className="mobile-category-menu"><button type="button" onClick={()=>setCatOpen(!catOpen)}>Categories <span>{catOpen?"−":"+"}</span></button>{catOpen&&<div className="mobile-category-list">{categoryNav.map(c=><div key={c.slug}><Link onClick={()=>setOpen(false)} href={c.href}>{c.name}</Link>{c.children?.map(ch=><Link className="nested" onClick={()=>setOpen(false)} href={ch.href} key={ch.slug}>{ch.name}</Link>)}</div>)}</div>}</div><Link onClick={()=>setOpen(false)} href="/brands">Brands</Link><Link onClick={()=>setOpen(false)} href="/collections">Collections</Link><Link onClick={()=>setOpen(false)} href="/deals">Deals</Link><Link onClick={()=>setOpen(false)} href="/bundles">Bundles</Link><Link onClick={()=>setOpen(false)} href="/services">Services</Link><Link onClick={()=>setOpen(false)} href="/guides">Guides</Link><Link onClick={()=>setOpen(false)} href="/search">Search</Link><Link onClick={()=>setOpen(false)} href="/account">Account</Link></nav></div>}
 </>
}
