'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';

type Item={slug:string;brand:string;name:string;shortDescription:string;quickSpecs:string[];category?:string;family?:string};
export default function UnifiedCatalogueClient({items,basePath,searchPlaceholder='Search products…',filterLabel='All'}:{items:Item[];basePath:string;searchPlaceholder?:string;filterLabel?:string}){
 const [q,setQ]=useState(''); const [brand,setBrand]=useState('All'); const [sort,setSort]=useState('Featured');
 const brands=useMemo(()=>Array.from(new Set(items.map(x=>x.brand))).sort(),[items]);
 const filtered=useMemo(()=>{let a=items.filter(p=>(brand==='All'||p.brand===brand)&&(!q||`${p.name} ${p.brand} ${p.family||''} ${p.category||''} ${p.shortDescription}`.toLowerCase().includes(q.toLowerCase())));if(sort==='A–Z')a=[...a].sort((x,y)=>x.name.localeCompare(y.name));if(sort==='Brand')a=[...a].sort((x,y)=>x.brand.localeCompare(y.brand)||x.name.localeCompare(y.name));return a},[items,brand,q,sort]);
 const clear=()=>{setQ('');setBrand('All');setSort('Featured')};
 return <div className="catalogue-shell"><div className="catalogue-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={searchPlaceholder} aria-label="Search products"/><select value={brand} onChange={e=>setBrand(e.target.value)}><option value="All">All brands</option>{brands.map(b=><option key={b}>{b}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option>Featured</option><option>A–Z</option><option>Brand</option></select></div><div className="results-line"><span>{filtered.length} {filterLabel}</span>{(q||brand!=='All'||sort!=='Featured')&&<button onClick={clear}>Clear</button>}</div>{filtered.length?<div className="product-grid computerGrid">{filtered.map(p=><Link href={`${basePath}/${p.slug}`} className="computerCard" key={p.slug}><div className="computerCardMedia"><span>{p.brand}</span><strong>{p.family||p.category||'Product'}</strong><small>Product photo coming soon</small></div><div className="computerCardBody"><small>{p.category||'AMAAL'}</small><h3>{p.name}</h3><p>{p.shortDescription}</p><div>{p.quickSpecs.slice(0,4).map(s=><span key={s}>{s}</span>)}</div><strong className="comingSoon">Price coming soon</strong></div></Link>)}</div>:<div className="catalogue-empty"><h3>No products match those choices.</h3><p>Try another brand or search term.</p></div>}</div>
}
