'use client';
import {useEffect,useMemo,useState} from 'react';
import ProductCard from './ProductCard';
import type {Product} from '../lib/catalog';
import {Filter,Search,X} from 'lucide-react';
export default function UniversalShopClient({items}:{items:Product[]}){
 const [q,setQ]=useState(''),[brand,setBrand]=useState('All'),[category,setCategory]=useState('All'),[min,setMin]=useState(''),[max,setMax]=useState(''),[sort,setSort]=useState('Featured'),[page,setPage]=useState(1),[filters,setFilters]=useState(false); const per=24;
 useEffect(()=>{const p=new URLSearchParams(location.search);setQ(p.get('q')||'');setBrand(p.get('brand')||'All');setCategory(p.get('category')||'All');setMin(p.get('min')||'');setMax(p.get('max')||'')},[]);
 useEffect(()=>{const p=new URLSearchParams();if(q)p.set('q',q);if(brand!=='All')p.set('brand',brand);if(category!=='All')p.set('category',category);if(min)p.set('min',min);if(max)p.set('max',max);history.replaceState(null,'',p.toString()?`/shop?${p}`:'/shop');setPage(1)},[q,brand,category,min,max]);
 const brands=useMemo(()=>['All',...Array.from(new Set(items.map(x=>x.brand_name).filter(Boolean) as string[])).sort(),],[items]); const cats=useMemo(()=>['All',...Array.from(new Set(items.map(x=>x.category_name).filter(Boolean) as string[])).sort(),],[items]);
 const filtered=useMemo(()=>{let r=items.filter(x=>{const price=Number(x.variants?.[0]?.sellingPrice||0);const hay=`${x.name} ${x.brand_name||''} ${x.category_name||''} ${x.short_description||''} ${x.attributes?.map(a=>`${a.key} ${a.value}`).join(' ')||''}`.toLowerCase();return (brand==='All'||x.brand_name===brand)&&(category==='All'||x.category_name===category)&&(!q||hay.includes(q.toLowerCase()))&&(!min||price>=Number(min))&&(!max||price<=Number(max));});if(sort==='A–Z')r.sort((a,b)=>a.name.localeCompare(b.name));if(sort==='Price low')r.sort((a,b)=>Number(a.variants?.[0]?.sellingPrice||0)-Number(b.variants?.[0]?.sellingPrice||0));if(sort==='Price high')r.sort((a,b)=>Number(b.variants?.[0]?.sellingPrice||0)-Number(a.variants?.[0]?.sellingPrice||0));return r},[items,q,brand,category,min,max,sort]);
 const clear=()=>{setQ('');setBrand('All');setCategory('All');setMin('');setMax('')}; const visible=filtered.slice(0,page*per); const controls=<div className="shop-filter-controls"><label>Brand<select value={brand} onChange={e=>setBrand(e.target.value)}>{brands.map(x=><option key={x}>{x}</option>)}</select></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{cats.map(x=><option key={x}>{x}</option>)}</select></label><label>Min price<input inputMode="numeric" value={min} onChange={e=>setMin(e.target.value.replace(/\D/g,''))} placeholder="UGX"/></label><label>Max price<input inputMode="numeric" value={max} onChange={e=>setMax(e.target.value.replace(/\D/g,''))} placeholder="UGX"/></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option>Featured</option><option>A–Z</option><option>Price low</option><option>Price high</option></select></label></div>;
 return <div className="universal-shop"><div className="shop-toolbar"><div className="shop-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search phones, TVs, appliances, computers…" aria-label="Search the Amaal catalogue"/></div><button className="mobile-filter-button" onClick={()=>setFilters(true)}><Filter size={16}/> Filters</button><div className="shop-selects">{controls}</div></div>{filters&&<div className="mobile-filter-sheet"><div className="mobile-filter-head"><h2>Filter catalogue</h2><button onClick={()=>setFilters(false)} aria-label="Close filters"><X/></button></div>{controls}<button className="button gold" onClick={()=>setFilters(false)}>Apply filters</button></div>}<div className="shop-result-row"><span><b>{filtered.length.toLocaleString()}</b> published products</span>{(q||brand!=='All'||category!=='All'||min||max)&&<button onClick={clear}><X size={14}/> Clear filters</button>}</div>{!visible.length?<div className="empty"><Search/><h2>No products match those filters.</h2><p>Try a broader search or clear the filters.</p><button className="button outline" onClick={clear}>Clear filters</button></div>:<div className="product-grid">{visible.map(p=><ProductCard key={p.id} product={p}/>)}</div>}{visible.length<filtered.length&&<div className="load-more"><button className="button outline" onClick={()=>setPage(x=>x+1)}>Load more products</button><small>Showing {visible.length} of {filtered.length}</small></div>}</div>
}
