import Link from 'next/link';
import SiteHeader from '../../../components/SiteHeader';
import SiteFooter from '../../../components/SiteFooter';
import AddToBag from '../../../components/AddToBag';
import PhoneVariantSelector from '../../../components/PhoneVariantSelector';
import { getCatalog, image, price } from '../../../lib/catalog';
import { featuredProducts, newProducts, type HomeProduct } from '../../../lib/homepage-data';
import { phoneCatalogue } from '../../../lib/phone-catalogue';

const curated = [...featuredProducts, ...newProducts];
function ugx(value:number){return value ? new Intl.NumberFormat('en-UG',{style:'currency',currency:'UGX',maximumFractionDigits:0}).format(value) : 'Price on request'}
function CuratedDetail({p}:{p:HomeProduct}){const photos=p.images??[];const hero=photos[0];return <main><SiteHeader/><section className="section product-detail"><div className="detail-media"><div className="detail-image">{hero?<img src={hero} alt={p.name}/>:<div className="detail-placeholder"><span>AMAAL</span><strong>PRODUCT PHOTO</strong><small>Asset to be supplied</small></div>}</div>{photos.length>1&&<div className="detail-thumbs">{photos.map((src,i)=><div className="detail-thumb" key={src}><img src={src} alt={`${p.name} view ${i+1}`}/></div>)}</div>}</div><div className="detail-copy"><p className="eyebrow">{p.brand} · {p.eyebrow}</p><h1>{p.name}</h1><div className="detail-price">{ugx(p.price)}</div><p className="detail-note">{p.description}</p><div className="quick-specs">{p.quickDetails.map(x=><span key={x}>{x}</span>)}</div>{p.price>0?<AddToBag id={p.slug} name={p.name} price={ugx(p.price)}/>:<Link className="button gold" href="/contact">Enquire about this product</Link>}<div className="detail-trust"><span>Genuine product</span><span>Warranty support</span><span>Reliable delivery</span></div></div></section><section className="section product-detail-more"><p className="eyebrow">PRODUCT INFORMATION</p><h2>Everything you need to know.</h2><p>Full product information is presented separately from the quick catalogue view so customers can explore the model without clutter. Amaal can expand specifications, warranty and delivery details as official product records are published.</p></section><SiteFooter/></main>}
function PhoneDetail({p}:{p:typeof phoneCatalogue[number]}){return <main><SiteHeader/><section className="section product-detail phone-detail"><div className="detail-media"><div className="detail-image"><div className="detail-placeholder phone-photo-placeholder"><span>AMAAL</span><strong>{p.name}</strong><small>PHONE PHOTO TO BE SUPPLIED</small></div></div></div><div className="detail-copy"><p className="eyebrow">{p.brand} · {p.series}</p><h1>{p.name}</h1><p className="detail-note">{p.description}</p><PhoneVariantSelector product={p}/><div className="phone-detail-actions"><Link className="button gold" href="/contact">Enquire about this model</Link><Link className="button" href="/phones">Browse all phones</Link></div><div className="detail-trust"><span>Model-level catalogue</span><span>Clear variant selection</span><span>Official-data led</span></div></div></section><section className="section phone-spec-section"><div><p className="eyebrow">MODEL INFORMATION</p><h2>One model. Its available configurations.</h2><p>Storage, RAM and network options are represented as variants of the same phone model. Selecting another capacity does not create a duplicate product page.</p></div><div className="phone-spec-table"><div><span>Brand</span><strong>{p.brand}</strong></div><div><span>Family</span><strong>{p.family}</strong></div><div><span>Series</span><strong>{p.series}</strong></div><div><span>Network</span><strong>{p.network}</strong></div><div><span>Configurations</span><strong>{p.variants.map(v=>v.label).join(' · ')}</strong></div></div></section><section className="section product-detail-more"><p className="eyebrow">PHOTOGRAPHY & VERIFICATION</p><h2>Product imagery is coming.</h2><p>Each phone model has its own image placeholder. When Amaal supplies photography, it will be attached to the model page without reusing another model's image. Technical fields not verified in the master catalogue remain unpublished rather than being guessed.</p></section><SiteFooter/></main>}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const phone=phoneCatalogue.find(x=>x.slug===slug);if(phone)return <PhoneDetail p={phone}/>;const local=curated.find(x=>x.slug===slug);if(local)return <CuratedDetail p={local}/>;const catalog=await getCatalog();const p=(catalog?.products??[]).find(x=>(x.slug??String(x.id))===slug);if(!p)return <main><SiteHeader/><section className="section empty"><h1>Product not found.</h1><Link href="/shop">Return to shop</Link></section><SiteFooter/></main>;const formatted=price(p);return <main><SiteHeader/><section className="section product-detail"><div className="detail-image">{image(p)?<img src={image(p)} alt={p.name}/>:<div className="detail-placeholder"><span>AMAAL</span><strong>PRODUCT PHOTO</strong></div>}</div><div className="detail-copy"><p className="eyebrow">{p.brand_name??'AMAAL'}</p><h1>{p.name}</h1>{formatted&&<div className="detail-price">{formatted}</div>}<p className="detail-note">{p.description||p.short_description||'Genuine product from a trusted brand. Delivery and warranty details are confirmed through Amaal.'}</p>{formatted?<AddToBag id={String(p.id)} name={p.name} price={formatted}/>:<Link className="button gold" href="/contact">Enquire about this product</Link>}<div className="detail-trust"><span>Genuine product</span><span>Warranty support</span><span>Reliable delivery</span></div></div></section><SiteFooter/></main>}
