'use client';

import { useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { CheckCircle2, Clock3, MapPin, PackageCheck, Pencil, Plus, Truck, X } from 'lucide-react';

type Any = any;

async function api(path: string, init: RequestInit = {}) {
  const response = await fetch(`/api/engine${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...(init.headers || {}) } });
  const text = await response.text(); let payload: Any = null; try { payload = text ? JSON.parse(text) : null; } catch { payload = text; }
  if (!response.ok) throw new Error(payload?.error || 'The delivery action could not be completed.');
  return payload;
}

function money(v: Any) { const n = Number(v); return Number.isFinite(n) ? new Intl.NumberFormat('en-UG', { style: 'currency', currency: 'UGX', maximumFractionDigits: 0 }).format(n) : '—'; }
function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="adminModalBackdrop"><div className="adminModal wide"><header><div><span className="eyebrow">Delivery management</span><h3>{title}</h3></div><button className="iconButton" onClick={onClose}><X size={17}/></button></header>{children}</div></div>; }
function Field({ label, value, onChange, type='text', required=false }: Any) { return <label className="adminField"><span>{label}{required?' *':''}</span><input type={type} required={required} value={value ?? ''} onChange={e=>onChange(e.target.value)}/></label>; }
function Select({ label, value, onChange, options }: Any) { return <label className="adminField"><span>{label}</span><select value={value ?? ''} onChange={e=>onChange(e.target.value)}>{options.map((o: Any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>; }

export function DeliveryWorkspace({ summary: initialSummary, shipments: initialShipments, zones: initialZones, partners: initialPartners, orders, drivers, permissions, isSuperAdmin }: Any) {
  const [summary,setSummary]=useState(initialSummary||{}); const [shipments,setShipments]=useState(initialShipments||[]); const [zones,setZones]=useState(initialZones||[]); const [partners,setPartners]=useState(initialPartners||[]);
  const [modal,setModal]=useState<'shipment'|'zone'|'partner'|'edit'|'status'|'detail'|null>(null); const [selected,setSelected]=useState<Any>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const canManage=isSuperAdmin||permissions.includes('delivery.manage'); const canPartners=isSuperAdmin||permissions.includes('delivery.partners');
  const emptyShipment={orderId:'',method:'Delivery',zoneId:'',driverId:'',partnerId:'',unitCount:'1',unitCost:'0',carrier:'',trackingNumber:'',scheduledAt:'',recipientName:'',recipientPhone:'',address:'',notes:''};
  const [form,setForm]=useState<Any>(emptyShipment); const [statusForm,setStatusForm]=useState({status:'',recipientName:'',proofType:'Recipient',proofReference:'',proofNotes:'',failureReason:'',notes:''});
  const [zoneForm,setZoneForm]=useState({name:'',region:'',fee:'0',etaHours:'24',status:'Active'}); const [partnerForm,setPartnerForm]=useState({name:'',partnerType:'Individual',phone:'',email:'',address:'',serviceArea:'',defaultUnitCost:'0',status:'Active',notes:''});
  const set=(k:string,v:Any)=>setForm((x:Any)=>({...x,[k]:v}));
  async function refresh(){const [s,sh,z,p]=await Promise.all([api('/api/delivery/summary'),api('/api/delivery/shipments'),api('/api/delivery/zones'),api('/api/delivery/partners')]);setSummary(s);setShipments(sh||[]);setZones(z||[]);setPartners(p||[]);}
  async function submitShipment(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api(selected?`/api/delivery/shipments/${selected.id}`:'/api/delivery/shipments',{method:selected?'PATCH':'POST',body:JSON.stringify({...form,unitCount:Number(form.unitCount),unitCost:Number(form.unitCost)})});await refresh();setModal(null);setSelected(null);}catch(e:Any){setError(e.message)}finally{setBusy(false)}}
  async function submitZone(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{if(selected)await api(`/api/delivery/zones/${selected.id}`,{method:'PATCH',body:JSON.stringify(zoneForm)});else await api('/api/delivery/zones',{method:'POST',body:JSON.stringify(zoneForm)});await refresh();setModal(null);setSelected(null);}catch(e:Any){setError(e.message)}finally{setBusy(false)}}
  async function submitPartner(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{if(selected)await api(`/api/delivery/partners/${selected.id}`,{method:'PATCH',body:JSON.stringify(partnerForm)});else await api('/api/delivery/partners',{method:'POST',body:JSON.stringify(partnerForm)});await refresh();setModal(null);setSelected(null);}catch(e:Any){setError(e.message)}finally{setBusy(false)}}
  function editShipment(row:Any){setSelected(row);setForm({orderId:row.order_id||'',method:row.method||'Delivery',zoneId:row.zone_id||'',driverId:row.driver_id||'',partnerId:row.partner_id||'',unitCount:row.unit_count||0,unitCost:row.unit_cost||0,carrier:row.carrier||'',trackingNumber:row.tracking_number||'',scheduledAt:row.scheduled_at?new Date(row.scheduled_at).toISOString().slice(0,16):'',recipientName:row.recipient_name||'',recipientPhone:row.recipient_phone||'',address:row.address||'',notes:row.notes||''});setError('');setModal('edit');}
  async function updateStatus(e:FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError('');try{await api(`/api/delivery/shipments/${selected.id}/status`,{method:'POST',body:JSON.stringify(statusForm)});await refresh();setModal(null);setSelected(null);}catch(e:Any){setError(e.message)}finally{setBusy(false)}}
  async function openDetail(row:Any){setBusy(true);setError('');try{const detail=await api(`/api/delivery/shipments/${row.id}`);setSelected(detail);setModal('detail')}catch(e:Any){setError(e.message)}finally{setBusy(false)}}
  function openStatus(row:Any){const next:Record<string,string[]>={Pending:['Assigned','Cancelled'],Assigned:['Picked Up','Cancelled'],'Picked Up':['In Transit','Cancelled'],'In Transit':['Out for Delivery','Failed','Returned'],'Out for Delivery':['Delivered','Failed','Returned'],Failed:['Assigned','Cancelled']};setSelected(row);setStatusForm({status:next[row.status]?.[0]||'',recipientName:row.recipient_name||'',proofType:'Recipient',proofReference:'',proofNotes:'',failureReason:'',notes:''});setError('');setModal('status');}
  const openShipment=()=>{setSelected(null);setForm(emptyShipment);setError('');setModal('shipment')};
  return <div className="workspace">
    <section className="welcome"><div><span className="eyebrow">Operations · Delivery</span><h2>Delivery control</h2><p>Plan deliveries, assign responsibility, track exceptions and keep delivery costs visible.</p></div>{canManage&&<div className="workspaceActions"><button onClick={openShipment}><Plus size={15}/> Create shipment</button><button onClick={()=>{setSelected(null);setZoneForm({name:'',region:'',fee:'0',etaHours:'24',status:'Active'});setModal('zone')}}><Plus size={15}/> Add zone</button>{canPartners&&<button onClick={()=>{setSelected(null);setPartnerForm({name:'',partnerType:'Individual',phone:'',email:'',address:'',serviceArea:'',defaultUnitCost:'0',status:'Active',notes:''});setModal('partner')}}><Plus size={15}/> Add partner</button>}</div>}</section>
    <section className="metrics">{[['All deliveries',summary.total,PackageCheck],['Pending',summary.pending,Clock3],['In transit',summary.transit,Truck],['Delayed',summary.delayed,Clock3],['Delivered this month',summary.deliveredThisMonth,CheckCircle2],['Returned',summary.returned,MapPin]].map(([label,value,Icon]:Any)=><article className="metric" key={label}><span>{label}</span><strong>{value ?? 0}</strong><small><Icon size={14}/> Live business records</small></article>)}</section>
    <section className="panel tablePanel"><div className="panelHeading"><div><h3>Shipments</h3><p>Every shipment remains connected to its order and customer.</p></div></div><div className="tableWrap"><table><thead><tr><th>Shipment</th><th>Customer</th><th>Driver</th><th>Zone</th><th>Status</th><th>Schedule</th><th>Cost</th><th>Actions</th></tr></thead><tbody>{shipments.length?shipments.map((r:Any)=><tr key={r.id}><td><strong>{r.shipment_no}</strong><small>{r.order_no}</small></td><td>{r.customer_name||r.recipient_name||'Guest'}</td><td>{r.driver_name||'Unassigned'}</td><td>{r.zone_name||'—'}</td><td><span className="teamStatus">{r.status}</span></td><td>{r.scheduled_at?new Date(r.scheduled_at).toLocaleString():'—'}</td><td>{money(r.total_delivery_cost)}</td><td><button className="softAction" onClick={()=>openDetail(r)}>View units</button>{canManage&&!['Delivered','Cancelled','Returned'].includes(r.status)&&<><button className="softAction" onClick={()=>editShipment(r)}><Pencil size={13}/> Edit</button><button className="softAction" onClick={()=>openStatus(r)}>Status</button></>}</td></tr>):<tr><td colSpan={8}><div className="emptyState">No delivery shipments yet.</div></td></tr>}</tbody></table></div></section>
    <div className="twoColumn"><section className="panel"><div className="panelHeading"><div><h3>Delivery zones</h3><p>Coverage, fees and expected timing.</p></div></div><div className="tableWrap"><table><thead><tr><th>Zone</th><th>Fee</th><th>ETA</th><th>Status</th><th/></tr></thead><tbody>{zones.length?zones.map((z:Any)=><tr key={z.id}><td><strong>{z.name}</strong><small>{z.region||'—'}</small></td><td>{money(z.fee)}</td><td>{z.eta_hours} hrs</td><td>{z.status}</td><td>{canManage&&<button className="softAction" onClick={()=>{setSelected(z);setZoneForm({name:z.name,region:z.region||'',fee:z.fee||0,etaHours:z.eta_hours||24,status:z.status||'Active'});setModal('zone')}}><Pencil size={13}/> Edit</button>}</td></tr>):<tr><td colSpan={5}><div className="emptyState">No zones yet.</div></td></tr>}</tbody></table></div></section>
    <section className="panel"><div className="panelHeading"><div><h3>Delivery partners</h3><p>Partner activity and cost control.</p></div></div><div className="tableWrap"><table><thead><tr><th>Partner</th><th>Status</th><th>Delivered</th><th>Cost</th><th/></tr></thead><tbody>{partners.length?partners.map((p:Any)=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.partner_type}</small></td><td>{p.status}</td><td>{p.delivered_shipments||0}</td><td>{money(p.total_cost)}</td><td>{canPartners&&<button className="softAction" onClick={()=>{setSelected(p);setPartnerForm({name:p.name,partnerType:p.partner_type||'Individual',phone:p.phone||'',email:p.email||'',address:p.address||'',serviceArea:p.service_area||'',defaultUnitCost:p.default_unit_cost||0,status:p.status||'Active',notes:p.notes||''});setModal('partner')}}><Pencil size={13}/> Edit</button>}</td></tr>):<tr><td colSpan={5}><div className="emptyState">No delivery partners yet.</div></td></tr>}</tbody></table></div></section></div>

    {error&&<div className="error">{error}</div>}
    {modal==='detail'&&selected&&<Modal title={`Shipment ${selected.shipment_no}`} onClose={()=>{setModal(null);setSelected(null)}}><div className="panelHeading"><div><h4>{selected.order_no}</h4><p>{selected.customer_name||selected.recipient_name||'Guest'} · {selected.status}</p></div><span className="catalogStatus">{selected.serializedUnits?.length||0} physical unit(s)</span></div><section className="panel" style={{marginTop:14}}><div className="panelHeading"><div><h4>Exact physical units</h4><p>The same units assigned to the order are tracked through this shipment.</p></div></div><div className="tableWrap"><table><thead><tr><th>Product</th><th>IMEI / Serial</th><th>Batch</th><th>Shipment state</th><th>Unit state</th></tr></thead><tbody>{(selected.serializedUnits||[]).length?selected.serializedUnits.map((u:Any)=><tr key={u.id}><td><strong>{u.product_name}</strong><small>{u.variant_name||u.sku}</small></td><td><strong>{u.imei1||u.serial_number||u.imei2||'—'}</strong><small>{u.serial_number&&u.serial_number!==u.imei1?`Serial ${u.serial_number}`:''}</small></td><td>{u.batch_number||'—'}</td><td><span className="teamStatus">{u.status}</span></td><td>{u.unit_status}</td></tr>):<tr><td colSpan={5}><div className="emptyState">This order has no serialized physical units attached to the shipment.</div></td></tr>}</tbody></table></div></section><div className="adminRelationshipList" style={{marginTop:14}}><div><strong>Delivery reconciliation</strong><span>Shipment, order assignment and physical-unit identity remain linked. Delivery completion will only succeed when every serialized unit is still Reserved.</span></div></div></Modal>}
    {(modal==='shipment'||modal==='edit')&&<Modal title={selected?'Edit shipment':'Create shipment'} onClose={()=>setModal(null)}><form onSubmit={submitShipment}><div className="adminFormGrid"><Select label="Order" value={form.orderId} onChange={(v:string)=>set('orderId',v)} options={[{value:'',label:'Select order'},...(orders||[]).filter((o:Any)=>!selected||o.id===selected.order_id).filter((o:Any)=>['Ready for Dispatch','Dispatched'].includes(o.status)).map((o:Any)=>({value:o.id,label:`${o.order_no} · ${o.customer_name||'Guest'}`}))]}/><Select label="Method" value={form.method} onChange={(v:string)=>set('method',v)} options={['Delivery','Pickup'].map(x=>({value:x,label:x}))}/><Select label="Zone" value={form.zoneId} onChange={(v:string)=>set('zoneId',v)} options={[{value:'',label:'No zone'},...zones.filter((z:Any)=>z.status==='Active').map((z:Any)=>({value:z.id,label:z.name}))]}/><Select label="Driver" value={form.driverId} onChange={(v:string)=>set('driverId',v)} options={[{value:'',label:'Unassigned'},...(drivers||[]).map((d:Any)=>({value:d.id,label:d.name}))]}/><Select label="Delivery partner" value={form.partnerId} onChange={(v:string)=>set('partnerId',v)} options={[{value:'',label:'Direct / internal'},...partners.filter((p:Any)=>p.status==='Active').map((p:Any)=>({value:p.id,label:p.name}))]}/><Field label="Unit count" type="number" value={String(form.unitCount)} onChange={(v:string)=>set('unitCount',v)}/><Field label="Unit delivery cost" type="number" value={String(form.unitCost)} onChange={(v:string)=>set('unitCost',v)}/><Field label="Carrier" value={form.carrier} onChange={(v:string)=>set('carrier',v)}/><Field label="Tracking number" value={form.trackingNumber} onChange={(v:string)=>set('trackingNumber',v)}/><Field label="Scheduled at" type="datetime-local" value={form.scheduledAt} onChange={(v:string)=>set('scheduledAt',v)}/><Field label="Recipient name" value={form.recipientName} onChange={(v:string)=>set('recipientName',v)}/><Field label="Recipient phone" value={form.recipientPhone} onChange={(v:string)=>set('recipientPhone',v)}/></div><div className="adminSubmit"><button type="button" onClick={()=>setModal(null)}>Cancel</button><button className="primaryAction" disabled={busy}>{busy?'Saving…':'Save shipment'}</button></div></form></Modal>}
    {modal==='status'&&selected&&<Modal title={`Update delivery · ${selected.shipment_no}`} onClose={()=>setModal(null)}><form onSubmit={updateStatus}><div className="adminFormGrid"><Select label="New status" value={statusForm.status} onChange={(v:string)=>setStatusForm({...statusForm,status:v})} options={(selected.status==='Pending'?['Assigned','Cancelled']:selected.status==='Assigned'?['Picked Up','Cancelled']:selected.status==='Picked Up'?['In Transit','Cancelled']:selected.status==='In Transit'?['Out for Delivery','Failed','Returned']:selected.status==='Out for Delivery'?['Delivered','Failed','Returned']:selected.status==='Failed'?['Assigned','Cancelled']:[]).map(x=>({value:x,label:x}))}/><Field label="Recipient name" value={statusForm.recipientName} onChange={(v:string)=>setStatusForm({...statusForm,recipientName:v})}/><Select label="Delivery proof" value={statusForm.proofType} onChange={(v:string)=>setStatusForm({...statusForm,proofType:v})} options={['Recipient','Photo','Signature','None'].map(x=>({value:x,label:x}))}/><Field label="Proof reference" value={statusForm.proofReference} onChange={(v:string)=>setStatusForm({...statusForm,proofReference:v})}/><Field label="Failure reason" value={statusForm.failureReason} onChange={(v:string)=>setStatusForm({...statusForm,failureReason:v})}/></div><div className="adminSubmit"><button type="button" onClick={()=>setModal(null)}>Cancel</button><button className="primaryAction" disabled={busy||!statusForm.status}>{busy?'Saving…':'Update status'}</button></div></form></Modal>}
    {modal==='zone'&&<Modal title={selected?'Edit delivery zone':'Add delivery zone'} onClose={()=>setModal(null)}><form onSubmit={submitZone}><div className="adminFormGrid"><Field label="Zone name" required value={zoneForm.name} onChange={(v:string)=>setZoneForm({...zoneForm,name:v})}/><Field label="Region" value={zoneForm.region} onChange={(v:string)=>setZoneForm({...zoneForm,region:v})}/><Field label="Delivery fee" type="number" value={String(zoneForm.fee)} onChange={(v:string)=>setZoneForm({...zoneForm,fee:v})}/><Field label="Expected time (hours)" type="number" value={String(zoneForm.etaHours)} onChange={(v:string)=>setZoneForm({...zoneForm,etaHours:v})}/><Select label="Status" value={zoneForm.status} onChange={(v:string)=>setZoneForm({...zoneForm,status:v})} options={['Active','Inactive'].map(x=>({value:x,label:x}))}/></div><div className="adminSubmit"><button type="button" onClick={()=>setModal(null)}>Cancel</button><button className="primaryAction" disabled={busy}>{busy?'Saving…':'Save zone'}</button></div></form></Modal>}
    {modal==='partner'&&<Modal title={selected?'Edit delivery partner':'Add delivery partner'} onClose={()=>setModal(null)}><form onSubmit={submitPartner}><div className="adminFormGrid"><Field label="Partner name" required value={partnerForm.name} onChange={(v:string)=>setPartnerForm({...partnerForm,name:v})}/><Select label="Type" value={partnerForm.partnerType} onChange={(v:string)=>setPartnerForm({...partnerForm,partnerType:v})} options={['Individual','Company','Courier'].map(x=>({value:x,label:x}))}/><Field label="Phone" value={partnerForm.phone} onChange={(v:string)=>setPartnerForm({...partnerForm,phone:v})}/><Field label="Email" type="email" value={partnerForm.email} onChange={(v:string)=>setPartnerForm({...partnerForm,email:v})}/><Field label="Service area" value={partnerForm.serviceArea} onChange={(v:string)=>setPartnerForm({...partnerForm,serviceArea:v})}/><Field label="Default cost per unit" type="number" value={String(partnerForm.defaultUnitCost)} onChange={(v:string)=>setPartnerForm({...partnerForm,defaultUnitCost:v})}/></div><div className="adminSubmit"><button type="button" onClick={()=>setModal(null)}>Cancel</button><button className="primaryAction" disabled={busy}>{busy?'Saving…':'Save partner'}</button></div></form></Modal>}
  </div>;
}
