'use client';
import { useMemo, useState } from 'react';
import { BarChart3, Building2, ClipboardList, FileText, PackageCheck, Plus, RefreshCw, Search, Truck, Wallet, X } from 'lucide-react';

type Any = any;
async function api(path:string, init:RequestInit={}){const r=await fetch(path,{...init,headers:{'Content-Type':'application/json',...(init.headers||{})}});const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.error||'The action could not be completed.');return d}
const money=(v:any)=>Number.isFinite(Number(v))?new Intl.NumberFormat('en-UG',{style:'currency',currency:'UGX',maximumFractionDigits:0}).format(Number(v)):'—';
const num=(v:any)=>Number.isFinite(Number(v))?new Intl.NumberFormat('en-UG',{maximumFractionDigits:0}).format(Number(v)):'—';
function Modal({title,children,onClose,wide=false}:{title:string;children:any;onClose:()=>void;wide?:boolean}){return <div className="adminModalBackdrop"><div className={`adminModal ${wide?'wide':''}`}><header><div><span className="eyebrow">Purchasing</span><h3>{title}</h3></div><button className="iconButton" onClick={onClose}><X size={17}/></button></header>{children}</div></div>}
function Field({label,value,onChange,type='text',placeholder=''}:any){return <label className="adminField"><span>{label}</span><input type={type} value={value??''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Select({label,value,onChange,options}:any){return <label className="adminField"><span>{label}</span><select value={value??''} onChange={e=>onChange(e.target.value)}>{options.map((o:any)=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select></label>}
function Status({children}:any){return <span className="catalogStatus">{children||'—'}</span>}
function Table({rows,columns}:{rows:Any[];columns:[string,string][]}){return <div className="tableWrap"><table><thead><tr>{columns.map(([k,l])=><th key={k}>{l}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map(([k])=><td key={k}>{k==='status'?<Status>{r[k]}</Status>:k.includes('amount')||k.includes('total')||k.includes('value')||k.includes('balance')||k.includes('price')?money(r[k]):r[k]??'—'}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={columns.length}><div className="emptyState">No records to show.</div></td></tr>}</tbody></table></div>}

export function PurchasingWorkspace({summary,suppliers,requisitions,orders,receipts,invoices,payments,analytics,readiness,variants,departments,permissions}:{summary:Any;suppliers:Any[];requisitions:Any[];orders:Any[];receipts:Any[];invoices:Any[];payments:Any[];analytics:Any;readiness:Any;variants:Any[];departments:Any[];permissions:string[]}){
 const [tab,setTab]=useState('overview');const [modal,setModal]=useState<string|null>(null);const [query,setQuery]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [refresh,setRefresh]=useState(0);
 const canManage=permissions.includes('procurement.manage'), canReq=permissions.includes('procurement.requisition'), canApprove=permissions.includes('procurement.approve'), canInvoice=permissions.includes('procurement.invoice'), canPay=permissions.includes('procurement.payments'), canReceive=permissions.includes('procurement.receive');
 const filteredSuppliers=useMemo(()=>suppliers.filter(s=>!query||`${s.legal_name} ${s.trading_name||''} ${s.supplier_code||''}`.toLowerCase().includes(query.toLowerCase())),[suppliers,query]);
 const refreshPage=()=>{setRefresh(x=>x+1);setModal(null)};
 return <div className="workspace purchasingWorkspace" key={refresh}>
  <section className="welcome"><div><span className="eyebrow">Commerce · Purchasing</span><h2>Purchasing Control Centre</h2><p>Plan what the business needs, manage suppliers, place purchases, receive goods and keep supplier money visible — all from one business workspace.</p></div><button className="softAction" onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={14}/> Refresh</button></section>
  <section className="stockHeroGrid">
   <article className="stockHeroCard"><div className="stockHeroIcon"><Wallet size={20}/></div><div><span>Purchase spend</span><strong>{money(summary?.invoicedValue)}</strong><small>Invoices in the selected period</small></div></article>
   <article className="stockHeroCard"><div className="stockHeroIcon"><ClipboardList size={20}/></div><div><span>Open purchase orders</span><strong>{num(summary?.openPurchaseOrders)}</strong><small>Orders still moving through fulfilment</small></div></article>
   <article className="stockHeroCard alert"><div className="stockHeroIcon"><PackageCheck size={20}/></div><div><span>Awaiting receipt</span><strong>{num(readiness?.partiallyReceivedOrders)}</strong><small>Orders with outstanding goods</small></div></article>
   <article className="stockHeroCard"><div className="stockHeroIcon"><Building2 size={20}/></div><div><span>Paid to suppliers</span><strong>{money(summary?.paid30d)}</strong><small>Payments recorded in the selected period</small></div></article>
  </section>
  <section className="stockCommandBar"><div className="stockTabs">{[['overview','Overview'],['requests','Purchase requests'],['orders','Purchase orders'],['receiving','Receiving'],['invoices','Supplier invoices'],['suppliers','Suppliers'],['payments','Payments']].map(([id,l])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{l}</button>)}</div><div className="stockActions">{canReq&&<button onClick={()=>setModal('request')}><Plus size={14}/> Request purchase</button>}{canManage&&<button onClick={()=>setModal('order')}><Plus size={14}/> Purchase order</button>}{canInvoice&&<button onClick={()=>setModal('invoice')}><FileText size={14}/> Record invoice</button>}{canPay&&<button className="primaryAction" onClick={()=>setModal('payment')}><Wallet size={14}/> Record payment</button>}</div></section>
  {tab==='overview'&&<>
   <section className="stockOverviewGrid"><div className="panel"><div className="panelHeading"><div><h3>What needs attention</h3><p>Purchasing work that may need a decision.</p></div></div><div className="attentionList">
    <div><ClipboardList size={15}/><div><strong>{num(summary?.pendingRequisitions)} purchase requests</strong><span>Waiting for purchasing action or approval</span></div><b>{num(summary?.pendingRequisitions)}</b></div>
    <div><Truck size={15}/><div><strong>{num(readiness?.partiallyReceivedOrders)} orders partly received</strong><span>Follow up on outstanding goods</span></div><b>{num(readiness?.partiallyReceivedOrders)}</b></div>
    <div><FileText size={15}/><div><strong>{num(readiness?.openInvoiceExceptions)} invoice issues</strong><span>Review before payment</span></div><b>{num(readiness?.openInvoiceExceptions)}</b></div>
    <div><Wallet size={15}/><div><strong>{num(summary?.overdueInvoices)} overdue invoices</strong><span>Supplier payments need attention</span></div><b>{num(summary?.overdueInvoices)}</b></div>
   </div></div><div className="panel"><div className="panelHeading"><div><h3>Supplier performance</h3><p>Highest purchase activity from the existing records.</p></div></div><div className="adminRelationshipList">{(analytics?.supplierSpend||[]).slice(0,6).map((s:any)=><div key={s.id}><span>{num(s.purchase_orders)} orders</span><strong>{s.legal_name}</strong><b>{money(s.merchandise_value)}</b></div>)}{!(analytics?.supplierSpend||[]).length&&<div className="emptyState">Supplier purchasing history will appear here.</div>}</div></div></section>
   <section className="panel"><div className="panelHeading"><div><h3>Recent purchasing activity</h3><p>Requests, orders, receipts and supplier invoices in one view.</p></div></div><Table rows={[...orders.slice(0,6).map(x=>({...x,activity_type:'Purchase order'})),...receipts.slice(0,4).map(x=>({...x,activity_type:'Goods received'}))].sort((a,b)=>new Date(b.created_at||0).getTime()-new Date(a.created_at||0).getTime()).slice(0,10)} columns={[[ 'activity_type','Activity'],['po_no','Purchase order'],['supplier_name','Supplier'],['status','Status'],['created_at','Date']]} /></section>
  </>}
  {tab==='requests'&&<section className="panel"><div className="panelHeading"><div><h3>Purchase requests</h3><p>Requests for products or supplies before an order is placed.</p></div></div><Table rows={requisitions} columns={[[ 'requisition_no','Request'],['requester_name','Requested by'],['department_name','Department'],['priority','Priority'],['status','Status'],['units','Units']]} /></section>}
  {tab==='orders'&&<section className="panel"><div className="panelHeading"><div><h3>Purchase orders</h3><p>Create, submit, approve, revise, cancel, close and track outstanding purchases.</p></div></div><Table rows={orders} columns={[[ 'po_no','Order'],['supplier_name','Supplier'],['status','Status'],['currency','Currency'],['subtotal','Subtotal'],['received_units','Received']]} /></section>}
  {tab==='receiving'&&<section className="panel"><div className="panelHeading"><div><h3>Goods receiving</h3><p>Expected and completed supplier deliveries, including partial deliveries.</p></div>{canReceive&&<button className="primaryAction" onClick={()=>setTab('orders')}><Truck size={14}/> Receive from order</button>}</div><Table rows={receipts} columns={[[ 'grn_no','Receipt'],['po_no','Purchase order'],['supplier_name','Supplier'],['location_name','Warehouse'],['status','Status'],['received_units','Units']]} /></section>}
  {tab==='invoices'&&<section className="panel"><div className="panelHeading"><div><h3>Supplier invoices</h3><p>Match purchases, identify differences and follow payment status.</p></div></div><Table rows={invoices} columns={[[ 'invoice_no','Invoice'],['supplier_name','Supplier'],['po_no','Purchase order'],['status','Status'],['total_amount','Total'],['paid_amount','Paid'],['due_date','Due']]} /></section>}
  {tab==='suppliers'&&<section className="panel"><div className="stockFilterBar"><div className="stockSearch"><Search size={15}/><input placeholder="Search supplier, trading name or code" value={query} onChange={e=>setQuery(e.target.value)}/></div><button onClick={()=>setQuery('')}>Clear</button></div><div className="panelHeading"><div><h3>Supplier directory</h3><p>Supplier records, purchasing history, pricing and performance.</p></div>{canManage&&<button className="primaryAction" onClick={()=>setModal('supplier')}><Plus size={14}/> Add supplier</button>}</div><Table rows={filteredSuppliers} columns={[[ 'supplier_code','Code'],['legal_name','Supplier'],['status','Status'],['qualification_status','Qualification'],['product_count','Products'],['purchase_order_count','Orders'],['invoice_value','Purchase value']]} /></section>}
  {tab==='payments'&&<section className="panel"><div className="panelHeading"><div><h3>Supplier payments</h3><p>Record payments, allocate them to invoices and review payment history.</p></div></div><Table rows={payments} columns={[[ 'payment_no','Payment'],['supplier_name','Supplier'],['invoice_no','Invoice'],['amount','Amount'],['method','Method'],['status','Status'],['payment_date','Date']]} /></section>}
  {modal==='request'&&<RequestModal variants={variants} suppliers={suppliers} departments={departments} onClose={()=>setModal(null)} onDone={refreshPage}/>} 
  {modal==='order'&&<OrderModal variants={variants} suppliers={suppliers} onClose={()=>setModal(null)} onDone={refreshPage}/>} 
  {modal==='invoice'&&<InvoiceModal variants={variants} suppliers={suppliers} orders={orders} onClose={()=>setModal(null)} onDone={refreshPage}/>} 
  {modal==='payment'&&<PaymentModal suppliers={suppliers} invoices={invoices} onClose={()=>setModal(null)} onDone={refreshPage}/>} 
  {modal==='supplier'&&<SupplierModal onClose={()=>setModal(null)} onDone={refreshPage}/>} 
  {error&&<div className="adminError">{error}</div>}
 </div>
}
function LineEditor({variants,lines,setLines,prices=false}:any){return <div className="panel" style={{padding:12,marginTop:8}}><div className="panelHeading"><div><h4>Items</h4><p>Add every product being requested or purchased.</p></div><button type="button" className="softAction" onClick={()=>setLines([...lines,{variantId:variants[0]?.id||'',quantity:1,unitPrice:0,estimatedUnitCost:0}])}><Plus size={13}/> Add line</button></div>{lines.map((l:any,i:number)=><div className="adminFormGrid" key={i}><Select label="Product" value={l.variantId} onChange={(v:any)=>{const x=[...lines];x[i]={...x[i],variantId:v};setLines(x)}} options={variants.map((v:any)=>({value:v.id,label:`${v.sku} — ${v.product_name}${v.variant_name?` · ${v.variant_name}`:''}`}))}/><Field label="Quantity" type="number" value={l.quantity} onChange={(v:any)=>{const x=[...lines];x[i]={...x[i],quantity:v};setLines(x)}}/>{prices&&<Field label="Unit price" type="number" value={l.unitPrice} onChange={(v:any)=>{const x=[...lines];x[i]={...x[i],unitPrice:v};setLines(x)}}/>}<button type="button" className="softAction" onClick={()=>setLines(lines.filter((_:any,j:number)=>j!==i))}>Remove</button></div>)}</div>}
function RequestModal({variants,suppliers,departments,onClose,onDone}:any){const [f,setF]=useState<any>({departmentId:departments[0]?.id||'',priority:'Normal',neededBy:'',justification:'',notes:''});const [lines,setLines]=useState<any[]>([{variantId:variants[0]?.id||'',quantity:1,estimatedUnitCost:0,preferredSupplierId:suppliers[0]?.id||''}]);return <Modal title="Create purchase request" onClose={onClose} wide><form onSubmit={async e=>{e.preventDefault();try{await api('/api/procurement/requisitions',{method:'POST',body:JSON.stringify({...f,lines:lines.map(x=>({...x,quantity:Number(x.quantity),estimatedUnitCost:Number(x.estimatedUnitCost||0)}))})});onDone()}catch(err:any){alert(err.message)}}}><div className="adminFormGrid"><Select label="Department" value={f.departmentId} onChange={(v:any)=>setF({...f,departmentId:v})} options={departments.map((x:any)=>({value:x.id,label:x.name}))}/><Select label="Priority" value={f.priority} onChange={(v:any)=>setF({...f,priority:v})} options={['Low','Normal','High','Urgent']}/><Field label="Needed by" type="date" value={f.neededBy} onChange={(v:any)=>setF({...f,neededBy:v})}/><Field label="Justification" value={f.justification} onChange={(v:any)=>setF({...f,justification:v})}/></div><LineEditor variants={variants} lines={lines} setLines={setLines}/><div className="adminSubmit"><button className="primaryAction">Create request</button></div></form></Modal>}
function OrderModal({variants,suppliers,onClose,onDone}:any){const [f,setF]=useState<any>({supplierId:suppliers[0]?.id||'',currency:'UGX',expectedDate:'',notes:''});const [lines,setLines]=useState<any[]>([{variantId:variants[0]?.id||'',quantity:1,unitPrice:0}]);return <Modal title="Create purchase order" onClose={onClose} wide><form onSubmit={async e=>{e.preventDefault();try{await api('/api/procurement/orders',{method:'POST',body:JSON.stringify({...f,expectedDate:f.expectedDate||null,lines:lines.map(x=>({...x,quantity:Number(x.quantity),unitPrice:Number(x.unitPrice||0)}))})});onDone()}catch(err:any){alert(err.message)}}}><div className="adminFormGrid"><Select label="Supplier" value={f.supplierId} onChange={(v:any)=>setF({...f,supplierId:v})} options={suppliers.filter((s:any)=>s.status==='Active'&&s.qualification_status==='Approved').map((x:any)=>({value:x.id,label:x.legal_name}))}/><Field label="Expected delivery" type="date" value={f.expectedDate} onChange={(v:any)=>setF({...f,expectedDate:v})}/><Field label="Currency" value={f.currency} onChange={(v:any)=>setF({...f,currency:v})}/></div><LineEditor variants={variants} lines={lines} setLines={setLines} prices/><div className="adminSubmit"><button className="primaryAction">Create purchase order</button></div></form></Modal>}
function InvoiceModal({variants,suppliers,orders,onClose,onDone}:any){const [f,setF]=useState<any>({supplierId:suppliers[0]?.id||'',purchaseOrderId:'',invoiceNo:'',invoiceDate:new Date().toISOString().slice(0,10),dueDate:'',currency:'UGX',taxAmount:0,discountAmount:0});const [lines,setLines]=useState<any[]>([{variantId:variants[0]?.id||'',quantity:1,unitPrice:0}]);return <Modal title="Record supplier invoice" onClose={onClose} wide><form onSubmit={async e=>{e.preventDefault();try{await api('/api/procurement/invoices',{method:'POST',body:JSON.stringify({...f,purchaseOrderId:f.purchaseOrderId||null,taxAmount:Number(f.taxAmount||0),discountAmount:Number(f.discountAmount||0),lines:lines.map(x=>({...x,quantity:Number(x.quantity),unitPrice:Number(x.unitPrice||0)}))})});onDone()}catch(err:any){alert(err.message)}}}><div className="adminFormGrid"><Select label="Supplier" value={f.supplierId} onChange={(v:any)=>setF({...f,supplierId:v})} options={suppliers.map((x:any)=>({value:x.id,label:x.legal_name}))}/><Select label="Purchase order" value={f.purchaseOrderId} onChange={(v:any)=>setF({...f,purchaseOrderId:v})} options={[{value:'',label:'Not linked'},...orders.filter((o:any)=>o.supplier_id===f.supplierId).map((x:any)=>({value:x.id,label:x.po_no}))]}/><Field label="Invoice number" value={f.invoiceNo} onChange={(v:any)=>setF({...f,invoiceNo:v})}/><Field label="Invoice date" type="date" value={f.invoiceDate} onChange={(v:any)=>setF({...f,invoiceDate:v})}/><Field label="Due date" type="date" value={f.dueDate} onChange={(v:any)=>setF({...f,dueDate:v})}/><Field label="Tax" type="number" value={f.taxAmount} onChange={(v:any)=>setF({...f,taxAmount:v})}/><Field label="Discount" type="number" value={f.discountAmount} onChange={(v:any)=>setF({...f,discountAmount:v})}/></div><LineEditor variants={variants} lines={lines} setLines={setLines} prices/><div className="adminSubmit"><button className="primaryAction">Save supplier invoice</button></div></form></Modal>}
function PaymentModal({suppliers,invoices,onClose,onDone}:any){const [f,setF]=useState<any>({supplierId:suppliers[0]?.id||'',invoiceId:'',amount:'',paymentDate:new Date().toISOString().slice(0,10),method:'Bank Transfer',reference:'',notes:''});return <Modal title="Record supplier payment" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{await api('/api/procurement/payments',{method:'POST',body:JSON.stringify({...f,invoiceId:f.invoiceId||null,amount:Number(f.amount)})});onDone()}catch(err:any){alert(err.message)}}}><Select label="Supplier" value={f.supplierId} onChange={(v:any)=>setF({...f,supplierId:v,invoiceId:''})} options={suppliers.map((x:any)=>({value:x.id,label:x.legal_name}))}/><Select label="Invoice" value={f.invoiceId} onChange={(v:any)=>setF({...f,invoiceId:v})} options={[{value:'',label:'Unallocated payment'},...invoices.filter((x:any)=>x.supplier_id===f.supplierId&&['Matched','Partially Paid'].includes(x.status)).map((x:any)=>({value:x.id,label:`${x.invoice_no} · ${money(Number(x.total_amount)-Number(x.paid_amount||0))} due`}))]}/><Field label="Amount" type="number" value={f.amount} onChange={(v:any)=>setF({...f,amount:v})}/><Field label="Payment date" type="date" value={f.paymentDate} onChange={(v:any)=>setF({...f,paymentDate:v})}/><Select label="Method" value={f.method} onChange={(v:any)=>setF({...f,method:v})} options={['Bank Transfer','Cash','Mobile Money','Cheque','Other']}/><Field label="Reference" value={f.reference} onChange={(v:any)=>setF({...f,reference:v})}/><div className="adminSubmit"><button className="primaryAction">Record payment</button></div></form></Modal>}
function SupplierModal({onClose,onDone}:any){const [f,setF]=useState<any>({legalName:'',tradingName:'',supplierCode:'',email:'',phone:'',website:'',country:'Uganda',defaultCurrency:'UGX',paymentTermsDays:30,notes:''});return <Modal title="Add supplier" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{await api('/api/suppliers',{method:'POST',body:JSON.stringify(f)});onDone()}catch(err:any){alert(err.message)}}}><Field label="Legal name *" value={f.legalName} onChange={(v:any)=>setF({...f,legalName:v})}/><Field label="Trading name" value={f.tradingName} onChange={(v:any)=>setF({...f,tradingName:v})}/><div className="adminFormGrid"><Field label="Supplier code" value={f.supplierCode} onChange={(v:any)=>setF({...f,supplierCode:v})}/><Field label="Phone" value={f.phone} onChange={(v:any)=>setF({...f,phone:v})}/><Field label="Email" value={f.email} onChange={(v:any)=>setF({...f,email:v})}/><Field label="Website" value={f.website} onChange={(v:any)=>setF({...f,website:v})}/><Field label="Payment terms (days)" type="number" value={f.paymentTermsDays} onChange={(v:any)=>setF({...f,paymentTermsDays:v})}/></div><div className="adminSubmit"><button className="primaryAction">Add supplier</button></div></form></Modal>}
