'use client';
import { useMemo,useState } from 'react';
import { BarChart3,Download,Save,RefreshCw,ShieldCheck,AlertTriangle } from 'lucide-react';
const money=(v:any)=>v==null||!Number.isFinite(Number(v))?'—':new Intl.NumberFormat('en-UG',{style:'currency',currency:'UGX',maximumFractionDigits:0}).format(Number(v));
export function ReportsWorkspace({summary,trend,products,customers,procurement,delivery,warranty,returns,finance,tax,website,snapshots,canManage,canExport}:{summary:any;trend:any[];products:any[];customers:any[];procurement:any[];delivery:any[];warranty:any[];returns:any[];finance:any[];tax:any;website:any;snapshots:any[];canManage:boolean;canExport:boolean}){
 const [tab,setTab]=useState('Executive'); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const data=tab==='Products'?products:tab==='Customers'?customers:tab==='Procurement'?procurement:tab==='Delivery'?delivery:tab==='Warranty'?warranty:tab==='Returns'?returns:tab==='Finance'?finance:tab==='Website'?([website||{}]):trend;
 const cols=useMemo(()=>{if(!data.length)return [];return Object.keys(data[0]).slice(0,6)},[data]);
 async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/bi/snapshots',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reportKey:tab.toLowerCase()})});const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to save');setMessage(`Saved ${p.report_key||tab} snapshot.`)}catch(e){setMessage(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}
 function exportReport(){window.location.href=`/api/bi/export?type=${tab==='Executive'?'sales':tab.toLowerCase()}`}
 const revenue=summary?.sales?.revenue??summary?.sales?.total; const gross=summary?.margin?.gross_margin??summary?.grossProfit; const partial=Boolean(summary?.dataHealth?.partial); const unavailable=Boolean(summary?.dataHealth?.complete===false && !summary?.sales && !summary?.margin);
 return <div className="phase20Workspace"><section className="phase20Hero"><div><span className="eyebrow">Business intelligence</span><h2>Reports that reconcile to operations.</h2><p>Executive, sales, inventory, customer, procurement, delivery, service, returns, credit and finance views sourced from recorded business activity.</p></div><div className="phase20Actions">{canManage&&<button className="primaryAction" onClick={save} disabled={busy}><Save size={15}/>{busy?'Saving…':'Save snapshot'}</button>}{canExport&&<button className="softAction" onClick={exportReport}><Download size={15}/>Export</button>}</div></section>
 <section className="phase20Kpis"><article><span>Revenue</span><strong>{money(revenue)}</strong><small>Completed sales</small></article><article><span>Gross profit</span><strong>{money(gross)}</strong><small>Recorded sales less cost</small></article><article><span>Tax</span><strong>{money(tax?.sales_tax)}</strong><small>Completed sales tax</small></article><article><span>Data quality</span><strong>{unavailable?'Unavailable':partial?'Partial':'Live'}</strong><small>{unavailable?'Backend report unavailable':partial?'Some report sections failed':'Connected to business services'}</small></article></section>
 {message&&<div className="phase20Notice"><ShieldCheck size={15}/>{message}</div>}
 <div className="phase20Tabs">{['Executive','Products','Customers','Procurement','Delivery','Warranty','Returns','Finance','Website'].map(x=><button className={tab===x?'active':''} key={x} onClick={()=>setTab(x)}>{x}</button>)}</div>
 <section className="panel phase20Panel"><div className="panelHeading"><div><h3>{tab} report</h3><p>{data.length?`${data.length.toLocaleString()} rows available.`:partial?'This report section is unavailable because its backend data source failed.':'No recorded activity for this report.'}</p></div><span className="phase20Live"><i/>Live</span></div>{data.length?<div className="tableWrap"><table><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{data.slice(0,100).map((r,i)=><tr key={i}>{cols.map(c=><td key={c}>{typeof r[c]==='object'?JSON.stringify(r[c]):String(r[c]??'—')}</td>)}</tr>)}</tbody></table></div>:<div className="phase20Empty"><AlertTriangle size={20}/><strong>{partial?'Report data unavailable':'No recorded activity'}</strong><span>{partial?'The backend did not return a trustworthy value for this section; no zero is substituted.':'Nothing has been posted for this report yet. Empty data is shown explicitly rather than fabricated.'}</span></div>}</section>
 <section className="panel phase20Panel"><div className="panelHeading"><div><h3>Saved snapshots</h3><p>Historical report snapshots are retained for auditability.</p></div><RefreshCw size={16}/></div><div className="phase20SnapshotGrid">{snapshots.slice(0,8).map((s:any)=><div key={s.id}><strong>{s.report_key}</strong><span>{String(s.period_start).slice(0,10)} → {String(s.period_end).slice(0,10)}</span><small>{s.generated_by_name||'System'}</small></div>)}{!snapshots.length&&<span className="phase20Muted">No snapshots.</span>}</div></section></div>
}
