'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, BarChart3, Boxes, BriefcaseBusiness, CalendarRange, Download, FileText, Filter, Gauge, RefreshCw, Save, ShoppingCart, Sparkles, Truck, Users, Wallet } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

type Any = Record<string, any>;
const money=(v:any)=>Number.isFinite(Number(v))?new Intl.NumberFormat('en-UG',{style:'currency',currency:'UGX',maximumFractionDigits:0}).format(Number(v)):'—';
const num=(v:any)=>Number.isFinite(Number(v))?new Intl.NumberFormat('en-UG',{maximumFractionDigits:0}).format(Number(v)):'—';
const pct=(v:any)=>Number.isFinite(Number(v))?`${Number(v).toFixed(1)}%`:'—';
const palette=['#b89032','#26364f','#7b8799','#d8c27c','#52637c','#9d7c2b'];
async function api(path:string,init:RequestInit={}){const r=await fetch(`/api${path}`,{...init,headers:{'Content-Type':'application/json',...(init.headers||{})}});if(!r.ok){const t=await r.text();let d:any;try{d=JSON.parse(t)}catch{d=null}throw new Error(d?.error||'The report action could not be completed.')}const t=await r.text();try{return t?JSON.parse(t):null}catch{return t}}
function Kpi({label,value,note,icon:Icon}:{label:string;value:string;note:string;icon:any}){return <article className="stockHeroCard"><div className="stockHeroIcon"><Icon size={19}/></div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></article>}
function Panel({title,text,children,action}:{title:string;text?:string;children:any;action?:any}){return <section className="panel"><div className="panelHeading"><div><h3>{title}</h3>{text&&<p>{text}</p>}</div>{action}</div>{children}</section>}
function Empty({text}:{text:string}){return <div className="emptyState">{text}</div>}
function Table({rows,columns}:{rows:Any[];columns:[string,string][]}){return <div className="tableWrap"><table><thead><tr>{columns.map(([k,l])=><th key={k}>{l}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map(([k])=><td key={k}>{['revenue','amount','balance','gross_margin','cost','merchandise_value','outstanding','refund_amount','tax','debit','credit'].some(x=>k.includes(x))?money(r[k]):k.includes('pct')?pct(r[k]):r[k]??'—'}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={columns.length}><Empty text="No records are available for this period."/></td></tr>}</tbody></table></div>}

export function ReportsWorkspace({permissions}:{permissions:string[]}){
 const today=new Date(); const prior=new Date(today); prior.setDate(today.getDate()-29);
 const iso=(d:Date)=>d.toISOString().slice(0,10);
 const [start,setStart]=useState(iso(prior)); const [end,setEnd]=useState(iso(today)); const [locationId,setLocationId]=useState('');
 const [summary,setSummary]=useState<Any|null>(null),[trend,setTrend]=useState<Any[]>([]),[payments,setPayments]=useState<Any[]>([]),[products,setProducts]=useState<Any[]>([]),[customers,setCustomers]=useState<Any[]>([]),[categories,setCategories]=useState<Any[]>([]),[procurement,setProcurement]=useState<Any[]>([]),[returns,setReturns]=useState<Any[]>([]),[aging,setAging]=useState<Any[]>([]),[finance,setFinance]=useState<Any[]>([]),[warranty,setWarranty]=useState<Any[]>([]),[delivery,setDelivery]=useState<Any[]>([]),[inventoryAge,setInventoryAge]=useState<Any[]>([]),[inventoryTurn,setInventoryTurn]=useState<Any[]>([]),[cashiers,setCashiers]=useState<Any[]>([]),[locations,setLocations]=useState<Any[]>([]),[snapshots,setSnapshots]=useState<Any[]>([]);
 const [tab,setTab]=useState('executive'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const canManage=permissions.includes('bi.manage'),canExport=permissions.includes('bi.export'),canView=permissions.includes('bi.view');
 const query=`?start=${encodeURIComponent(start)}&end=${encodeURIComponent(end)}${locationId?`&locationId=${encodeURIComponent(locationId)}`:''}`;
 async function load(){if(!canView)return;setBusy(true);setError('');try{const [s,t,p,pr,c,cat,po,re,ag,fi,wa,dlv,invAge,invTurn,cash,loc,sn]=await Promise.all([api(`/bi/summary${query}`),api(`/bi/sales-trend${query}`),api(`/bi/payment-methods${query}`),api(`/bi/products${query}`),api(`/bi/customers${query}`),api(`/bi/categories${query}`),api(`/bi/procurement${query}`),api(`/bi/returns${query}`),api(`/bi/credit-aging${query}`),api(`/bi/finance${query}`),api(`/bi/warranty${query}`),api(`/bi/delivery${query}`),api(`/bi/inventory-ageing${query}`),api(`/bi/inventory-turnover${query}`),api(`/bi/cashiers${query}`),api('/bi/locations'),api(`/bi/snapshots${query}`)]);setSummary(s);setTrend(t||[]);setPayments(p||[]);setProducts(pr||[]);setCustomers(c||[]);setCategories(cat||[]);setProcurement(po||[]);setReturns(re||[]);setAging(ag||[]);setFinance(fi||[]);setWarranty(wa||[]);setDelivery(dlv||[]);setInventoryAge(invAge||[]);setInventoryTurn(invTurn||[]);setCashiers(cash||[]);setLocations(loc||[]);setSnapshots(sn||[])}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[start,end,locationId]);
 const topProducts=useMemo(()=>products.slice(0,8).map((x:any)=>({name:x.product||x.name||'Product',value:Number(x.revenue||0)})),[products]);
 const paymentData=useMemo(()=>payments.map((x:any)=>({name:x.method,value:Number(x.amount||0)})),[payments]);
 const marginData=useMemo(()=>products.slice(0,8).map((x:any)=>({name:x.product||'Product',margin:Number(x.gross_margin||0)})),[products]);
 const categoryData=useMemo(()=>categories.slice(0,8).map((x:any)=>({name:x.category,value:Number(x.revenue||0)})),[categories]);
 const financeData=useMemo(()=>finance.filter((x:any)=>['Revenue','Expense'].includes(x.account_type)).slice(0,10).map((x:any)=>({name:x.name,value:Math.abs(Number(x.balance||0)),type:x.account_type})),[finance]);
 async function saveSnapshot(){setBusy(true);setSaved('');try{await api('/bi/snapshots',{method:'POST',body:JSON.stringify({start,end,reportKey:'management-pack'})});setSaved('Report saved for later review.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 function exportReport(type:string){window.location.href=`/api/bi/export?type=${encodeURIComponent(type)}&start=${encodeURIComponent(start)}&end=${encodeURIComponent(end)}`}
 if(!canView)return <div className="workspace"><section className="welcome"><div><span className="eyebrow">Business reports</span><h2>Reports</h2><p>You do not have access to business performance reports.</p></div></section></div>;
 return <div className="workspace reportsWorkspace">
  <section className="welcome"><div><span className="eyebrow">Business intelligence · Management</span><h2>Business Performance Centre</h2><p>One decision-making view across sales, customers, products, stock, purchasing, finance, credit, delivery and service — using the same live business records.</p></div><div className="workspaceActions"><button className="softAction" disabled={busy} onClick={load}><RefreshCw size={14}/>{busy?'Refreshing…':'Refresh'}</button>{canManage&&<button className="primaryAction" disabled={busy} onClick={saveSnapshot}><Save size={14}/> Save report</button>}</div></section>
  {error&&<div className="adminError">{error}</div>}{saved&&<div className="adminSuccess">{saved}</div>}
  <section className="stockCommandBar"><div className="stockTabs">{[['executive','Executive'],['sales','Sales'],['customers','Customers'],['products','Products'],['operations','Operations'],['finance','Finance'],['credit','Credit'],['service','Service'],['saved','Saved reports']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div><div className="stockActions"><label className="reportFilter"><CalendarRange size={14}/><input type="date" value={start} onChange={e=>setStart(e.target.value)}/><span>to</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="reportFilter"><Filter size={14}/><select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">All locations</option>{locations.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div></section>

  {tab==='executive'&&<><section className="stockHeroGrid financeHeroGrid"><Kpi icon={Wallet} label="Revenue" value={money(summary?.sales?.revenue)} note="Completed sales"/><Kpi icon={Gauge} label="Gross margin" value={pct(summary?.grossMarginPct)} note={money(summary?.margin?.gross_margin)}/><Kpi icon={ShoppingCart} label="Orders" value={num(summary?.orders?.total)} note={`${num(summary?.orders?.open)} currently open`}/><Kpi icon={Boxes} label="Stock value" value={money(summary?.inventory?.stock_value)} note={`${num(summary?.inventory?.units)} units`}/><Kpi icon={Users} label="Customers" value={num(summary?.customers?.total)} note={`${num(summary?.customers?.acquired)} acquired`}/><Kpi icon={Truck} label="Delivery cost" value={money(summary?.delivery?.cost)} note={`${num(summary?.delivery?.delivered)} delivered`}/></section>
   <section className="stockOverviewGrid"><Panel title="Revenue movement" text="Daily completed sales across the selected period."><div className="financeChart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend.map((x:any)=>({...x,label:String(x.day).slice(5)}))}><defs><linearGradient id="reportRevenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#b89032" stopOpacity={0.3}/><stop offset="100%" stopColor="#b89032" stopOpacity={0.02}/></linearGradient></defs><CartesianGrid stroke="#ebe7dd" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label"/><YAxis tickFormatter={(v)=>`${Math.round(Number(v)/1000)}k`}/><Tooltip formatter={(v:any)=>money(v)}/><Area dataKey="revenue" type="monotone" stroke="#b89032" fill="url(#reportRevenue)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Panel><Panel title="Payment mix" text="How completed sales were paid."><div className="financeChart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={paymentData} dataKey="value" nameKey="name" innerRadius="52%" outerRadius="76%">{paymentData.map((_:any,i:number)=><Cell key={i} fill={palette[i%palette.length]}/>)}</Pie><Tooltip formatter={(v:any)=>money(v)}/><Legend/></PieChart></ResponsiveContainer></div></Panel></section>
   <section className="stockOverviewGrid"><Panel title="Top products" text="Revenue contribution from the product catalogue."><div className="financeChart wide"><ResponsiveContainer width="100%" height="100%"><BarChart data={topProducts} layout="vertical" margin={{left:25,right:20}}><CartesianGrid stroke="#ebe7dd" strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tickFormatter={(v)=>`${Math.round(Number(v)/1000)}k`}/><YAxis type="category" dataKey="name" width={120}/><Tooltip formatter={(v:any)=>money(v)}/><Bar dataKey="value" fill="#26364f" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div></Panel><Panel title="Business health" text="Exceptions and workload that deserve management attention."><div className="attentionStack"><div className="attentionRow"><span className="attentionIcon"><CreditCardIcon/></span><span className="attentionCopy"><strong>Credit outstanding</strong><small>Active and restructured customer credit</small></span><b>{money(summary?.credit?.outstanding)}</b></div><div className="attentionRow"><span className="attentionIcon"><Activity size={17}/></span><span className="attentionCopy"><strong>Warranty cases</strong><small>Open service cases in the period</small></span><b>{num(summary?.warranty?.open)}</b></div><div className="attentionRow"><span className="attentionIcon"><BriefcaseBusiness size={17}/></span><span className="attentionCopy"><strong>Purchasing value</strong><small>Non-cancelled purchase orders</small></span><b>{money(summary?.procurement?.merchandise_value)}</b></div></div></Panel></section></>}
  {tab==='sales'&&<><section className="stockOverviewGrid"><Panel title="Sales by category" text="Revenue and gross contribution by product category."><div className="financeChart"><ResponsiveContainer width="100%" height="100%"><BarChart data={categoryData}><CartesianGrid stroke="#ebe7dd" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis tickFormatter={(v)=>`${Math.round(Number(v)/1000)}k`}/><Tooltip formatter={(v:any)=>money(v)}/><Bar dataKey="value" fill="#b89032" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></Panel><Panel title="Product contribution" text="Highest gross-margin products in the period."><div className="financeChart"><ResponsiveContainer width="100%" height="100%"><BarChart data={marginData} layout="vertical" margin={{left:25,right:20}}><CartesianGrid stroke="#ebe7dd" strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tickFormatter={(v)=>`${Math.round(Number(v)/1000)}k`}/><YAxis type="category" dataKey="name" width={120}/><Tooltip formatter={(v:any)=>money(v)}/><Bar dataKey="margin" fill="#52637c" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div></Panel><Panel title="Sales by cashier" text="Recorded completed sales by team member."><Table rows={cashiers.slice(0,20)} columns={[[ 'cashier','Cashier'],['transactions','Transactions'],['revenue','Revenue'],['discounts','Discounts']]}/></Panel></section><Panel title="Customer revenue ranking" text="Customers with completed sales in the selected period."><Table rows={customers.slice(0,50)} columns={[[ 'customer_no','Customer'],['name','Name'],['phone','Phone'],['transactions','Transactions'],['revenue','Revenue'],['units','Units']]}/></Panel></>}
  {tab==='customers'&&<Panel title="Customer performance" text="Revenue, transaction frequency and units purchased."><Table rows={customers} columns={[[ 'customer_no','Customer'],['name','Name'],['customer_type','Type'],['transactions','Transactions'],['revenue','Revenue'],['units','Units']]}/></Panel>}
  {tab==='products'&&<><Panel title="Product performance" text="The same catalogue and sales records used by the Products module."><Table rows={products} columns={[[ 'product','Product'],['sku','Product code'],['units','Units'],['revenue','Revenue'],['cost','Cost'],['gross_margin','Gross margin']]}/></Panel><Panel title="Category performance" text="Category-level commercial performance."><Table rows={categories} columns={[[ 'category','Category'],['units','Units'],['revenue','Revenue'],['cost','Cost'],['gross_margin','Gross margin']]}/></Panel></>}
  {tab==='operations'&&<><section className="stockOverviewGrid"><Panel title="Purchasing by supplier" text="Purchase commitments and receiving progress."><Table rows={procurement} columns={[[ 'supplier','Supplier'],['purchase_orders','Orders'],['merchandise_value','Value'],['received_units','Received'],['received_pct','Received %']]}/></Panel><Panel title="Returns" text="Return workload and refund exposure."><Table rows={returns} columns={[[ 'status','Status'],['count','Returns'],['refund_amount','Refund amount']]}/></Panel></section><Panel title="Service partner workload" text="Repair work across the service network."><Table rows={warranty} columns={[[ 'repair_partner','Partner'],['jobs','Jobs'],['active_jobs','Active'],['completed_jobs','Completed'],['partner_cost','Partner cost'],['avg_days','Average days']]}/></Panel></>}
  {tab==='finance'&&<><section className="stockOverviewGrid"><Panel title="Financial account activity" text="Posted accounting activity behind the management view."><Table rows={finance.slice(0,80)} columns={[[ 'code','Code'],['name','Account'],['account_type','Type'],['debit','Debit'],['credit','Credit'],['balance','Balance']]}/></Panel><Panel title="Finance mix" text="Largest recorded account balances."><div className="financeChart"><ResponsiveContainer width="100%" height="100%"><BarChart data={financeData} layout="vertical" margin={{left:30,right:20}}><XAxis type="number" tickFormatter={(v)=>`${Math.round(Number(v)/1000)}k`}/><YAxis type="category" dataKey="name" width={130}/><Tooltip formatter={(v:any)=>money(v)}/><Bar dataKey="value" fill="#26364f"/></BarChart></ResponsiveContainer></div></Panel></section></>}
  {tab==='credit'&&<Panel title="Credit ageing" text="Amounts currently due by ageing bucket."><Table rows={aging} columns={[[ 'bucket','Ageing'],['installments','Installments'],['outstanding','Outstanding']]}/></Panel>}
  {tab==='service'&&<Panel title="Warranty & repair performance" text="Service workload and partner performance."><Table rows={warranty} columns={[[ 'repair_partner','Partner'],['jobs','Jobs'],['active_jobs','Active'],['completed_jobs','Completed'],['partner_cost','Partner cost'],['avg_days','Average days']]}/></Panel>}
  {tab==='saved'&&<Panel title="Saved management reports" text="Saved point-in-time report summaries for management review." action={canExport&&<div className="workspaceActions"><button className="softAction" onClick={()=>exportReport('sales')}><Download size={14}/> Sales CSV</button><button className="softAction" onClick={()=>exportReport('products')}><Download size={14}/> Products CSV</button></div>}><Table rows={snapshots} columns={[[ 'report_key','Report'],['period_start','From'],['period_end','To'],['generated_by_name','Saved by'],['created_at','Saved at']]}/></Panel>}
  <section className="actionStrip"><div><span className="eyebrow">Take the next action</span><strong>Reports stay connected to the operational work.</strong></div><div className="actionLinks"><a href="/sales"><ShoppingCart size={16}/> Sales</a><a href="/products"><Boxes size={16}/> Products</a><a href="/customers"><Users size={16}/> Customers</a><a href="/finance"><Wallet size={16}/> Finance</a><a href="/stock"><Boxes size={16}/> Stock</a></div></section>
 </div>
}
function CreditCardIcon(){return <Wallet size={17}/>}
