'use client';
import { useMemo, useState } from 'react';
import { BadgeCheck, ClipboardCheck, FileText, HeartHandshake, PackageCheck, Plus, RefreshCw, Search, Truck, UserRound, Wrench, X, WalletCards } from 'lucide-react';

type Any = any;
const api = async (path:string, init:RequestInit={}) => { const r=await fetch(path,{...init,headers:{'Content-Type':'application/json',...(init.headers||{})}}); const t=await r.text(); let d:any=null; try{d=t?JSON.parse(t):null}catch{d=t} if(!r.ok) throw new Error(d?.error||'The action could not be completed.'); return d; };
const money=(v:any)=>Number.isFinite(Number(v))?new Intl.NumberFormat('en-UG',{style:'currency',currency:'UGX',maximumFractionDigits:0}).format(Number(v)):'—';
function Modal({title,children,onClose,wide=false}:{title:string;children:any;onClose:()=>void;wide?:boolean}){return <div className="adminModalBackdrop"><div className={`adminModal ${wide?'wide':''}`}><header><div><span className="eyebrow">Service</span><h3>{title}</h3></div><button className="iconButton" onClick={onClose}><X size={17}/></button></header>{children}</div></div>}
function Field({label,value,onChange,type='text',placeholder=''}:any){return <label className="adminField"><span>{label}</span><input type={type} value={value??''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Select({label,value,onChange,options}:any){return <label className="adminField"><span>{label}</span><select value={value??''} onChange={e=>onChange(e.target.value)}>{options.map((o:any)=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select></label>}
function Table({rows,columns,onRow}:{rows:Any[];columns:[string,string][];onRow?:(r:any)=>void}){return <div className="tableWrap"><table><thead><tr>{columns.map(([k,l])=><th key={k}>{l}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i} onClick={()=>onRow?.(r)} style={onRow?{cursor:'pointer'}:undefined}>{columns.map(([k])=><td key={k}>{k==='status'?<span className="catalogStatus">{r[k]||'—'}</span>:k.includes('amount')||k.includes('cost')||k.includes('refund')?money(r[k]):r[k]??'—'}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={columns.length}><div className="emptyState">No records to show yet.</div></td></tr>}</tbody></table></div>}

export function ServiceWorkspace({returnsSummary,warrantySummary,returns,claims,policies,partners,customers,orders,sales,variants,locations,staff,permissions}:{returnsSummary:Any;warrantySummary:Any;returns:Any[];claims:Any[];policies:Any[];partners:Any[];customers:Any[];orders:Any[];sales:Any[];variants:Any[];locations:Any[];staff:Any[];permissions:string[]}){
 const [tab,setTab]=useState('overview'); const [modal,setModal]=useState<string|null>(null); const [selected,setSelected]=useState<any>(null); const [detail,setDetail]=useState<any>(null); const [query,setQuery]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [refresh,setRefresh]=useState(0);
 const canManageReturns=permissions.includes('returns.manage'), canRefund=permissions.includes('returns.refund'), canWarranty=permissions.includes('warranty.manage'), canPartners=permissions.includes('warranty.partners');
 const filteredReturns=useMemo(()=>returns.filter(r=>!query||`${r.return_no} ${r.customer_name||''} ${r.order_no||''} ${r.sale_no||''} ${r.status||''}`.toLowerCase().includes(query.toLowerCase())),[returns,query]);
 const filteredClaims=useMemo(()=>claims.filter(r=>!query||`${r.claim_no} ${r.customer_name||''} ${r.product_name||''} ${r.issue||''} ${r.status||''}`.toLowerCase().includes(query.toLowerCase())),[claims,query]);
 const refreshPage=()=>{setRefresh(x=>x+1);setModal(null);setSelected(null);setDetail(null);setError('')};
 const run=async(fn:()=>Promise<any>)=>{setBusy(true);setError('');try{await fn();refreshPage()}catch(e:any){setError(e.message||'The action could not be completed.')}finally{setBusy(false)}};
 const openReturn=async(r:any)=>{try{setDetail(await api(`/api/returns/${r.id}`))}catch(e:any){setError((e as Error).message)}};
 const openClaim=async(r:any)=>{try{setDetail(await api(`/api/warranty/claims/${r.id}`))}catch(e:any){setError((e as Error).message)}};
 return <div className="workspace serviceWorkspace" key={refresh}>
  <section className="welcome"><div><span className="eyebrow">Customer care · Service</span><h2>Service Control Centre</h2><p>Keep returns, warranty cases, repairs and customer follow-ups moving from one clear business workspace.</p></div><button className="softAction" onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={14}/> Refresh</button></section>
  <section className="stockHeroGrid">
   <article className="stockHeroCard"><div className="stockHeroIcon"><PackageCheck size={20}/></div><div><span>Returns</span><strong>{returnsSummary?.total??0}</strong><small>{returnsSummary?.requested??0} waiting for action</small></div></article>
   <article className="stockHeroCard"><div className="stockHeroIcon"><BadgeCheck size={20}/></div><div><span>Warranty cases</span><strong>{warrantySummary?.total??0}</strong><small>{warrantySummary?.open??0} still open</small></div></article>
   <article className="stockHeroCard alert"><div className="stockHeroIcon"><Wrench size={20}/></div><div><span>In repair</span><strong>{warrantySummary?.inRepair??0}</strong><small>{warrantySummary?.ready??0} ready for collection</small></div></article>
   <article className="stockHeroCard"><div className="stockHeroIcon"><WalletCards size={20}/></div><div><span>Refunds awaiting action</span><strong>{returnsSummary?.refundPending??0}</strong><small>{money(returnsSummary?.refundValue)} across active refunds</small></div></article>
  </section>
  <section className="stockCommandBar"><div className="stockTabs">{[['overview','Overview'],['returns','Returns'],['warranty','Warranty'],['repairs','Repairs'],['policies','Warranty policies'],['partners','Repair partners']].map(([id,l])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{l}</button>)}</div><div className="stockActions">{canManageReturns&&<button onClick={()=>setModal('return')}><Plus size={14}/> New return</button>}{canWarranty&&<button onClick={()=>setModal('claim')}><Plus size={14}/> New warranty case</button>}{canWarranty&&<button className="primaryAction" onClick={()=>setModal('policy')}><Plus size={14}/> Add warranty policy</button>}</div></section>
  <div className="stockFilterBar"><div className="stockSearch"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customers, cases, orders or products"/></div></div>
  {tab==='overview'&&<>
   <section className="stockOverviewGrid"><div className="panel"><div className="panelHeading"><div><h3>What needs attention</h3><p>Service work that may need a decision today.</p></div></div><div className="attentionList">
    <div><PackageCheck size={15}/><div><strong>{returnsSummary?.requested??0} returns awaiting action</strong><span>Requests waiting for approval or receipt</span></div><b>{returnsSummary?.requested??0}</b></div>
    <div><WalletCards size={15}/><div><strong>{returnsSummary?.refundPending??0} refunds awaiting payment</strong><span>Approved refunds not fully completed</span></div><b>{returnsSummary?.refundPending??0}</b></div>
    <div><Wrench size={15}/><div><strong>{warrantySummary?.inRepair??0} repairs in progress</strong><span>Keep customers updated on repair progress</span></div><b>{warrantySummary?.inRepair??0}</b></div>
    <div><HeartHandshake size={15}/><div><strong>{warrantySummary?.ready??0} ready for collection</strong><span>Customers can collect completed repairs</span></div><b>{warrantySummary?.ready??0}</b></div>
   </div></div><div className="panel"><div className="panelHeading"><div><h3>Service journey</h3><p>One connected flow from customer issue to resolution.</p></div></div><div className="adminRelationshipList"><div><span>1</span><strong>Customer or transaction</strong><b>Customer · order · sale</b></div><div><span>2</span><strong>Assessment</strong><b>Return · warranty review</b></div><div><span>3</span><strong>Resolution</strong><b>Refund · restock · repair</b></div><div><span>4</span><strong>Customer outcome</strong><b>Collection · completed service</b></div></div></div></section>
   <section className="panel"><div className="panelHeading"><div><h3>Recent service activity</h3><p>Returns and warranty cases connected to customers, orders and products.</p></div></div><Table rows={[...returns.slice(0,6).map(x=>({...x,kind:'Return'})),...claims.slice(0,6).map(x=>({...x,kind:'Warranty'}))].sort((a,b)=>new Date(b.created_at||0).getTime()-new Date(a.created_at||0).getTime()).slice(0,10)} columns={[[ 'kind','Type'],['return_no','Reference'],['claim_no','Warranty case'],['customer_name','Customer'],['product_name','Product'],['status','Status']]} /></section>
  </>}
  {tab==='returns'&&<section className="panel"><div className="panelHeading"><div><h3>Returns</h3><p>Manage customer returns through approval, receipt, inspection, refund and restocking.</p></div></div><Table rows={filteredReturns} columns={[[ 'return_no','Return'],['customer_name','Customer'],['order_no','Order'],['sale_no','Sale'],['status','Status'],['refund_amount','Refund'],['refunded_amount','Paid back']]} onRow={openReturn}/></section>}
  {tab==='warranty'&&<section className="panel"><div className="panelHeading"><div><h3>Warranty cases</h3><p>Review eligibility, progress, repair work and customer resolution.</p></div></div><Table rows={filteredClaims} columns={[[ 'claim_no','Case'],['customer_name','Customer'],['product_name','Product'],['issue','Issue'],['warranty_status','Coverage'],['status','Status'],['estimated_cost','Estimated cost']]} onRow={openClaim}/></section>}
  {tab==='repairs'&&<section className="panel"><div className="panelHeading"><div><h3>Repairs</h3><p>Approved and active warranty cases that are moving through repair work.</p></div></div><Table rows={claims.filter(c=>['Approved','In Repair','Ready for Collection'].includes(c.status))} columns={[[ 'claim_no','Warranty case'],['customer_name','Customer'],['product_name','Product'],['issue','Issue'],['warranty_status','Coverage'],['status','Repair stage'],['estimated_cost','Estimated cost']]} onRow={openClaim}/></section>}
  {tab==='policies'&&<section className="panel"><div className="panelHeading"><div><h3>Warranty policies</h3><p>Coverage rules used when a warranty case is opened.</p></div></div><Table rows={policies} columns={[[ 'name','Policy'],['brand_name','Brand'],['category_name','Category'],['duration_days','Days'],['coverage','Coverage'],['status','Status']]} /></section>}
  {tab==='partners'&&<section className="panel"><div className="panelHeading"><div><h3>Repair partners</h3><p>Repair centres and technicians supporting customer service.</p></div>{canPartners&&<button className="primaryAction" onClick={()=>setModal('partner')}><Plus size={14}/> Add partner</button>}</div><Table rows={partners} columns={[[ 'name','Partner'],['partner_type','Type'],['status','Status'],['total_jobs','Jobs'],['active_jobs','Active'],['completed_jobs','Completed'],['total_partner_cost','Cost']]} /></section>}
  {error&&<div className="error">{error}</div>}
  {modal==='return'&&<ReturnModal customers={customers} orders={orders} sales={sales} variants={variants} locations={locations} onClose={()=>setModal(null)} onDone={refreshPage} setError={setError}/>} 
  {modal==='claim'&&<ClaimModal customers={customers} orders={orders} sales={sales} variants={variants} policies={policies} onClose={()=>setModal(null)} onDone={refreshPage} setError={setError}/>} 
  {modal==='policy'&&<PolicyModal policies={policies} onClose={()=>setModal(null)} onDone={refreshPage}/>} 
  {modal==='partner'&&<PartnerModal onClose={()=>setModal(null)} onDone={refreshPage}/>} 
  {detail&&<DetailModal detail={detail} type={detail.return_no?'return':'claim'} canManageReturns={canManageReturns} canRefund={canRefund} canWarranty={canWarranty} canPartners={canPartners} variants={variants} locations={locations} staff={staff} partners={partners} onClose={()=>setDetail(null)} onRefresh={refreshPage}/>} 
 </div>
}

function ReturnModal({customers,orders,sales,variants,locations,onClose,onDone,setError}:any){
 const [source,setSource]=useState<'order'|'sale'>('order'); const [sourceId,setSourceId]=useState(orders[0]?.id||''); const [detail,setDetail]=useState<any>(null); const [f,setF]=useState<any>({customerId:'',locationId:locations[0]?.id||'',reason:'Customer return',notes:'',refundMethod:'Original Payment'}); const [lines,setLines]=useState<any[]>([]); const [loading,setLoading]=useState(false);
 const load=async(id:string,kind=source)=>{setSourceId(id);if(!id){setDetail(null);setLines([]);return}setLoading(true);try{const d=await api(`/api/${kind==='order'?'orders':'sales'}/${id}`);setDetail(d);setF((x:any)=>({...x,customerId:d.customer_id||''}));setLines((d.lines||[]).map((l:any)=>({lineId:l.id,variantId:l.variant_id,product_name:l.product_name,quantity:1,max:Number(l.quantity||1),unitPrice:Number(l.unit_price||0),condition:'Unknown',disposition:'Restock',reason:''})));}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const submit=async(e:any)=>{e.preventDefault();try{await api('/api/returns',{method:'POST',body:JSON.stringify({[source==='order'?'orderId':'saleId']:sourceId,customerId:f.customerId||null,locationId:f.locationId||null,reason:f.reason,notes:f.notes,refundMethod:f.refundMethod,lines:lines.map(x=>({[source==='order'?'orderLineId':'saleLineId']:x.lineId,variantId:x.variantId,quantity:Number(x.quantity),unitPrice:Number(x.unitPrice),condition:x.condition,disposition:x.disposition,reason:x.reason}))})});onDone();onClose()}catch(e:any){setError(e.message)}};
 return <Modal title="Create return" onClose={onClose} wide><form onSubmit={submit}><div className="adminFormGrid"><Select label="Original transaction" value={source} onChange={(v:any)=>{setSource(v);setSourceId('');setDetail(null);setLines([])}} options={[{value:'order',label:'Order'},{value:'sale',label:'Sale'}]}/><Select label="Transaction" value={sourceId} onChange={(v:any)=>load(v,source)} options={[{value:'',label:'Select transaction'},...(source==='order'?orders:sales).map((x:any)=>({value:x.id,label:`${source==='order'?x.order_no:x.sale_no} · ${x.customer_name||'Guest'}`}))]}/><Select label="Customer" value={f.customerId} onChange={(v:any)=>setF({...f,customerId:v})} options={[{value:'',label:'From original transaction'},...customers.map((x:any)=>({value:x.id,label:`${x.customer_no} · ${x.name}`}))]}/><Select label="Return location" value={f.locationId} onChange={(v:any)=>setF({...f,locationId:v})} options={[{value:'',label:'Choose location'},...locations.map((x:any)=>({value:x.id,label:x.name}))]}/><Field label="Reason" value={f.reason} onChange={(v:any)=>setF({...f,reason:v})}/><Select label="Refund method" value={f.refundMethod} onChange={(v:any)=>setF({...f,refundMethod:v})} options={['Original Payment','Cash','Mobile Money','Card','Bank Transfer','Store Credit','Other'].map(x=>({value:x,label:x}))}/></div>{loading?<div className="emptyState">Loading transaction items…</div>:detail&&<div className="adminFormGrid">{lines.map((l:any,i:number)=><div className="panel" key={l.lineId}><strong>{l.product_name}</strong><div className="adminFormGrid"><Field label={`Quantity (max ${l.max})`} type="number" value={l.quantity} onChange={(v:any)=>setLines(ls=>ls.map((x,j)=>j===i?{...x,quantity:Math.min(Number(v)||0,x.max)}:x))}/><Select label="Condition" value={l.condition} onChange={(v:any)=>setLines(ls=>ls.map((x,j)=>j===i?{...x,condition:v}:x))} options={['New','Good','Used','Damaged','Defective','Unknown'].map(x=>({value:x,label:x}))}/><Select label="What should happen" value={l.disposition} onChange={(v:any)=>setLines(ls=>ls.map((x,j)=>j===i?{...x,disposition:v}:x))} options={['Restock','Repair','Scrap','Return to Supplier','Quarantine'].map(x=>({value:x,label:x}))}/></div></div>)}</div>}<div className="adminSubmit"><button type="button" onClick={onClose}>Cancel</button><button className="primaryAction" disabled={!sourceId||!lines.length}>Create return</button></div></form></Modal>
}
function ClaimModal({customers,orders,sales,variants,policies,onClose,onDone,setError}:any){const [f,setF]=useState<any>({customerId:'',orderId:'',saleId:'',variantId:variants[0]?.id||'',serializedUnitId:'',policyId:'',issue:'',estimatedCost:0}); const submit=async(e:any)=>{e.preventDefault();try{await api('/api/warranty/claims',{method:'POST',body:JSON.stringify({...f,orderId:f.orderId||null,saleId:f.saleId||null,customerId:f.customerId||null,policyId:f.policyId||null,serializedUnitId:f.serializedUnitId||null,estimatedCost:Number(f.estimatedCost||0)})});onDone();onClose()}catch(e:any){setError(e.message)}};return <Modal title="Create warranty case" onClose={onClose} wide><form onSubmit={submit}><div className="adminFormGrid"><Select label="Customer" value={f.customerId} onChange={(v:any)=>setF({...f,customerId:v})} options={[{value:'',label:'Choose customer'},...customers.map((x:any)=>({value:x.id,label:`${x.customer_no} · ${x.name}`}))]}/><Select label="Order (optional)" value={f.orderId} onChange={(v:any)=>setF({...f,orderId:v,saleId:''})} options={[{value:'',label:'No order selected'},...orders.map((x:any)=>({value:x.id,label:`${x.order_no} · ${x.customer_name||'Guest'}`}))]}/><Select label="Sale (optional)" value={f.saleId} onChange={(v:any)=>setF({...f,saleId:v,orderId:''})} options={[{value:'',label:'No sale selected'},...sales.filter((x:any)=>x.status==='Completed').map((x:any)=>({value:x.id,label:`${x.sale_no} · ${x.customer_name||'Guest'}`}))]}/><Select label="Product variant" value={f.variantId} onChange={(v:any)=>setF({...f,variantId:v})} options={[{value:'',label:'Select product'},...variants.map((x:any)=>({value:x.id,label:`${x.product_name} · ${x.variant_name||x.sku}`}))]}/><Select label="Warranty policy" value={f.policyId} onChange={(v:any)=>setF({...f,policyId:v})} options={[{value:'',label:'Review manually'},...policies.filter((x:any)=>x.status==='Active').map((x:any)=>({value:x.id,label:x.name}))]}/><Field label="Estimated cost" type="number" value={f.estimatedCost} onChange={(v:any)=>setF({...f,estimatedCost:v})}/></div><Field label="Customer issue" value={f.issue} onChange={(v:any)=>setF({...f,issue:v})} placeholder="Describe the problem"/><div className="adminSubmit"><button type="button" onClick={onClose}>Cancel</button><button className="primaryAction">Create warranty case</button></div></form></Modal>}
function PolicyModal({onClose,onDone}:any){const [f,setF]=useState<any>({name:'',durationDays:365,coverage:'',exclusions:'',status:'Active'});return <Modal title="Add warranty policy" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{await api('/api/warranty/policies',{method:'POST',body:JSON.stringify({...f,durationDays:Number(f.durationDays)})});onDone();onClose()}catch(err:any){alert(err.message)}}}><Field label="Policy name" value={f.name} onChange={(v:any)=>setF({...f,name:v})}/><Field label="Coverage period (days)" type="number" value={f.durationDays} onChange={(v:any)=>setF({...f,durationDays:v})}/><Field label="What is covered" value={f.coverage} onChange={(v:any)=>setF({...f,coverage:v})}/><Field label="What is not covered" value={f.exclusions} onChange={(v:any)=>setF({...f,exclusions:v})}/><Select label="Status" value={f.status} onChange={(v:any)=>setF({...f,status:v})} options={['Active','Inactive']}/><div className="adminSubmit"><button className="primaryAction">Save policy</button></div></form></Modal>}
function PartnerModal({onClose,onDone}:any){const [f,setF]=useState<any>({name:'',partnerType:'Repair Centre',phone:'',email:'',address:'',serviceArea:'',defaultLaborCost:0,status:'Active',notes:''});return <Modal title="Add repair partner" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{await api('/api/warranty/partners',{method:'POST',body:JSON.stringify({...f,defaultLaborCost:Number(f.defaultLaborCost||0)})});onDone();onClose()}catch(err:any){alert(err.message)}}}><Field label="Partner name" value={f.name} onChange={(v:any)=>setF({...f,name:v})}/><Select label="Type" value={f.partnerType} onChange={(v:any)=>setF({...f,partnerType:v})} options={['Repair Centre','Technician','Authorized Service Centre']}/><div className="adminFormGrid"><Field label="Phone" value={f.phone} onChange={(v:any)=>setF({...f,phone:v})}/><Field label="Email" value={f.email} onChange={(v:any)=>setF({...f,email:v})}/><Field label="Service area" value={f.serviceArea} onChange={(v:any)=>setF({...f,serviceArea:v})}/><Field label="Standard labour cost" type="number" value={f.defaultLaborCost} onChange={(v:any)=>setF({...f,defaultLaborCost:v})}/></div><div className="adminSubmit"><button className="primaryAction">Save partner</button></div></form></Modal>}

function DetailModal({detail,type,canManageReturns,canRefund,canWarranty,canPartners,variants,locations,staff,partners,onClose,onRefresh}:any){const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');const [warrantyStatus,setWarrantyStatus]=useState(detail.warranty_status||'Pending');const [note,setNote]=useState(''); const run=async(fn:()=>Promise<any>)=>{setBusy(true);try{await fn();onRefresh()}catch(e:any){alert(e.message)}finally{setBusy(false)}};
 if(type==='return') return <Modal title={`${detail.return_no} · Return`} onClose={onClose} wide><div className="detailGrid"><div><span>Customer</span><strong>{detail.customer_name||'Guest'}</strong></div><div><span>Order</span><strong>{detail.order_no||detail.sale_no||'—'}</strong></div><div><span>Status</span><strong>{detail.status}</strong></div><div><span>Refund</span><strong>{money(detail.refund_amount)}</strong></div></div><div className="panel"><h4>Returned items</h4><Table rows={detail.lines||[]} columns={[[ 'product_name','Product'],['variant_name','Variant'],['quantity','Qty'],['condition','Condition'],['disposition','What happens'],['refund_amount','Refund']]} /></div>{canManageReturns&&detail.status&&<div className="adminFormGrid"><Select label="Move to" value={status} onChange={setStatus} options={[{value:'',label:'Choose next step'},...(detail.status==='Requested'?['Approved','Rejected','Cancelled']:detail.status==='Approved'?['Received','Rejected','Cancelled']:detail.status==='Received'?['Inspected','Cancelled']:detail.status==='Inspected'?['Refund Pending','Restocked','Rejected']:detail.status==='Refund Pending'?['Cancelled']:[]).map(x=>({value:x,label:x}))]}/><Field label="Note" value={note} onChange={setNote}/></div>}{status&&<button className="primaryAction" disabled={busy} onClick={()=>run(()=>api(`/api/returns/${detail.id}/status`,{method:'POST',body:JSON.stringify({status,note})}))}>Update return</button>}{canRefund&&detail.status==='Refund Pending'&&<RefundForm detail={detail} onDone={onRefresh}/>}<div className="panel"><h4>History</h4><Table rows={detail.events||[]} columns={[[ 'status','Status'],['note','Note'],['created_at','Date']]}/></div></Modal>;
 return <Modal title={`${detail.claim_no} · Warranty case`} onClose={onClose} wide><div className="detailGrid"><div><span>Customer</span><strong>{detail.customer_name||'—'}</strong></div><div><span>Product</span><strong>{detail.product_name||'—'}</strong></div><div><span>Coverage</span><strong>{detail.warranty_status||'Pending'}</strong></div><div><span>Status</span><strong>{detail.status}</strong></div></div><div className="panel"><h4>Issue</h4><p>{detail.issue}</p></div>{canWarranty&&<div className="adminFormGrid"><Select label="Next status" value={status} onChange={setStatus} options={[{value:'',label:'Choose next step'},...(detail.status==='Submitted'?['Under Review','Rejected','Cancelled']:detail.status==='Under Review'?['Approved','Rejected','Cancelled']:detail.status==='Approved'?['In Repair','Rejected','Cancelled']:detail.status==='In Repair'?['Ready for Collection','Cancelled']:detail.status==='Ready for Collection'?['Resolved','Cancelled']:[]).map(x=>({value:x,label:x}))]}/><Select label="Coverage decision" value={warrantyStatus} onChange={setWarrantyStatus} options={['Pending','Covered','Not Covered','Goodwill'].map(x=>({value:x,label:x}))}/><Field label="Note" value={note} onChange={setNote}/></div>}{status&&<button className="primaryAction" disabled={busy} onClick={()=>run(()=>api(`/api/warranty/claims/${detail.id}`,{method:'PATCH',body:JSON.stringify({status,warrantyStatus,note})}))}>Update warranty case</button>}{detail.job&&<div className="panel"><h4>Repair work</h4><Table rows={[detail.job]} columns={[[ 'job_no','Repair job'],['status','Status'],['technician_name','Technician'],['partner_name','Partner'],['diagnosis','Diagnosis'],['work_done','Work completed'],['expected_return_at','Expected return']]}/>{canWarranty&&<JobActions job={detail.job} variants={variants} locations={locations} staff={staff} partners={partners} onRefresh={onRefresh}/>}</div>}{canWarranty&&['Approved','In Repair'].includes(detail.status)&&!detail.job&&<JobCreate claim={detail} partners={partners} staff={staff} onDone={onRefresh}/>}<div className="panel"><h4>History</h4><Table rows={detail.events||[]} columns={[[ 'status','Status'],['note','Note'],['created_at','Date']]}/></div></Modal>;
}
function RefundForm({detail,onDone}:any){const [f,setF]=useState<any>({amount:detail.refund_amount,method:detail.refund_method||'Original Payment',reference:''});return <div className="panel"><h4>Complete refund</h4><div className="adminFormGrid"><Field label="Amount" type="number" value={f.amount} onChange={(v:any)=>setF({...f,amount:v})}/><Select label="Method" value={f.method} onChange={(v:any)=>setF({...f,method:v})} options={['Cash','Mobile Money','Card','Bank Transfer','Original Payment','Store Credit','Other']}/><Field label="Reference" value={f.reference} onChange={(v:any)=>setF({...f,reference:v})}/></div><button className="primaryAction" onClick={async()=>{try{await api(`/api/returns/${detail.id}/refund`,{method:'POST',body:JSON.stringify({...f,amount:Number(f.amount)})});onDone()}catch(e:any){alert(e.message)}}}>Record refund</button></div>}
function JobCreate({claim,partners,staff,onDone}:any){const [f,setF]=useState<any>({technicianId:'',partnerId:'',itemDescription:claim.product_name||'',repairLocation:'',expectedReturnAt:'',diagnosis:'',partnerCost:0,notes:''});return <div className="panel"><h4>Open repair work</h4><div className="adminFormGrid"><Select label="Technician" value={f.technicianId} onChange={(v:any)=>setF({...f,technicianId:v})} options={[{value:'',label:'Unassigned'},...staff.map((x:any)=>({value:x.id,label:x.name}))]}/><Select label="Repair partner" value={f.partnerId} onChange={(v:any)=>setF({...f,partnerId:v})} options={[{value:'',label:'Internal repair'},...partners.filter((x:any)=>x.status==='Active').map((x:any)=>({value:x.id,label:x.name}))]}/><Field label="Repair location" value={f.repairLocation} onChange={(v:any)=>setF({...f,repairLocation:v})}/><Field label="Expected return" type="datetime-local" value={f.expectedReturnAt} onChange={(v:any)=>setF({...f,expectedReturnAt:v})}/><Field label="Diagnosis" value={f.diagnosis} onChange={(v:any)=>setF({...f,diagnosis:v})}/><Field label="Partner cost" type="number" value={f.partnerCost} onChange={(v:any)=>setF({...f,partnerCost:v})}/></div><button className="primaryAction" onClick={async()=>{try{await api(`/api/warranty/claims/${claim.id}/job`,{method:'POST',body:JSON.stringify({...f,technicianId:f.technicianId||null,partnerId:f.partnerId||null,partnerCost:Number(f.partnerCost||0)})});onDone()}catch(e:any){alert(e.message)}}}>Open repair work</button></div>}
function JobActions({job,variants,locations,staff,partners,onRefresh}:any){const [f,setF]=useState<any>({status:job.status,diagnosis:job.diagnosis||'',workDone:job.work_done||'',laborCost:job.labor_cost||0,partnerCost:job.partner_cost||0,expectedReturnAt:job.expected_return_at||'',technicianId:job.technician_id||'',partnerId:job.partner_id||''});const [part,setPart]=useState<any>({variantId:variants[0]?.id||'',locationId:locations[0]?.id||'',quantity:1,reason:''});return <><div className="adminFormGrid"><Select label="Repair status" value={f.status} onChange={(v:any)=>setF({...f,status:v})} options={['Queued','Diagnosing','Repairing','Awaiting Parts','Quality Check','Completed','Cancelled'].map(x=>({value:x,label:x}))}/><Select label="Technician" value={f.technicianId} onChange={(v:any)=>setF({...f,technicianId:v})} options={[{value:'',label:'Unassigned'},...staff.map((x:any)=>({value:x.id,label:x.name}))]}/><Select label="Repair partner" value={f.partnerId} onChange={(v:any)=>setF({...f,partnerId:v})} options={[{value:'',label:'Internal repair'},...partners.map((x:any)=>({value:x.id,label:x.name}))]}/><Field label="Diagnosis" value={f.diagnosis} onChange={(v:any)=>setF({...f,diagnosis:v})}/><Field label="Work completed" value={f.workDone} onChange={(v:any)=>setF({...f,workDone:v})}/><Field label="Labour cost" type="number" value={f.laborCost} onChange={(v:any)=>setF({...f,laborCost:v})}/></div><button className="primaryAction" onClick={async()=>{try{await api(`/api/warranty/jobs/${job.id}`,{method:'PATCH',body:JSON.stringify({...f,technicianId:f.technicianId||null,partnerId:f.partnerId||null,laborCost:Number(f.laborCost||0),partnerCost:Number(f.partnerCost||0),expectedReturnAt:f.expectedReturnAt||null})});onRefresh()}catch(e:any){alert(e.message)}}}>Save repair update</button><div className="panel"><h4>Use a stock part</h4><div className="adminFormGrid"><Select label="Part" value={part.variantId} onChange={(v:any)=>setPart({...part,variantId:v})} options={variants.map((x:any)=>({value:x.id,label:`${x.product_name} · ${x.variant_name||x.sku}`}))}/><Select label="Location" value={part.locationId} onChange={(v:any)=>setPart({...part,locationId:v})} options={locations.map((x:any)=>({value:x.id,label:x.name}))}/><Field label="Quantity" type="number" value={part.quantity} onChange={(v:any)=>setPart({...part,quantity:v})}/><Field label="Reason" value={part.reason} onChange={(v:any)=>setPart({...part,reason:v})}/></div><button className="softAction" onClick={async()=>{try{await api(`/api/warranty/jobs/${job.id}/parts`,{method:'POST',body:JSON.stringify({...part,quantity:Number(part.quantity)})});onRefresh()}catch(e:any){alert(e.message)}}}>Record part use</button></div></>}
