'use client';
import { useState, type FormEvent } from 'react';
import { Building2,Save,Plus,MapPin,SlidersHorizontal } from 'lucide-react';
async function api(path:string,options?:RequestInit){const r=await fetch(path,options);const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||'Request failed');return p}
export function SettingsWorkspace({organization,settings,branches,departments,canManage,canOrg,canBranches,canDepartments}:{organization:any;settings:any;branches:any[];departments:any[];canManage:boolean;canOrg:boolean;canBranches:boolean;canDepartments:boolean}){
 const [org,setOrg]=useState(organization||{}),[localSettings,setLocalSettings]=useState(settings||{}),[localBranches,setBranches]=useState(branches),[localDepartments,setDepartments]=useState(departments),[tab,setTab]=useState('Organization'),[message,setMessage]=useState('');
 const [branchName,setBranchName]=useState(''),[branchAddress,setBranchAddress]=useState(''); const [deptName,setDeptName]=useState(''),[deptCode,setDeptCode]=useState('');
 async function saveOrg(){try{const r=await api('/api/organization',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(org)});setOrg(r);setMessage('Organization profile saved.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save organization')}}
 async function saveSettings(e:FormEvent){e.preventDefault();try{await api('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(localSettings)});setMessage('Business settings saved.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save settings')}}
 async function addBranch(){try{const b=await api('/api/branches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:branchName,address:branchAddress})});setBranches([...localBranches,b]);setBranchName('');setBranchAddress('');setMessage('Branch created.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to create branch')}}
 async function addDepartment(){try{const d=await api('/api/departments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:deptName,code:deptCode})});setDepartments([...localDepartments,d]);setDeptName('');setDeptCode('');setMessage('Department created.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to create department')}}
 const field=(key:string,label:string)=><label className="phase20Field"><span>{label}</span><input value={org?.[key]??''} onChange={e=>setOrg({...org,[key]:e.target.value})}/></label>;
 return <div className="phase20Workspace"><section className="phase20Hero"><div><span className="eyebrow">Business configuration</span><h2>Business settings with controlled scope.</h2><p>Organization identity, operating branches, departments and safe business-level defaults. Technical infrastructure remains outside this workspace.</p></div><span className="phase20Pill"><Building2 size={14}/> Business administration</span></section>{message&&<div className="phase20Notice"><Save size={15}/>{message}</div>}<div className="phase20Tabs">{['Organization','Branches','Departments','Defaults'].map(x=><button className={tab===x?'active':''} key={x} onClick={()=>setTab(x)}>{x}</button>)}</div>
 {tab==='Organization'&&<section className="panel phase20Panel"><div className="panelHeading"><div><h3>Organization identity</h3><p>Used across business documents and reporting.</p></div></div><div className="phase20FormGrid">{['legal_name','trading_name','registration_number','tax_number','country_code','currency','timezone','locale','address','city','region','postal_code','phone','email','website'].map(k=>field(k,k.replaceAll('_',' ')))}</div>{canOrg&&<button className="primaryAction" onClick={saveOrg}><Save size={15}/>Save organization</button>}</section>}
 {tab==='Branches'&&<><section className="panel phase20Panel"><div className="panelHeading"><div><h3>Operating branches</h3><p>Business branches can be activated or deactivated without deleting history.</p></div><MapPin size={16}/></div><div className="phase20RoleGrid">{localBranches.map(b=><article key={b.id}><strong>{b.name}</strong><span>{b.status}</span><small>{b.address||'No address'}</small></article>)}</div>{canBranches&&<div className="phase20Form"><input placeholder="Branch name" value={branchName} onChange={e=>setBranchName(e.target.value)}/><input placeholder="Address" value={branchAddress} onChange={e=>setBranchAddress(e.target.value)}/><button className="primaryAction" onClick={addBranch}><Plus size={15}/>Add branch</button></div>}</section></>}
 {tab==='Departments'&&<section className="panel phase20Panel"><div className="panelHeading"><div><h3>Departments</h3><p>Organizational structure and accountability.</p></div></div><div className="phase20RoleGrid">{localDepartments.map(d=><article key={d.id}><strong>{d.name}</strong><span>{d.code}</span><small>{d.manager_name||'No manager'} · {d.user_count??0} staff</small></article>)}</div>{canDepartments&&<div className="phase20Form"><input placeholder="Department name" value={deptName} onChange={e=>setDeptName(e.target.value)}/><input placeholder="Code" value={deptCode} onChange={e=>setDeptCode(e.target.value)}/><button className="primaryAction" onClick={addDepartment}><Plus size={15}/>Add department</button></div>}</section>}
 {tab==='Defaults'&&<section className="panel phase20Panel"><div className="panelHeading"><div><h3>Business defaults</h3><p>Only business-level configuration is exposed here.</p></div><SlidersHorizontal size={16}/></div><form className="phase20FormGrid" onSubmit={saveSettings}>{Object.entries(localSettings||{}).map(([k,v])=><label className="phase20Field" key={k}><span>{k.replaceAll('_',' ')}</span><input value={typeof v==='string'?v:JSON.stringify(v)} name={k} onChange={e=>setLocalSettings({...localSettings,[k]:e.target.value})}/></label>)}{canManage&&<button className="primaryAction" type="submit"><Save size={15}/>Save defaults</button>}</form></section>}
 </div>
}
