'use client';

import { useMemo, useState } from 'react';
import { Boxes, ClipboardCheck, ArrowRightLeft, PackagePlus, SlidersHorizontal, AlertTriangle, Warehouse, RefreshCw, Plus, Check, Truck, Search, X } from 'lucide-react';

type Any = any;

async function api(path: string, init: RequestInit = {}) {
  const response = await fetch(path.replace(/^\/api\/engine/, '/api'), { ...init, headers: { 'Content-Type': 'application/json', ...(init.headers || {}) } });
  const text = await response.text(); let payload: any = null; try { payload = text ? JSON.parse(text) : null; } catch { payload = text; }
  if (!response.ok) throw new Error(payload?.error || 'The inventory action could not be completed.');
  return payload;
}

function money(v: any) { const n = Number(v); return Number.isFinite(n) ? new Intl.NumberFormat('en-UG',{style:'currency',currency:'UGX',maximumFractionDigits:0}).format(n) : '—'; }
function num(v: any) { const n=Number(v); return Number.isFinite(n)?new Intl.NumberFormat('en-UG',{maximumFractionDigits:0}).format(n):'—'; }
function Modal({title,children,onClose,wide=false}:{title:string;children:any;onClose:()=>void;wide?:boolean}) { return <div className="adminModalBackdrop"><div className={`adminModal ${wide?'wide':''}`}><header><div><span className="eyebrow">Warehouse control</span><h3>{title}</h3></div><button className="iconButton" onClick={onClose}><X size={17}/></button></header>{children}</div></div> }
function Field({label,value,onChange,type='text',placeholder=''}:any){return <label className="adminField"><span>{label}</span><input type={type} value={value??''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Select({label,value,onChange,options}:any){return <label className="adminField"><span>{label}</span><select value={value??''} onChange={e=>onChange(e.target.value)}>{options.map((o:any)=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select></label>}

export function StockWorkspace({summary,locations,stock,movements,receipts,adjustments,transfers,stocktakes,incidents,variants,permissions}:{summary:Any;locations:Any[];stock:Any[];movements:Any[];receipts:Any[];adjustments:Any[];transfers:Any[];stocktakes:Any[];incidents:Any[];variants:Any[];permissions:string[]}) {
 const [tab,setTab]=useState('overview'); const [refresh,setRefresh]=useState(0); const [modal,setModal]=useState<string|null>(null); const [query,setQuery]=useState(''); const [location,setLocation]=useState('');
 const canManage=permissions.includes('inventory.manage'), canReceive=permissions.includes('inventory.receive'), canAdjust=permissions.includes('inventory.adjust'), canTransfer=permissions.includes('inventory.transfer'), canTake=permissions.includes('inventory.stocktake'), canIncidents=permissions.includes('inventory.incidents');
 const filtered=useMemo(()=>stock.filter(x=>!query || `${x.product_name} ${x.sku} ${x.location_name}`.toLowerCase().includes(query.toLowerCase())).filter(x=>!location||String(x.location_id)===location),[stock,query,location]);
 const low=filtered.filter(x=>Number(x.available)<=5 && Number(x.on_hand)>0);
 return <div className="workspace stockWorkspace" key={refresh}>
  <section className="welcome stockWelcome"><div><span className="eyebrow">Operations · Warehouse control</span><h2>Stock & Warehouses</h2><p>Control where stock is held, what is moving, what needs reconciliation and what requires action — using the existing inventory engine.</p></div><div className="workspaceActions"><button onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={14}/> Refresh</button></div></section>
  <section className="stockHeroGrid">
   <article className="stockHeroCard"><div className="stockHeroIcon"><Warehouse size={20}/></div><div><span>On-hand inventory</span><strong>{num(summary?.onHand)}</strong><small>Across {num(summary?.locations)} active locations</small></div></article>
   <article className="stockHeroCard"><div className="stockHeroIcon"><Boxes size={20}/></div><div><span>Available</span><strong>{num(Number(summary?.onHand||0)-Number(summary?.reserved||0))}</strong><small>{num(summary?.reserved)} units reserved</small></div></article>
   <article className="stockHeroCard alert"><div className="stockHeroIcon"><AlertTriangle size={20}/></div><div><span>Low-stock lines</span><strong>{num(summary?.lowStock)}</strong><small>Replenishment pressure</small></div></article>
   <article className="stockHeroCard"><div className="stockHeroIcon"><ArrowRightLeft size={20}/></div><div><span>Movements · 24h</span><strong>{num(summary?.movements24h)}</strong><small>Receipts, transfers & adjustments</small></div></article>
  </section>
  <section className="stockCommandBar"><div className="stockTabs">{[['overview','Overview'],['inventory','Inventory'],['warehouses','Warehouses'],['movements','Movements'],['controls','Controls']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div><div className="stockActions">{canReceive&&<button onClick={()=>setModal('receipt')}><PackagePlus size={14}/> Receive</button>}{canTransfer&&<button onClick={()=>setModal('transfer')}><ArrowRightLeft size={14}/> Transfer</button>}{canAdjust&&<button onClick={()=>setModal('adjustment')}><SlidersHorizontal size={14}/> Adjust</button>}{canTake&&<button onClick={()=>setModal('stocktake')}><ClipboardCheck size={14}/> Stocktake</button>}{canManage&&<button className="primaryAction" onClick={()=>setModal('warehouse')}><Plus size={14}/> Warehouse</button>}</div></section>
  {tab==='overview'&&<>
   <section className="stockOverviewGrid"><div className="panel"><div className="panelHeading"><div><h3>Warehouse network</h3><p>Operational capacity by active location.</p></div></div><div className="warehouseCards">{locations.map(l=><article key={l.id}><div className="warehouseTop"><Warehouse size={16}/><span className="catalogStatus">{l.status}</span></div><strong>{l.name}</strong><small>{l.code} · {l.type}</small><div className="warehouseStats"><span><b>{num(l.total_units)}</b> units</span><span><b>{num(l.sku_count)}</b> SKUs</span></div></article>)}{!locations.length&&<div className="emptyState">No active warehouse locations are available.</div>}</div></div>
   <div className="panel"><div className="panelHeading"><div><h3>Attention centre</h3><p>Issues that need a warehouse operator.</p></div></div><div className="attentionList">{low.slice(0,8).map(x=><div key={x.id}><AlertTriangle size={15}/><div><strong>{x.product_name}</strong><span>{x.sku} · {x.location_name}</span></div><b>{num(x.available)}</b></div>)}{incidents.filter(x=>x.status==='Open').slice(0,4).map(x=><div key={'i'+x.id}><AlertTriangle size={15}/><div><strong>{x.incident_type} · {x.product_name}</strong><span>{x.location_name} · {x.reason}</span></div><b>Open</b></div>)}{!low.length&&!incidents.some(x=>x.status==='Open')&&<div className="emptyState">Warehouse operations are clear.</div>}</div></div></section>
   <section className="panel"><div className="panelHeading"><div><h3>Recent stock movement</h3><p>Traceable inventory activity from the authoritative engine.</p></div><button className="textAction" onClick={()=>setTab('movements')}>View all</button></div><div className="tableWrap"><table><thead><tr><th>Time</th><th>Product</th><th>Location</th><th>Movement</th><th>Quantity</th><th>After</th></tr></thead><tbody>{movements.slice(0,12).map(m=><tr key={m.id}><td>{new Date(m.created_at).toLocaleString()}</td><td><strong>{m.product_name}</strong><small>{m.sku}</small></td><td>{m.location_name}</td><td><span className="catalogStatus">{m.movement_type||m.type}</span></td><td>{num(m.quantity??m.delta)}</td><td>{num(m.after_qty)}</td></tr>)}{!movements.length&&<tr><td colSpan={6}><div className="emptyState">No movements recorded.</div></td></tr>}</tbody></table></div></section>
  </>}
  {tab==='inventory'&&<section className="panel"><div className="stockFilterBar"><div className="stockSearch"><Search size={15}/><input placeholder="Search product, SKU or warehouse" value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={location} onChange={e=>setLocation(e.target.value)}><option value="">All warehouses</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><button onClick={()=>{setQuery('');setLocation('')}}>Clear</button></div><div className="tableWrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Warehouse</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Value</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><strong>{x.product_name}</strong><small>{x.variant_name||'Default'}</small></td><td>{x.sku}</td><td>{x.location_name}</td><td>{num(x.on_hand)}</td><td>{num(x.reserved)}</td><td><b className={Number(x.available)<=5?'dangerText':''}>{num(x.available)}</b></td><td>{money(Number(x.on_hand||0)*Number(x.cost_price||0))}</td></tr>)}{!filtered.length&&<tr><td colSpan={7}><div className="emptyState">No inventory matches your filters.</div></td></tr>}</tbody></table></div></section>}
  {tab==='warehouses'&&<section className="panel"><div className="panelHeading"><div><h3>Warehouse directory</h3><p>Manage the physical locations that own stock.</p></div></div><div className="warehouseCards warehouseDirectory">{locations.map(l=><article key={l.id}><div className="warehouseTop"><Warehouse size={18}/><span className="catalogStatus">{l.status}</span></div><strong>{l.name}</strong><small>{l.code} · {l.type}</small><p>{l.address||'No address recorded'}</p><div className="warehouseStats"><span><b>{num(l.total_units)}</b> units</span><span><b>{num(l.sku_count)}</b> SKUs</span></div>{canManage&&<button className="softAction" onClick={()=>setModal('editWarehouse:'+l.id)}>Edit location</button>}</article>)}</div></section>}
  {tab==='movements'&&<section className="panel"><div className="panelHeading"><div><h3>Inventory ledger</h3><p>Every stock movement should have a business reason and traceable actor.</p></div></div><div className="tableWrap"><table><thead><tr><th>Date</th><th>Product</th><th>Location</th><th>Type</th><th>Before</th><th>Change</th><th>After</th><th>Actor</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{new Date(m.created_at).toLocaleString()}</td><td>{m.product_name}<small>{m.sku}</small></td><td>{m.location_name}</td><td>{m.movement_type||m.type}</td><td>{num(m.before_qty)}</td><td>{num(m.quantity??m.delta)}</td><td>{num(m.after_qty)}</td><td>{m.actor_email||'—'}</td></tr>)}</tbody></table></div></section>}
  {tab==='controls'&&<section className="stockControlGrid"><Control title="Receipts" icon={<PackagePlus/>} rows={receipts} columns={['receipt_no','location_name','supplier_name','units']} /><Control title="Transfers" icon={<ArrowRightLeft/>} rows={transfers} columns={['transfer_no','from_location_name','to_location_name','status']} /><Control title="Adjustments" icon={<SlidersHorizontal/>} rows={adjustments} columns={['adjustment_no','location_name','reason','net_change']} /><Control title="Stocktakes" icon={<ClipboardCheck/>} rows={stocktakes} columns={['stocktake_no','location_name','status','line_count']} /><Control title="Incidents" icon={<AlertTriangle/>} rows={incidents} columns={['incident_no','incident_type','product_name','status']} /></section>}
  {modal==='warehouse'&&<WarehouseModal locations={locations} onClose={()=>setModal(null)} onDone={()=>{setModal(null);setRefresh(x=>x+1)}} />}
  {modal?.startsWith('editWarehouse:')&&<WarehouseModal initial={locations.find(x=>String(x.id)===modal.split(':')[1])} locations={locations} onClose={()=>setModal(null)} onDone={()=>{setModal(null);setRefresh(x=>x+1)}}/>}
  {modal==='receipt'&&<ReceiptModal locations={locations} variants={variants} onClose={()=>setModal(null)} onDone={()=>{setModal(null);setRefresh(x=>x+1)}}/>}
  {modal==='adjustment'&&<AdjustmentModal locations={locations} variants={variants} onClose={()=>setModal(null)} onDone={()=>{setModal(null);setRefresh(x=>x+1)}}/>}
  {modal==='transfer'&&<TransferModal locations={locations} variants={variants} onClose={()=>setModal(null)} onDone={()=>{setModal(null);setRefresh(x=>x+1)}}/>}
  {modal==='stocktake'&&<StocktakeModal locations={locations} onClose={()=>setModal(null)} onDone={()=>{setModal(null);setRefresh(x=>x+1)}}/>}
 </div>
}
function Control({title,icon,rows,columns}:any){return <div className="panel stockControlPanel"><div className="panelHeading"><div><h3>{icon}{title}</h3><p>{rows.length} records</p></div></div>{rows.slice(0,6).map((r:any)=><div className="miniRow" key={r.id}><div><strong>{r[columns[0]]||'—'}</strong><span>{r[columns[1]]||'—'}</span></div><b>{r[columns[2]]||'—'}</b><small>{r[columns[3]]??'—'}</small></div>)}{!rows.length&&<div className="emptyState">No records.</div>}</div>}

function WarehouseModal({initial,onClose,onDone}:any){const [f,setF]=useState<any>({name:initial?.name||'',code:initial?.code||'',type:initial?.type||'Warehouse',address:initial?.address||'',notes:initial?.notes||'',status:initial?.status||'Active'});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const set=(k:string,v:any)=>setF({...f,[k]:v});async function submit(e:any){e.preventDefault();setBusy(true);try{await api(initial?`/api/inventory/locations/${initial.id}`:'/api/inventory/locations',{method:initial?'PATCH':'POST',body:JSON.stringify(f)});onDone()}catch(e:any){setError(e.message)}finally{setBusy(false)}}return <Modal title={initial?'Edit warehouse':'Add warehouse'} onClose={onClose}><form onSubmit={submit}><Field label="Warehouse name *" value={f.name} onChange={(v:any)=>set('name',v)}/><Field label="Code *" value={f.code} onChange={(v:any)=>set('code',v)} placeholder="e.g. KLA01"/><Select label="Type" value={f.type} onChange={(v:any)=>set('type',v)} options={['Warehouse','Branch','Store','Transit']}/><Select label="Status" value={f.status} onChange={(v:any)=>set('status',v)} options={['Active','Inactive']}/><Field label="Address" value={f.address} onChange={(v:any)=>set('address',v)}/><Field label="Notes" value={f.notes} onChange={(v:any)=>set('notes',v)}/>{error&&<div className="adminError">{error}</div>}<div className="adminSubmit"><button className="primaryAction" disabled={busy}>{busy?'Saving…':'Save warehouse'}</button></div></form></Modal>}
function LineEditor({variants,lines,setLines,mode='standard'}:any){return <div className="lineEditor">{lines.map((l:any,i:number)=><div className="lineEditorRow" key={i}><Select label="Product / SKU" value={l.variantId} onChange={(v:any)=>{const a=[...lines];a[i]={...a[i],variantId:v};setLines(a)}} options={[{value:'',label:'Select SKU'},...variants.map((v:any)=>({value:v.id,label:`${v.product_name} · ${v.sku}`}))]}/><Field label={mode==='adjustment'?'Quantity change':'Quantity'} type="number" value={mode==='adjustment'?l.quantityChange:l.quantity} onChange={(v:any)=>{const a=[...lines];a[i]={...a[i],...(mode==='adjustment'?{quantityChange:v}:{quantity:v})};setLines(a)}}/><Field label="Unit cost" type="number" value={l.unitCost} onChange={(v:any)=>{const a=[...lines];a[i]={...a[i],unitCost:v};setLines(a)}}/><button className="iconButton" type="button" onClick={()=>setLines(lines.filter((_:any,j:number)=>j!==i))}><X size={14}/></button></div>)}<button className="softAction" type="button" onClick={()=>setLines([...lines,{variantId:'',quantity:1,unitCost:''}])}><Plus size={14}/> Add line</button></div>}
function ReceiptModal({locations,variants,onClose,onDone}:any){const [locationId,setLocationId]=useState(locations[0]?.id||'');const [supplierName,setSupplierName]=useState('');const [supplierReference,setSupplierReference]=useState('');const [notes,setNotes]=useState('');const [lines,setLines]=useState<any[]>([{variantId:'',quantity:1,unitCost:''}]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:any){e.preventDefault();setBusy(true);try{await api('/api/inventory/receipts',{method:'POST',body:JSON.stringify({locationId,supplierName,supplierReference,notes,lines})});onDone()}catch(e:any){setError(e.message)}finally{setBusy(false)}}return <Modal title="Receive goods" onClose={onClose} wide><form onSubmit={submit}><div className="adminFormGrid"><Select label="Receiving warehouse" value={locationId} onChange={setLocationId} options={locations.map((x:any)=>({value:x.id,label:x.name}))}/><Field label="Supplier" value={supplierName} onChange={setSupplierName}/><Field label="Supplier reference" value={supplierReference} onChange={setSupplierReference}/><Field label="Notes" value={notes} onChange={setNotes}/></div><LineEditor variants={variants} lines={lines} setLines={setLines}/>{error&&<div className="adminError">{error}</div>}<div className="adminSubmit"><button className="primaryAction" disabled={busy}>{busy?'Receiving…':'Post goods receipt'}</button></div></form></Modal>}
function AdjustmentModal({locations,variants,onClose,onDone}:any){const [locationId,setLocationId]=useState(locations[0]?.id||'');const [reason,setReason]=useState('');const [lines,setLines]=useState<any[]>([{variantId:'',quantityChange:1,unitCost:''}]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:any){e.preventDefault();setBusy(true);try{await api('/api/inventory/adjustments',{method:'POST',body:JSON.stringify({locationId,reason,lines:lines.map(x=>({...x,quantityChange:Number(x.quantityChange),unitCost:x.unitCost===''?undefined:Number(x.unitCost)}))})});onDone()}catch(e:any){setError(e.message)}finally{setBusy(false)}}return <Modal title="Adjust stock" onClose={onClose} wide><form onSubmit={submit}><div className="adminFormGrid"><Select label="Warehouse" value={locationId} onChange={setLocationId} options={locations.map((x:any)=>({value:x.id,label:x.name}))}/><Field label="Reason *" value={reason} onChange={setReason} placeholder="Count correction, damage, etc."/></div><LineEditor variants={variants} lines={lines} setLines={setLines} mode="adjustment"/><p className="adminHint">Use positive quantities for stock in and negative quantities for stock out. The engine validates availability and serialized units.</p>{error&&<div className="adminError">{error}</div>}<div className="adminSubmit"><button className="primaryAction" disabled={busy}>{busy?'Saving…':'Post adjustment'}</button></div></form></Modal>}
function TransferModal({locations,variants,onClose,onDone}:any){const [fromLocationId,setFrom]=useState(locations[0]?.id||'');const [toLocationId,setTo]=useState(locations[1]?.id||locations[0]?.id||'');const [notes,setNotes]=useState('');const [lines,setLines]=useState<any[]>([{variantId:'',quantity:1,unitCost:''}]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:any){e.preventDefault();setBusy(true);try{await api('/api/inventory/transfers',{method:'POST',body:JSON.stringify({fromLocationId,toLocationId,notes,lines})});onDone()}catch(e:any){setError(e.message)}finally{setBusy(false)}}return <Modal title="Request stock transfer" onClose={onClose} wide><form onSubmit={submit}><div className="adminFormGrid"><Select label="From warehouse" value={fromLocationId} onChange={setFrom} options={locations.map((x:any)=>({value:x.id,label:x.name}))}/><Select label="To warehouse" value={toLocationId} onChange={setTo} options={locations.map((x:any)=>({value:x.id,label:x.name}))}/><Field label="Notes" value={notes} onChange={setNotes}/></div><LineEditor variants={variants} lines={lines} setLines={setLines}/>{error&&<div className="adminError">{error}</div>}<div className="adminSubmit"><button className="primaryAction" disabled={busy}>{busy?'Submitting…':'Submit transfer'}</button></div></form></Modal>}
function StocktakeModal({locations,onClose,onDone}:any){const [locationId,setLocationId]=useState(locations[0]?.id||'');const [notes,setNotes]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:any){e.preventDefault();setBusy(true);try{await api('/api/inventory/stocktakes',{method:'POST',body:JSON.stringify({locationId,notes})});onDone()}catch(e:any){setError(e.message)}finally{setBusy(false)}}return <Modal title="Start stocktake" onClose={onClose}><form onSubmit={submit}><Select label="Warehouse" value={locationId} onChange={setLocationId} options={locations.map((x:any)=>({value:x.id,label:x.name}))}/><Field label="Notes" value={notes} onChange={setNotes}/><p className="adminHint">The existing engine will snapshot non-serialized and serialized stock for this location. Counting and finalization remain governed by its stocktake workflow.</p>{error&&<div className="adminError">{error}</div>}<div className="adminSubmit"><button className="primaryAction" disabled={busy}>{busy?'Starting…':'Start stocktake'}</button></div></form></Modal>}
