'use client';
import { useState } from 'react';
import { Plus,Save,UserPlus,Shield,UserCheck,UserX } from 'lucide-react';
async function api(path:string,options?:RequestInit){const r=await fetch(path,options);const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||'Request failed');return p}
export function TeamWorkspace({staff,roles,permissions,invitations,canManage,canRoles,isSuperAdmin}:{staff:any[];roles:any[];permissions:any[];invitations:any[];canManage:boolean;canRoles:boolean;isSuperAdmin:boolean}){
 const [tab,setTab]=useState('Staff'),[localStaff,setStaff]=useState(staff),[localRoles,setRoles]=useState(roles),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[roleId,setRoleId]=useState(roles.find(r=>r.name==='Manager')?.id||roles[0]?.id||''),[roleName,setRoleName]=useState(''),[roleDesc,setRoleDesc]=useState(''),[selectedPerms,setSelectedPerms]=useState<string[]>([]),[message,setMessage]=useState('');
 async function createStaff(){try{const u=await api('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,password,roleId})});setStaff([u,...localStaff]);setName('');setEmail('');setPassword('');setMessage('Staff account created.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to create staff')}}
 async function createRole(){try{const r=await api('/api/roles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:roleName,description:roleDesc,permissions:selectedPerms})});setRoles([...localRoles,{...r,permissions:selectedPerms}]);setRoleName('');setRoleDesc('');setSelectedPerms([]);setMessage('Custom role created.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to create role')}}
 async function toggleStatus(u:any){try{const next=u.status==='Active'?'Suspended':'Active';const r=await api(`/api/users/${u.id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:next})});setStaff(localStaff.map(x=>x.id===u.id?{...x,...r}:x));setMessage(`Account ${next.toLowerCase()}.`)}catch(e){setMessage(e instanceof Error?e.message:'Unable to update account')}}
 return <div className="phase20Workspace"><section className="phase20Hero"><div><span className="eyebrow">People & access</span><h2>Team, roles and access control.</h2><p>Manage staff, custom roles and granular permissions without exposing technical administration.</p></div><span className="phase20Pill"><Shield size={14}/> {isSuperAdmin?'Super Admin':'Administrator'}</span></section>{message&&<div className="phase20Notice"><UserCheck size={15}/>{message}</div>}<div className="phase20Tabs">{['Staff','Roles','Invitations'].map(x=><button className={tab===x?'active':''} key={x} onClick={()=>setTab(x)}>{x}</button>)}</div>
 {tab==='Staff'&&<><section className="panel phase20Panel"><div className="panelHeading"><div><h3>Create staff</h3><p>Every new account must receive at least one role.</p></div><UserPlus size={16}/></div>{canManage&&<div className="phase20Form"><input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Temporary password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><select value={roleId} onChange={e=>setRoleId(e.target.value)}>{localRoles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button className="primaryAction" onClick={createStaff}><Plus size={15}/>Create account</button></div>}</section><section className="panel phase20Panel"><div className="panelHeading"><div><h3>Staff directory</h3><p>{localStaff.length} active records loaded.</p></div></div><div className="tableWrap"><table><thead><tr><th>Name</th><th>Email</th><th>Roles</th><th>Status</th><th>Action</th></tr></thead><tbody>{localStaff.map(u=><tr key={u.id}><td><strong>{u.name}</strong></td><td>{u.email}</td><td>{Array.isArray(u.roles)?u.roles.join(', '):'—'}</td><td>{u.status}</td><td>{canManage&&<button className="textAction" onClick={()=>toggleStatus(u)}>{u.status==='Active'?<UserX size={13}/>:<UserCheck size={13}/>} {u.status==='Active'?'Suspend':'Activate'}</button>}</td></tr>)}</tbody></table></div></section></>}
 {tab==='Roles'&&<><section className="panel phase20Panel"><div className="panelHeading"><div><h3>Role catalogue</h3><p>System roles are protected; custom roles are editable.</p></div><Shield size={16}/></div><div className="phase20RoleGrid">{localRoles.map(r=><article key={r.id}><strong>{r.name}</strong><span>{r.system?'System role':'Custom role'}</span><small>{Array.isArray(r.permissions)?r.permissions.length:0} permissions</small></article>)}</div></section>{canRoles&&<section className="panel phase20Panel"><div className="panelHeading"><div><h3>Create custom role</h3><p>Grant only the capabilities the role needs.</p></div><Plus size={16}/></div><div className="phase20Form"><input placeholder="Role name" value={roleName} onChange={e=>setRoleName(e.target.value)}/><input placeholder="Description" value={roleDesc} onChange={e=>setRoleDesc(e.target.value)}/><div className="phase20PermissionGrid">{permissions.map(p=><label key={p.id}><input type="checkbox" checked={selectedPerms.includes(p.id)} onChange={e=>setSelectedPerms(x=>e.target.checked?[...x,p.id]:x.filter(y=>y!==p.id))}/>{p.id}</label>)}</div><button className="primaryAction" onClick={createRole}><Save size={15}/>Create role</button></div></section>}</>}
 {tab==='Invitations'&&<section className="panel phase20Panel"><div className="panelHeading"><div><h3>Invitations</h3><p>Invitation lifecycle and expiry status.</p></div></div><div className="tableWrap"><table><thead><tr><th>Email</th><th>Name</th><th>Role</th><th>Status</th><th>Expires</th></tr></thead><tbody>{invitations.map(i=><tr key={i.id}><td>{i.email}</td><td>{i.name}</td><td>{i.role_name||'—'}</td><td>{i.status}</td><td>{String(i.expires_at).slice(0,10)}</td></tr>)}</tbody></table></div></section>}
 </div>
}
