'use client';
import { useEffect, useMemo, useState } from 'react';
import { Globe2, ImagePlus, LayoutList, Megaphone, Menu, Plus, RefreshCw, Search, Settings2, ShieldCheck, Send, X, ExternalLink, ChevronRight } from 'lucide-react';

type Any = any;
const api=async(path:string,init:RequestInit={})=>{const r=await fetch(path,{...init,headers:{'Content-Type':'application/json',...(init.headers||{})}});const t=await r.text();let d:Any=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.error||'The action could not be completed.');return d};
const fmt=(v:Any)=>v==null||v===''?'—':String(v);
function Modal({title,children,onClose,wide=false}:{title:string;children:any;onClose:()=>void;wide?:boolean}){return <div className="adminModalBackdrop"><div className={`adminModal ${wide?'wide':''}`}><header><div><span className="eyebrow">Website</span><h3>{title}</h3></div><button className="iconButton" onClick={onClose}><X size={17}/></button></header>{children}</div></div>}
function Field({label,value,onChange,type='text',placeholder=''}:Any){return <label className="adminField"><span>{label}</span><input type={type} value={value??''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Textarea({label,value,onChange,placeholder=''}:Any){return <label className="adminField"><span>{label}</span><textarea value={value??''} onChange={e=>onChange(e.target.value)} placeholder={placeholder} rows={5}/></label>}
function Select({label,value,onChange,options}:Any){return <label className="adminField"><span>{label}</span><select value={value??''} onChange={e=>onChange(e.target.value)}>{options.map((o:Any)=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select></label>}
function Table({rows,columns,onRow}:{rows:Any[];columns:[string,string][];onRow?:(r:Any)=>void}){return <div className="tableWrap"><table><thead><tr>{columns.map(([k,l])=><th key={k}>{l}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i} onClick={()=>onRow?.(r)} style={onRow?{cursor:'pointer'}:undefined}>{columns.map(([k])=><td key={k}>{k==='status'?<span className="catalogStatus">{fmt(r[k])}</span>:fmt(r[k])}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={columns.length}><div className="emptyState">Nothing has been added yet.</div></td></tr>}</tbody></table></div>}

export function WebsiteWorkspace({sites,permissions}:{sites:Any[];permissions:string[]}){
 const [site,setSite]=useState<Any>(sites[0]||null),[tab,setTab]=useState('overview'),[modal,setModal]=useState<string|null>(null),[selected,setSelected]=useState<Any>(null),[data,setData]=useState<Any>({}),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const canManage=permissions.includes('web.manage'),canMedia=permissions.includes('web.media'),canDomains=permissions.includes('web.domains'),canRequest=permissions.includes('web.publish.request'),canApprove=permissions.includes('web.publish.approve'),canExecute=permissions.includes('web.publish.execute');
 const load=async(nextSite=site,nextTab=tab)=>{if(!nextSite)return;setBusy(true);setError('');try{const id=encodeURIComponent(nextSite.id);const [pages,navigation,banners,blocks,media,domains,redirects,settings,requests,releases,health,storefront]=await Promise.all([api(`/api/web/pages?siteId=${id}`),api(`/api/web/navigation?siteId=${id}`),api(`/api/web/banners?siteId=${id}`),api(`/api/web/content-blocks?siteId=${id}`),api(`/api/web/media?siteId=${id}`),canDomains?api(`/api/web/domains?siteId=${id}`):Promise.resolve([]),api(`/api/web/redirects?siteId=${id}`),api(`/api/web/settings?siteId=${id}`),canApprove?api(`/api/web/publish-requests?siteId=${id}`):Promise.resolve([]),api(`/api/web/releases?siteId=${id}`),api(`/api/web/hosting/health?siteId=${id}`),api('/api/catalog/products?limit=300')]);setData({pages,navigation,banners,blocks,media,domains,redirects,settings,requests,releases,health,storefront});}catch(e:Any){setError(e.message||'Could not load website information.')}finally{setBusy(false)}};
 useEffect(()=>{if(site) load(site,'overview')},[]);
 const choose=(s:Any)=>{setSite(s);setTab('overview');load(s,'overview')};
 const run=async(fn:()=>Promise<any>)=>{setBusy(true);setError('');try{await fn();setModal(null);setSelected(null);await load()}catch(e:Any){setError(e.message||'The action could not be completed.')}finally{setBusy(false)}};
 const filtered=(data[tab==='pages'?'pages':tab==='navigation'?'navigation':tab==='banners'?'banners':tab==='blocks'?'blocks':tab==='media'?'media':tab==='domains'?'domains':tab==='redirects'?'redirects':tab==='publishing'?'requests':[]]||[]).filter((x:Any)=>!query||JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));
 const counts={pages:(data.pages||[]).filter((x:Any)=>x.status==='Published').length,media:(data.media||[]).filter((x:Any)=>x.status==='Published').length,pending:(data.requests||[]).filter((x:Any)=>x.status==='Pending').length};
 return <div className="workspace websiteWorkspace">
  <section className="welcome"><div><span className="eyebrow">Business website</span><h2>Website Management</h2><p>Keep the public storefront, content and promotions current without exposing hosting administration.</p></div><div className="workspaceActions"><button className="softAction" onClick={()=>load()}><RefreshCw size={14}/> Refresh</button>{canManage&&<><button onClick={()=>setModal('site')}><Plus size={14}/> Add website</button>{site&&<button onClick={()=>setModal('siteEdit')}>Edit website</button>}</>}</div></section>
  {sites.length>0&&<section className="websiteSiteBar"><div className="websiteSitePicker"><Globe2 size={16}/><select value={site?.id||''} onChange={e=>choose(sites.find((s:any)=>s.id===e.target.value))}>{sites.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="websiteStatus"><span className={site?.status==='Active'?'ok':''}>{site?.status||'—'}</span><small>{site?.primary_domain||'No primary domain'}</small></div></section>}
  {!site?<section className="panel websiteEmpty"><Globe2 size={28}/><h3>No website connected yet</h3><p>Add the first business website to begin managing pages, menus, media and publishing.</p>{canManage&&<button className="primaryAction" onClick={()=>setModal('site')}><Plus size={14}/> Add website</button>}</section>:<>
   <section className="stockHeroGrid websiteKpis"><article className="stockHeroCard"><div className="stockHeroIcon"><LayoutList size={19}/></div><div><span>Published pages</span><strong>{counts.pages}</strong><small>{(data.pages||[]).length} total pages</small></div></article><article className="stockHeroCard"><div className="stockHeroIcon"><ImagePlus size={19}/></div><div><span>Published media</span><strong>{counts.media}</strong><small>{(data.media||[]).length} media items</small></div></article><article className="stockHeroCard"><div className="stockHeroIcon"><Megaphone size={19}/></div><div><span>Pending publishing</span><strong>{counts.pending}</strong><small>Items awaiting review</small></div></article><article className="stockHeroCard"><div className="stockHeroIcon"><ShieldCheck size={19}/></div><div><span>Latest release</span><strong>{fmt(data.releases?.[0]?.status)}</strong><small>{fmt(data.releases?.[0]?.release_name)}</small></div></article></section>
   <section className="stockCommandBar"><div className="stockTabs">{[['overview','Overview'],['pages','Pages'],['navigation','Menus'],['banners','Banners'],['blocks','Content'],['media','Media'],['publishing','Publishing'],['domains','Domains'],['redirects','Redirects'],['storefront','Storefront'],['settings','Website settings']].map(([id,l])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setQuery('');load(site,id)}}>{l}</button>)}</div><div className="stockActions">{tab==='pages'&&canManage&&<button onClick={()=>setModal('page')}><Plus size={14}/> New page</button>}{tab==='navigation'&&canManage&&<button onClick={()=>setModal('navigation')}><Plus size={14}/> Add menu item</button>}{tab==='banners'&&canManage&&<button onClick={()=>setModal('banner')}><Plus size={14}/> Add banner</button>}{tab==='blocks'&&canManage&&<button onClick={()=>setModal('block')}><Plus size={14}/> Add content</button>}{tab==='media'&&canMedia&&<button onClick={()=>setModal('media')}><Plus size={14}/> Add image</button>}{tab==='domains'&&canDomains&&<button onClick={()=>setModal('domain')}><Plus size={14}/> Add domain</button>}{tab==='redirects'&&canManage&&<button onClick={()=>setModal('redirect')}><Plus size={14}/> Add redirect</button>}{tab==='publishing'&&canRequest&&<button className="primaryAction" onClick={()=>setModal('release')}><Send size={14}/> Create release</button>}</div></section>
   {tab!=='overview'&&tab!=='settings'&&<div className="stockFilterBar"><div className="stockSearch"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this section"/></div></div>}
   {error&&<div className="adminError">{error}</div>}
   {tab==='overview'&&<Overview data={data} site={site} onTab={(x:string)=>{setTab(x);load(site,x)}}/>}
   {tab==='storefront'&&<section className="panel"><div className="panelHeading"><div><h3>Storefront catalogue</h3><p>See which existing products are ready to appear on the public website. Product details and stock remain managed in their business workspaces.</p></div></div><Table rows={(data.storefront?.rows||data.storefront||[]).filter((x:Any)=>!query||JSON.stringify(x).toLowerCase().includes(query.toLowerCase()))} columns={[[ 'name','Product'],['brand_name','Brand'],['category_name','Category'],['website_visibility','Website visibility'],['status','Status'],['min_price','From']]} /></section>}
   {tab==='settings'&&<SettingsPanel site={site} settings={data.settings||{}} canManage={canManage} onSave={(settings:any)=>run(()=>api('/api/web/settings',{method:'PUT',body:JSON.stringify({siteId:site.id,settings})}))}/>} 
   {tab==='pages'&&<section className="panel"><div className="panelHeading"><div><h3>Website pages</h3><p>Create and maintain business-facing pages. Publishing follows the review process.</p></div></div><Table rows={filtered} columns={[[ 'title','Page'],['slug','Address'],['template','Layout'],['status','Status'],['version','Version'],['updated_at','Last updated']]} onRow={(r)=>{setSelected(r);setModal('pageEdit')}}/></section>}
   {tab==='navigation'&&<section className="panel"><div className="panelHeading"><div><h3>Menus & links</h3><p>Organise the customer-facing navigation.</p></div></div><Table rows={filtered} columns={[[ 'menu_key','Menu'],['label','Label'],['url','Link'],['sort_order','Order'],['enabled','Visible']]} onRow={(r)=>{setSelected(r);setModal('navigationEdit')}}/></section>}
   {tab==='banners'&&<section className="panel"><div className="panelHeading"><div><h3>Promotional banners</h3><p>Manage homepage and campaign placements.</p></div></div><Table rows={filtered} columns={[[ 'title','Banner'],['placement','Placement'],['status','Status'],['starts_at','Starts'],['ends_at','Ends'],['sort_order','Order']]} onRow={(r)=>{setSelected(r);setModal('bannerDetail')}}/></section>}
   {tab==='blocks'&&<section className="panel"><div className="panelHeading"><div><h3>Content areas</h3><p>Reusable business content shown across the public website.</p></div></div><Table rows={filtered} columns={[[ 'key','Area'],['title','Title'],['status','Status'],['version','Version'],['updated_at','Updated']]} onRow={(r)=>{setSelected(r);setModal('blockEdit')}}/></section>}
   {tab==='media'&&<section className="panel"><div className="panelHeading"><div><h3>Media library</h3><p>Approved images for the public website. Maximum image size is 5 MB.</p></div></div><Table rows={filtered} columns={[[ 'filename','File'],['mime_type','Type'],['size_bytes','Size'],['alt_text','Description'],['status','Status'],['created_at','Added']]} onRow={(r)=>{setSelected(r);setModal('mediaEdit')}}/></section>}
   {tab==='publishing'&&<section className="panel"><div className="panelHeading"><div><h3>Publishing desk</h3><p>Review requests and manage website releases.</p></div></div><Table rows={filtered} columns={[[ 'resource_type','Item'],['action','Action'],['status','Status'],['requester','Requested by'],['created_at','Requested']]} onRow={(r)=>{setSelected(r);setModal('publishRequest')}}/><div className="panelHeading" style={{marginTop:18}}><div><h3>Release history</h3><p>Previous release records.</p></div></div><Table rows={data.releases||[]} columns={[[ 'release_name','Release'],['environment','Area'],['status','Status'],['created_at','Created'],['published_at','Published']]} onRow={(r)=>{setSelected(r);setModal('releaseDetail')}}/></section>}
   {tab==='domains'&&<section className="panel"><div className="panelHeading"><div><h3>Website addresses</h3><p>View business domains and their verification status. Domain connection is completed by the hosting provider.</p></div></div><Table rows={filtered} columns={[[ 'hostname','Address'],['type','Type'],['status','Status'],['ssl_status','Security'],['verified_at','Verified']]} /></section>}
   {tab==='redirects'&&<section className="panel"><div className="panelHeading"><div><h3>Redirects</h3><p>Keep old customer-facing addresses pointing to the right place.</p></div></div><Table rows={filtered} columns={[[ 'source_path','From'],['destination_url','To'],['status_code','Code'],['enabled','Enabled']]} /></section>}
  </>}
  {modal==='siteEdit'&&site&&<SiteEdit site={site} onClose={()=>setModal(null)} onSave={(f:any)=>run(()=>api(`/api/web/sites/${site.id}`,{method:'PATCH',body:JSON.stringify(f)}))}/>}
  {modal==='site'&&<SiteForm onClose={()=>setModal(null)} onSave={(f:any)=>run(()=>api('/api/web/sites',{method:'POST',body:JSON.stringify(f)}).then(()=>load()))}/>} 
  {modal==='page'&&<PageForm siteId={site.id} onClose={()=>setModal(null)} onSave={(f:any)=>run(()=>api('/api/web/pages',{method:'POST',body:JSON.stringify(f)}))}/>} 
  {modal==='pageEdit'&&selected&&<PageEdit page={selected} onClose={()=>setModal(null)} onSave={(f:any)=>run(()=>api(`/api/web/pages/${selected.id}`,{method:'PATCH',body:JSON.stringify(f)}))} onPublish={canRequest?(action:string)=>run(()=>api('/api/web/publish-requests',{method:'POST',body:JSON.stringify({siteId:site.id,resourceType:'web_pages',resourceId:selected.id,action})})):undefined}/>} 
  {modal==='navigation'&&<NavigationForm siteId={site.id} onClose={()=>setModal(null)} onSave={(f:any)=>run(()=>api('/api/web/navigation',{method:'POST',body:JSON.stringify(f)}))}/>} 
  {modal==='navigationEdit'&&selected&&<NavigationEdit item={selected} onClose={()=>setModal(null)} onSave={(f:any)=>run(()=>api(`/api/web/navigation/${selected.id}`,{method:'PATCH',body:JSON.stringify(f)}))}/>} 
  {modal==='banner'&&<BannerForm siteId={site.id} onClose={()=>setModal(null)} onSave={(f:any)=>run(()=>api('/api/web/banners',{method:'POST',body:JSON.stringify(f)}))}/>} 
  {modal==='bannerDetail'&&selected&&<BannerDetail item={selected} canRequest={canRequest} onClose={()=>setModal(null)} onPublish={()=>run(()=>api('/api/web/publish-requests',{method:'POST',body:JSON.stringify({siteId:site.id,resourceType:'web_banners',resourceId:selected.id,action:'publish'})}))}/>}
  {modal==='block'&&<BlockForm siteId={site.id} onClose={()=>setModal(null)} onSave={(f:any)=>run(()=>api('/api/web/content-blocks',{method:'POST',body:JSON.stringify(f)}))}/>} 
  {modal==='blockEdit'&&selected&&<BlockEdit item={selected} onClose={()=>setModal(null)} onSave={(f:any)=>run(()=>api(`/api/web/content-blocks/${selected.id}`,{method:'PATCH',body:JSON.stringify(f)}))} onPublish={canRequest?(action:string)=>run(()=>api('/api/web/publish-requests',{method:'POST',body:JSON.stringify({siteId:site.id,resourceType:'web_content_blocks',resourceId:selected.id,action})})):undefined}/>} 
  {modal==='media'&&<MediaForm siteId={site.id} onClose={()=>setModal(null)} onSave={(f:any)=>run(()=>api('/api/web/media',{method:'POST',body:JSON.stringify(f)}))}/>} 
  {modal==='mediaEdit'&&selected&&<MediaEdit item={selected} canMedia={canMedia} onClose={()=>setModal(null)} onPublish={canRequest?(action:string)=>run(()=>api('/api/web/publish-requests',{method:'POST',body:JSON.stringify({siteId:site.id,resourceType:'web_media',resourceId:selected.id,action})})):undefined} onStatus={(status:string)=>run(()=>api(`/api/web/media/${selected.id}/status`,{method:'PATCH',body:JSON.stringify({status})}))}/>} 
  {modal==='domain'&&<DomainForm siteId={site.id} onClose={()=>setModal(null)} onSave={(f:any)=>run(()=>api('/api/web/domains',{method:'POST',body:JSON.stringify(f)}))}/>} 
  {modal==='redirect'&&<RedirectForm siteId={site.id} onClose={()=>setModal(null)} onSave={(f:any)=>run(()=>api('/api/web/redirects',{method:'POST',body:JSON.stringify(f)}))}/>} 
  {modal==='release'&&<ReleaseForm siteId={site.id} onClose={()=>setModal(null)} onSave={(f:any)=>run(()=>api('/api/web/releases',{method:'POST',body:JSON.stringify(f)}))}/>} 
  {modal==='releaseDetail'&&selected&&<ReleaseDetail item={selected} canApprove={canApprove} canExecute={canExecute} onClose={()=>setModal(null)} onAction={(kind:string)=>run(()=>api(`/api/web/releases/${selected.id}/${kind}`,{method:'POST'}))}/>}
  {modal==='publishRequest'&&selected&&<PublishRequest item={selected} canApprove={canApprove} canExecute={canExecute} onClose={()=>setModal(null)} onAction={(kind:string)=>run(()=>api(`/api/web/publish-requests/${selected.id}/${kind}`,{method:'POST'}))}/>} 
  {busy&&<div className="ordersBusy">Working…</div>}
 </div>
}

function Overview({data,site,onTab}:Any){const h=data.health||{};return <div className="websiteOverview"><section className="websiteOverviewGrid"><div className="panel websitePreview"><div className="panelHeading"><div><h3>Public website snapshot</h3><p>{site.name} · {site.primary_domain||'Domain not set'}</p></div><a href={`/api/web/hosting/health?siteId=${site.id}`}><ExternalLink size={14}/></a></div><div className="websitePreviewCard"><div className="previewTop"><span>AMAA L BUSINESS</span><b>{site.name}</b></div><div className="previewHero"><span>Customer-facing storefront</span><strong>Products, offers & useful information</strong><small>Content shown here comes from your published business records.</small></div><div className="previewLinks">{(data.navigation||[]).filter((x:Any)=>x.enabled).slice(0,5).map((x:Any)=><span key={x.id}>{x.label}</span>)}</div></div></div><div className="panel"><div className="panelHeading"><div><h3>Website health</h3><p>Business-facing status only.</p></div></div><div className="websiteHealth"><div><span>Website</span><strong>{site.status}</strong></div><div><span>Address</span><strong>{site.primary_domain||'Not set'}</strong></div><div><span>Latest release</span><strong>{fmt(data.releases?.[0]?.status)}</strong></div><div><span>Published pages</span><strong>{(data.pages||[]).filter((x:Any)=>x.status==='Published').length}</strong></div><div><span>Pending reviews</span><strong>{(data.requests||[]).filter((x:Any)=>x.status==='Pending').length}</strong></div><div><span>Provider connection</span><strong>{h.healthy?'Healthy':'Review status'}</strong></div></div></div></section><section className="panel"><div className="panelHeading"><div><h3>Manage the storefront</h3><p>Jump directly into the area that needs attention.</p></div></div><div className="websiteQuickGrid">{[['pages','Pages','Create, edit and review customer-facing pages',LayoutList],['navigation','Menus','Organise the public menu',Menu],['banners','Banners','Manage campaigns and hero promotions',Megaphone],['media','Media','Keep approved imagery organised',ImagePlus],['publishing','Publishing','Review and release approved changes',Send],['settings','Website settings','Branding and public contact details',Settings2]].map(([id,title,desc,Icon]:Any)=><button key={id} onClick={()=>onTab(id)}><Icon size={18}/><span><strong>{title}</strong><small>{desc}</small></span><ChevronRight size={14}/></button>)}</div></section></div>}
function SiteEdit({site,onClose,onSave}:Any){const [f,setF]=useState({name:site.name,description:site.description||'',primaryDomain:site.primary_domain||'',status:site.status||'Active',locale:site.default_locale||'en-UG',currency:site.default_currency||'UGX'});return <Modal title={`Edit · ${site.name}`} onClose={onClose}><div className="adminFormGrid"><Field label="Website name" value={f.name} onChange={(v:any)=>setF({...f,name:v})}/><Field label="Primary domain" value={f.primaryDomain} onChange={(v:any)=>setF({...f,primaryDomain:v})}/><Select label="Website status" value={f.status} onChange={(v:any)=>setF({...f,status:v})} options={['Active','Maintenance','Disabled']}/><Select label="Currency" value={f.currency} onChange={(v:any)=>setF({...f,currency:v})} options={['UGX','USD','KES','TZS']}/></div><Textarea label="Description" value={f.description} onChange={(v:any)=>setF({...f,description:v})}/><button className="primaryAction" onClick={()=>onSave(f)}>Save website</button></Modal>}
function SiteForm({onClose,onSave}:Any){const [f,setF]=useState({name:'',slug:'',primaryDomain:'',description:'',locale:'en-UG',currency:'UGX'});return <Modal title="Add website" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="adminFormGrid"><Field label="Website name" value={f.name} onChange={(v:any)=>setF({...f,name:v})}/><Field label="Website address" value={f.slug} onChange={(v:any)=>setF({...f,slug:v})} placeholder="amaal-telecoms"/><Field label="Primary domain" value={f.primaryDomain} onChange={(v:any)=>setF({...f,primaryDomain:v})}/><Select label="Currency" value={f.currency} onChange={(v:any)=>setF({...f,currency:v})} options={['UGX','USD','KES','TZS']}/></div><Textarea label="Description" value={f.description} onChange={(v:any)=>setF({...f,description:v})}/><button className="primaryAction">Create website</button></form></Modal>}
function PageForm({siteId,onClose,onSave}:Any){const [f,setF]=useState({siteId,title:'',slug:'',template:'standard',excerpt:'',body:{heading:'',text:''},seoTitle:'',seoDescription:'',canonicalUrl:'',noindex:false});return <Modal title="Create page" onClose={onClose} wide><form onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="adminFormGrid"><Field label="Page title" value={f.title} onChange={(v:any)=>setF({...f,title:v})}/><Field label="Page address" value={f.slug} onChange={(v:any)=>setF({...f,slug:v})}/><Select label="Page layout" value={f.template} onChange={(v:any)=>setF({...f,template:v})} options={['standard','landing','contact','about','catalogue']}/><Field label="Search title" value={f.seoTitle} onChange={(v:any)=>setF({...f,seoTitle:v})}/></div><Textarea label="Short introduction" value={f.excerpt} onChange={(v:any)=>setF({...f,excerpt:v})}/><Field label="Main heading" value={f.body.heading} onChange={(v:any)=>setF({...f,body:{...f.body,heading:v}})}/><Textarea label="Page content" value={f.body.text} onChange={(v:any)=>setF({...f,body:{...f.body,text:v}})}/><Field label="Search description" value={f.seoDescription} onChange={(v:any)=>setF({...f,seoDescription:v})}/><button className="primaryAction">Save draft page</button></form></Modal>}
function PageEdit({page,onClose,onSave,onPublish}:Any){const [f,setF]=useState({title:page.title,slug:page.slug,excerpt:page.excerpt,body:page.body_json||{},seoTitle:page.seo_title,seoDescription:page.seo_description,canonicalUrl:page.canonical_url,noindex:page.noindex,status:page.status});return <Modal title={`Edit · ${page.title}`} onClose={onClose} wide><div className="adminFormGrid"><Field label="Page title" value={f.title} onChange={(v:any)=>setF({...f,title:v})}/><Field label="Page address" value={f.slug} onChange={(v:any)=>setF({...f,slug:v})}/><Field label="Search title" value={f.seoTitle} onChange={(v:any)=>setF({...f,seoTitle:v})}/><Select label="Status" value={f.status} onChange={(v:any)=>setF({...f,status:v})} options={['Draft','In Review','Approved','Archived']}/></div><Textarea label="Introduction" value={f.excerpt} onChange={(v:any)=>setF({...f,excerpt:v})}/><Textarea label="Page content" value={typeof f.body==='object'?JSON.stringify(f.body,null,2):f.body} onChange={(v:any)=>{try{setF({...f,body:JSON.parse(v)})}catch{setF({...f,body:{text:v}})}}}/><Field label="Search description" value={f.seoDescription} onChange={(v:any)=>setF({...f,seoDescription:v})}/><div className="nextActionRow"><button className="primaryAction" onClick={()=>onSave(f)}>Save changes</button>{onPublish&&page.status!=='Published'&&<button onClick={()=>onPublish('publish')}>Send for publishing</button>}</div></Modal>}
function NavigationForm({siteId,onClose,onSave}:Any){const [f,setF]=useState({siteId,menuKey:'main',label:'',url:'/',sortOrder:0,parentId:null,openNewTab:false,enabled:true});return <Modal title="Add menu item" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="adminFormGrid"><Field label="Menu label" value={f.label} onChange={(v:any)=>setF({...f,label:v})}/><Field label="Link" value={f.url} onChange={(v:any)=>setF({...f,url:v})}/><Field label="Order" type="number" value={f.sortOrder} onChange={(v:any)=>setF({...f,sortOrder:v})}/><Select label="Menu" value={f.menuKey} onChange={(v:any)=>setF({...f,menuKey:v})} options={['main','footer']}/></div><button className="primaryAction">Add menu item</button></form></Modal>}
function NavigationEdit({item,onClose,onSave}:Any){const [f,setF]=useState({label:item.label,url:item.url,sortOrder:item.sort_order,enabled:item.enabled,openNewTab:item.open_new_tab});return <Modal title={`Edit · ${item.label}`} onClose={onClose}><div className="adminFormGrid"><Field label="Menu label" value={f.label} onChange={(v:any)=>setF({...f,label:v})}/><Field label="Link" value={f.url} onChange={(v:any)=>setF({...f,url:v})}/><Field label="Order" type="number" value={f.sortOrder} onChange={(v:any)=>setF({...f,sortOrder:v})}/><Select label="Visible" value={String(f.enabled)} onChange={(v:any)=>setF({...f,enabled:v==='true'})} options={[{value:'true',label:'Visible'},{value:'false',label:'Hidden'}]}/></div><button className="primaryAction" onClick={()=>onSave(f)}>Save changes</button></Modal>}
function BannerForm({siteId,onClose,onSave}:Any){const [f,setF]=useState({siteId,title:'',subtitle:'',imageMediaId:'',linkUrl:'',placement:'home-hero',status:'Draft',startsAt:'',endsAt:'',sortOrder:0});return <Modal title="Add promotional banner" onClose={onClose}><div className="adminFormGrid"><Field label="Title" value={f.title} onChange={(v:any)=>setF({...f,title:v})}/><Field label="Subtitle" value={f.subtitle} onChange={(v:any)=>setF({...f,subtitle:v})}/><Field label="Image reference" value={f.imageMediaId} onChange={(v:any)=>setF({...f,imageMediaId:v})}/><Field label="Destination" value={f.linkUrl} onChange={(v:any)=>setF({...f,linkUrl:v})}/><Field label="Placement" value={f.placement} onChange={(v:any)=>setF({...f,placement:v})}/><Select label="Status" value={f.status} onChange={(v:any)=>setF({...f,status:v})} options={['Draft','Scheduled']}/></div><button className="primaryAction" onClick={()=>onSave(f)}>Save banner</button></Modal>}
function BlockForm({siteId,onClose,onSave}:Any){const [f,setF]=useState({siteId,key:'',title:'',content:{heading:'',text:''}});return <Modal title="Add content area" onClose={onClose}><Field label="Area name" value={f.key} onChange={(v:any)=>setF({...f,key:v})}/><Field label="Title" value={f.title} onChange={(v:any)=>setF({...f,title:v})}/><Textarea label="Content" value={f.content.text} onChange={(v:any)=>setF({...f,content:{...f.content,text:v}})}/><button className="primaryAction" onClick={()=>onSave(f)}>Save content</button></Modal>}
function BlockEdit({item,onClose,onSave,onPublish}:Any){const [f,setF]=useState({title:item.title,content:item.content_json||{},status:item.status});return <Modal title={`Edit · ${item.title||item.key}`} onClose={onClose}><Field label="Title" value={f.title} onChange={(v:any)=>setF({...f,title:v})}/><Textarea label="Content" value={typeof f.content==='object'?JSON.stringify(f.content,null,2):f.content} onChange={(v:any)=>{try{setF({...f,content:JSON.parse(v)})}catch{setF({...f,content:{text:v}})}}}/><Select label="Status" value={f.status} onChange={(v:any)=>setF({...f,status:v})} options={['Draft','Approved','Archived']}/><div className="nextActionRow"><button className="primaryAction" onClick={()=>onSave(f)}>Save changes</button>{onPublish&&f.status!=='Published'&&<button onClick={()=>onPublish('publish')}>Send for publishing</button>}</div></Modal>}
function MediaForm({siteId,onClose,onSave}:Any){const [f,setF]=useState({siteId,filename:'',mimeType:'image/jpeg',dataBase64:'',altText:''});return <Modal title="Add image" onClose={onClose}><Field label="File name" value={f.filename} onChange={(v:any)=>setF({...f,filename:v})}/><Select label="Image type" value={f.mimeType} onChange={(v:any)=>setF({...f,mimeType:v})} options={['image/jpeg','image/png','image/webp','image/gif']}/><Textarea label="Image data" value={f.dataBase64} onChange={(v:any)=>setF({...f,dataBase64:v})} placeholder="Paste the image data supplied by your approved media process"/><Field label="Description for customers" value={f.altText} onChange={(v:any)=>setF({...f,altText:v})}/><button className="primaryAction" onClick={()=>onSave(f)}>Add image</button></Modal>}
function MediaEdit({item,onClose,onStatus,onPublish}:Any){return <Modal title={`Media · ${item.filename}`} onClose={onClose}><div className="detailGrid"><div><span>File</span><strong>{item.filename}</strong></div><div><span>Type</span><strong>{item.mime_type}</strong></div><div><span>Status</span><strong>{item.status}</strong></div><div><span>Description</span><strong>{item.alt_text||'—'}</strong></div></div><div className="nextActionRow"><button onClick={()=>onStatus('Archived')}>Archive</button>{onPublish&&item.status!=='Published'&&<button className="primaryAction" onClick={()=>onPublish('publish')}>Send for publishing</button>}</div></Modal>}
function DomainForm({siteId,onClose,onSave}:Any){const [f,setF]=useState({siteId,hostname:'',type:'Custom'});return <Modal title="Add website address" onClose={onClose}><Field label="Website address" value={f.hostname} onChange={(v:any)=>setF({...f,hostname:v})} placeholder="www.example.com"/><Select label="Type" value={f.type} onChange={(v:any)=>setF({...f,type:v})} options={['Custom','Primary','Redirect']}/><button className="primaryAction" onClick={()=>onSave(f)}>Add address</button></Modal>}
function RedirectForm({siteId,onClose,onSave}:Any){const [f,setF]=useState({siteId,sourcePath:'/',destinationUrl:'/',statusCode:301});return <Modal title="Add redirect" onClose={onClose}><Field label="From" value={f.sourcePath} onChange={(v:any)=>setF({...f,sourcePath:v})}/><Field label="To" value={f.destinationUrl} onChange={(v:any)=>setF({...f,destinationUrl:v})}/><Select label="Redirect type" value={f.statusCode} onChange={(v:any)=>setF({...f,statusCode:Number(v)})} options={[301,302,307,308]}/><button className="primaryAction" onClick={()=>onSave(f)}>Save redirect</button></Modal>}
function ReleaseForm({siteId,onClose,onSave}:Any){const [f,setF]=useState({siteId,releaseName:'',environment:'Staging',notes:''});return <Modal title="Create website release" onClose={onClose}><Field label="Release name" value={f.releaseName} onChange={(v:any)=>setF({...f,releaseName:v})}/><Select label="Area" value={f.environment} onChange={(v:any)=>setF({...f,environment:v})} options={['Staging','Production']}/><Textarea label="Notes" value={f.notes} onChange={(v:any)=>setF({...f,notes:v})}/><button className="primaryAction" onClick={()=>onSave(f)}>Create release</button></Modal>}
function BannerDetail({item,canRequest,onClose,onPublish}:Any){return <Modal title={`Banner · ${item.title}`} onClose={onClose}><div className="detailGrid"><div><span>Placement</span><strong>{item.placement}</strong></div><div><span>Status</span><strong>{item.status}</strong></div><div><span>Starts</span><strong>{item.starts_at||'Any time'}</strong></div><div><span>Ends</span><strong>{item.ends_at||'No end date'}</strong></div></div><div className="panel"><h4>{item.subtitle||'Promotion'}</h4><p>Keep campaign timing and customer-facing presentation aligned with the current catalogue and promotions.</p></div>{canRequest&&item.status!=='Published'&&<button className="primaryAction" onClick={onPublish}>Send for publishing</button>}</Modal>}
function ReleaseDetail({item,canApprove,canExecute,onClose,onAction}:Any){return <Modal title={`Release · ${item.release_name}`} onClose={onClose}><div className="detailGrid"><div><span>Area</span><strong>{item.environment}</strong></div><div><span>Status</span><strong>{item.status}</strong></div><div><span>Created</span><strong>{item.created_at}</strong></div><div><span>Published</span><strong>{item.published_at||'—'}</strong></div></div><div className="nextActionRow">{canApprove&&item.status==='Draft'&&<button className="primaryAction" onClick={()=>onAction('approve')}>Approve release</button>}{canExecute&&item.status==='Approved'&&<button className="primaryAction" onClick={()=>onAction('publish')}>Publish release</button>}{canExecute&&item.status==='Published'&&<button onClick={()=>onAction('rollback')}>Roll back release</button>}</div></Modal>}
function PublishRequest({item,canApprove,canExecute,onClose,onAction}:Any){return <Modal title="Publishing request" onClose={onClose}><div className="detailGrid"><div><span>Item</span><strong>{item.resource_type}</strong></div><div><span>Action</span><strong>{item.action}</strong></div><div><span>Status</span><strong>{item.status}</strong></div><div><span>Requested by</span><strong>{item.requester||'—'}</strong></div></div><div className="nextActionRow">{canApprove&&item.status==='Pending'&&<button className="primaryAction" onClick={()=>onAction('approve')}>Approve</button>}{canExecute&&item.status==='Approved'&&<button className="primaryAction" onClick={()=>onAction('execute')}>Publish</button>}</div></Modal>}
function SettingsPanel({site,settings,canManage,onSave}:Any){const [f,setF]=useState<any>({theme:settings.theme||'Amaal Telecoms',siteTitle:settings.siteTitle||site.name,tagline:settings.tagline||'',logoUrl:settings.logoUrl||'',faviconUrl:settings.faviconUrl||'',primaryColor:settings.primaryColor||'',secondaryColor:settings.secondaryColor||'',footerText:settings.footerText||'',maintenanceMessage:settings.maintenanceMessage||''});return <section className="panel"><div className="panelHeading"><div><h3>Website settings</h3><p>Business-facing branding, contact and public presentation settings.</p></div></div><div className="adminFormGrid"><Field label="Website title" value={f.siteTitle} onChange={(v:any)=>setF({...f,siteTitle:v})}/><Field label="Tagline" value={f.tagline} onChange={(v:any)=>setF({...f,tagline:v})}/><Field label="Logo address" value={f.logoUrl} onChange={(v:any)=>setF({...f,logoUrl:v})}/><Field label="Browser icon address" value={f.faviconUrl} onChange={(v:any)=>setF({...f,faviconUrl:v})}/><Field label="Main brand colour" value={f.primaryColor} onChange={(v:any)=>setF({...f,primaryColor:v})}/><Field label="Supporting colour" value={f.secondaryColor} onChange={(v:any)=>setF({...f,secondaryColor:v})}/></div><Textarea label="Footer text" value={f.footerText} onChange={(v:any)=>setF({...f,footerText:v})}/><Textarea label="Temporary notice" value={f.maintenanceMessage} onChange={(v:any)=>setF({...f,maintenanceMessage:v})}/>{canManage&&<button className="primaryAction" onClick={()=>onSave(f)}>Save website settings</button>}</section>}
