'use client';
import Link from 'next/link';import {ArrowLeft,Package,RefreshCw} from 'lucide-react';import {useEffect,useState} from 'react';import SiteHeader from '../../../components/SiteHeader';import SiteFooter from '../../../components/SiteFooter';import {customerRequest} from '../../../lib/customer-auth';import {money} from '../../../lib/commerce';
export default function AccountOrders(){const [data,setData]=useState<any>(null);const [detail,setDetail]=useState<any>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [orderNo,setOrderNo]=useState('');
 async function load(){setLoading(true);setError('');try{const d=await customerRequest('/api/public/account');setData(d);const wanted=new URLSearchParams(window.location.search).get('order');if(wanted){setOrderNo(wanted);const x=await customerRequest(`/api/public/account/orders/${encodeURIComponent(wanted)}`);setDetail(x)}}catch(e:any){setError(e.message||'Unable to load your orders.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function openOrder(no:string){setBusy(true);setError('');try{const x=await customerRequest(`/api/public/account/orders/${encodeURIComponent(no)}`);setDetail(x);setOrderNo(no);window.history.replaceState({},'',`/account/orders?order=${encodeURIComponent(no)}`)}catch(e:any){setError(e.message||'Unable to load that order.')}finally{setBusy(false)}}
 if(loading)return <main><SiteHeader/><section className="section customer-access"><RefreshCw className="spin"/><p>Loading your orders…</p></section><SiteFooter/></main>;
 if(error&&!data)return <main><SiteHeader/><section className="section customer-access"><p className="eyebrow">MY AMAAL</p><h1>Sign in to view your orders.</h1><p>{error}</p><Link className="button gold" href="/account">Open account</Link></section><SiteFooter/></main>;
 return <main><SiteHeader/><section className="section account-page"><Link className="back-link" href="/account"><ArrowLeft size={16}/> My Amaal</Link><div className="checkout-head"><p className="eyebrow">ORDER HISTORY</p><h1>Your orders.</h1><p>Every order placed through Amaal stays connected to your customer account.</p></div>{error&&<div className="form-error">{error}</div>}<div className="portal-grid"><section className="portal-card"><Package/><h2>Recent orders</h2>{data?.orders?.length?data.orders.map((o:any)=><button className={`portal-row order-select${orderNo===o.order_no?' selected':''}`} key={o.order_no} onClick={()=>openOrder(o.order_no)}><span><b>{o.order_no}</b><small>{o.status} · {o.delivery_status||'Delivery pending'}</small></span><strong>{money(Number(o.grand_total||0))}</strong></button>):<p>No orders yet. <Link href="/shop">Start shopping.</Link></p>}</section>{detail&&<section className="portal-card account-order-detail"><p className="eyebrow">ORDER {detail.order.order_no}</p><h2>{detail.order.status}</h2><p>{detail.order.shipping_address}</p><div className="order-lines">{detail.lines.map((x:any,i:number)=><div className="order-line" key={`${x.product_name}-${i}`}><span><b>{x.product_name}</b><small>{x.variant_name||'Standard'} · Qty {x.quantity}</small></span><strong>{money(Number(x.line_total||0))}</strong></div>)}</div><div className="summary-total"><span>Total</span><strong>{money(Number(detail.order.grand_total||0))}</strong></div><div className="order-timeline">{detail.events.map((x:any,i:number)=><div className="order-timeline-item" key={`${x.status}-${x.created_at}-${i}`}><i/><span><b>{x.status}</b><small>{x.notes||''} · {new Date(x.created_at).toLocaleString('en-UG')}</small></span></div>)}</div><div className="button-row"><Link className="button gold" href={`/tracking?order=${encodeURIComponent(detail.order.order_no)}`}>Track delivery</Link>{busy&&<span>Loading…</span>}</div></section>}</div></section><SiteFooter/></main>}
