import {Search, UserRound, ShoppingBag, ArrowRight, ShieldCheck, Truck, Wrench} from 'lucide-react';
import {getCatalog,image,price} from '@/lib/catalog';

const fallbackCategories=['Phones','Tablets','TVs','Home Appliances','Kitchen Appliances','Refrigeration','Office Electronics','Sound & Speakers'];
export default async function Home(){
 const catalog=await getCatalog(); const products=catalog?.products||[]; const categories=(catalog?.categories||[]).filter(c=>!c.parent_id); const brands=(catalog?.brands||[]).slice(0,8); const featured=products.filter(p=>p.featured).slice(0,4); const picks=(featured.length?featured:products).slice(0,4);
 return <main>
  <header className="header"><div className="brand">AMAAL</div><nav><a href="#shop">Shop</a><a href="#categories">Categories</a><a href="#brands">Brands</a><a href="#deals">Deals</a><a href="#services">Services</a></nav><div className="actions"><button aria-label="Search"><Search size={19}/></button><button aria-label="Account"><UserRound size={19}/></button><button aria-label="Bag"><ShoppingBag size={19}/></button></div></header>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">PREMIUM CONSUMER ELECTRONICS</p><h1>Technology,<br/><em>beautifully chosen.</em></h1><p className="lead">Phones, appliances, entertainment and everyday technology from brands you can trust.</p><div className="hero-cta"><a className="button dark" href="#shop">Shop now <ArrowRight size={16}/></a><a className="text-link" href="#categories">Explore categories</a></div></div><div className="hero-art"><div className="art-glow"/><div className="art-card"><span>AMAAL</span><strong>Genuine.<br/>Premium.<br/>Everyday.</strong></div></div></section>
  <section className="trust"><div><ShieldCheck/><b>Genuine products</b><span>Trusted brands and authentic products</span></div><div><Truck/><b>Delivery</b><span>Convenient delivery options</span></div><div><Wrench/><b>Warranty & support</b><span>Help before and after purchase</span></div></section>
  <section id="categories" className="section"><div className="section-head"><div><p className="eyebrow">DISCOVER</p><h2>Shop by category</h2></div><a className="text-link" href="#shop">View all <ArrowRight size={15}/></a></div><div className="category-grid">{(categories.length?categories:fallbackCategories.map((name,i)=>({id:String(i),name,slug:name.toLowerCase().replaceAll(' ','-')}))).map((c:any)=><a className="category" href={`/category/${c.slug}`} key={c.id}><span>{c.name}</span><ArrowRight size={16}/></a>)}</div></section>
  <section id="shop" className="section soft"><div className="section-head"><div><p className="eyebrow">THE AMAAL EDIT</p><h2>Featured products</h2></div><a className="text-link" href="/shop">Shop all <ArrowRight size={15}/></a></div><div className="product-grid">{picks.map(p=><article className="product" key={p.id}><div className="product-image">{image(p)?<img src={image(p)} alt={p.name}/>:<div className="image-placeholder">AMAAL</div>}</div><div className="product-meta"><small>{p.brand_name||'AMAAL'}</small><h3>{p.name}</h3><strong>{price(p)}</strong></div></article>)}</div>{!picks.length&&<div className="empty">Your public catalogue is ready to connect. Publish products from the Business Admin Console to see them here.</div>}</section>
  <section id="brands" className="section"><div className="section-head"><div><p className="eyebrow">BRANDS</p><h2>Names you know. Quality you trust.</h2></div></div><div className="brands">{brands.map(b=><div className="brand-pill" key={b.id}>{b.name}</div>)}</div></section>
  <section id="deals" className="campaign"><div><p className="eyebrow">AMAAL DEALS</p><h2>Better technology,<br/>beautifully priced.</h2><p>Discover approved promotions and seasonal offers across the Amaal catalogue.</p><a className="button light" href="/deals">Explore deals <ArrowRight size={16}/></a></div><div className="campaign-number">A</div></section>
  <section id="services" className="service"><div><p className="eyebrow">AFTER SALES</p><h2>We're here after the purchase, too.</h2><p>Track orders, understand delivery, access warranty support and request service from one connected experience.</p></div><div className="service-links"><a href="/track-order">Track an order <ArrowRight size={16}/></a><a href="/services/warranty">Warranty <ArrowRight size={16}/></a><a href="/services/repairs">Repairs & service <ArrowRight size={16}/></a></div></section>
  <footer><div className="footer-brand"><div className="brand">AMAAL</div><p>Premium consumer electronics for everyday life.</p></div><div><b>Shop</b><a href="#categories">Categories</a><a href="#brands">Brands</a><a href="/deals">Deals</a></div><div><b>Customer care</b><a href="/faq">Help & FAQ</a><a href="/delivery">Delivery</a><a href="/services/warranty">Warranty</a><a href="/services/repairs">Repairs</a></div><div><b>Company</b><a href="/about">About Amaal</a><a href="/contact">Contact</a><a href="/account">Account</a></div></footer>
 </main>
}
