'use client';
import Link from 'next/link';import {useEffect,useMemo,useState} from 'react';import SiteHeader from '../../components/SiteHeader';import SiteFooter from '../../components/SiteFooter';import {getCompare,clearCompare} from '../../lib/compare';import {computerProducts} from '../../lib/computer-catalogue';import {audioProducts} from '../../lib/audio-catalogue';import {tabletProducts} from '../../lib/tablet-catalogue';import {accessoryProducts} from '../../lib/accessory-catalogue';import {applianceProducts} from '../../lib/appliance-catalogue';import {phoneCatalogue} from '../../lib/phone-catalogue';import {tvCatalogue} from '../../lib/tv-catalogue';
type Row={id:string;slug:string;name:string;brand:string;category:string;description:string;specs:Record<string,string>;href:string;price?:number};
const normalize=(x:any,kind:string):Row=>({id:String(x.id||x.slug),slug:String(x.slug),name:x.name,brand:x.brand||x.brand_name||'AMAAL',category:x.category||x.type||x.segment||x.family||kind,description:x.description||x.shortDescription||x.short_description||'',specs:{...Object.fromEntries(Object.entries(x.specs||{}).map(([k,v])=>[k,String(v)])),...Object.fromEntries((Array.isArray(x.attributes)?x.attributes:[]).map((a:any)=>[String(a.key),`${a.value}${a.unit?` ${a.unit}`:''}`]))},href:x.href||`/product/${x.slug}`,price:Number(x.variants?.[0]?.sellingPrice||0)||undefined});
const flatten=(x:any):any[]=>Array.isArray(x)?x:[x];
export default function Compare(){const [ids,setIds]=useState<string[]>([]);const [db,setDb]=useState<any[]>([]);useEffect(()=>{setIds(getCompare());const base=process.env.NEXT_PUBLIC_API_BASE_URL||process.env.AMAAL_API_BASE_URL||'';fetch(`${base}/api/public/catalog`).then(r=>r.ok?r.json():null).then(d=>setDb(d?.products||[])).catch(()=>{})},[]);const all=useMemo<Row[]>(()=>{
const catalogue=flatten(db).map(x=>normalize(x,'Catalogue'));
const phones=flatten(phoneCatalogue).map(x=>normalize(x,'Phone'));
const computers=flatten(computerProducts).map(x=>normalize(x,'Computer'));
const tvs=flatten(tvCatalogue).map(x=>normalize({...x,name:`${x.brand} ${x.model}`,shortDescription:`${x.technology} · ${x.generation}`,specs:{technology:x.technology,sizes:Array.isArray(x.sizes)?x.sizes.join(', '):x.sizes,verification:x.verificationStatus,market:x.market}},'TV'));
const audio=flatten(audioProducts).map(x=>normalize(x,'Audio'));
const tablets=flatten(tabletProducts).map(x=>normalize(x,'Tablet'));
const accessories=flatten(accessoryProducts).map(x=>normalize(x,'Accessory'));
const appliances=flatten(applianceProducts).map(x=>normalize(x,'Appliance'));
return [...catalogue,...phones,...computers,...tvs,...audio,...tablets,...accessories,...appliances];
},[db]);const rows=ids.map(id=>all.find(x=>x.id===id||x.slug===id)).filter(Boolean) as Row[];const specKeys=Array.from(new Set(rows.flatMap(x=>Object.keys(x.specs)))).slice(0,18);return <main><SiteHeader/><section className="section compare-page"><p className="eyebrow">COMPARE</p><h1>Put your shortlist side by side.</h1><p className="listing-lead">Compare up to four products from across the Amaal catalogue. Technical details are shown only when they are available in the catalogue.</p>{rows.length?<><div className="compare-table-wrap"><table><thead><tr><th>Product</th>{rows.map(p=><th key={p.id}><Link href={p.href}>{p.name}</Link></th>)}</tr></thead><tbody><tr><th>Brand</th>{rows.map(p=><td key={p.id}>{p.brand}</td>)}</tr><tr><th>Category</th>{rows.map(p=><td key={p.id}>{p.category}</td>)}</tr><tr><th>Price</th>{rows.map(p=><td key={p.id}>{p.price&&p.price>0?new Intl.NumberFormat('en-UG',{style:'currency',currency:'UGX',maximumFractionDigits:0}).format(p.price):'Price coming soon'}</td>)}</tr>{specKeys.map(k=><tr key={k}><th>{k}</th>{rows.map(p=><td key={p.id}>{p.specs[k]||'—'}</td>)}</tr>)}<tr><th>Details</th>{rows.map(p=><td key={p.id}>{p.description||'Details to be confirmed.'}</td>)}</tr></tbody></table></div><button className="button outline" onClick={()=>{clearCompare();setIds([])}}>Clear comparison</button></>:<div className="empty"><h2>Your comparison is empty.</h2><p>Choose Compare on products you are considering.</p><Link className="button gold" href="/shop">Browse products</Link></div>}</section><SiteFooter/></main>}
