export type AccessoryProduct={slug:string;brand:string;name:string;type:'Phone accessory'|'Computer accessory'|'Tablet accessory'|'Audio accessory'|'Gaming accessory';segment:'ESSENTIAL'|'PRODUCTIVITY'|'PREMIUM'|'GAMING';shortDescription:string;description:string;quickSpecs:string[];specs:Record<string,string>};
const a=(x:AccessoryProduct)=>x;
export const accessoryProducts:AccessoryProduct[]=[
 a({slug:'apple-pencil-pro',brand:'Apple',name:'Apple Pencil Pro',type:'Tablet accessory',segment:'PREMIUM',shortDescription:'A premium stylus for compatible iPad models, designed for drawing, notes, markup and creative workflows.',description:'Apple Pencil Pro is a precision input accessory for compatible iPad models. It is designed for customers who draw, annotate documents, take handwritten notes or work in creative applications where accurate pen input matters.',quickSpecs:['Precision stylus','Squeeze + barrel controls','Find My support'],specs:{'Compatibility':'Compatible iPad models','Controls':'Squeeze / barrel interaction','Charging':'Magnetic attachment and charging on compatible iPad','Use':'Drawing / notes / markup / creative apps'}}),
 a({slug:'apple-pencil-usb-c',brand:'Apple',name:'Apple Pencil (USB-C)',type:'Tablet accessory',segment:'ESSENTIAL',shortDescription:'A practical Apple Pencil for compatible iPad models, with USB-C charging and precise input.',description:'Apple Pencil (USB-C) gives compatible iPad users a straightforward way to write, sketch, annotate and navigate with precision. It is a strong everyday choice for students, professionals and creators who need reliable pen input.',quickSpecs:['USB-C charging','Pixel-level precision','Low-latency writing'],specs:{'Compatibility':'Compatible iPad models','Charging':'USB-C','Use':'Notes / drawing / markup','Positioning':'Everyday iPad stylus'}}),
 a({slug:'ipad-magic-keyboard',brand:'Apple',name:'Magic Keyboard for iPad',type:'Tablet accessory',segment:'PREMIUM',shortDescription:'A keyboard and protective cover designed to turn a compatible iPad into a more laptop-like workspace.',description:'Magic Keyboard for iPad combines a keyboard, protective design and a built-in trackpad experience for compatible iPad models. It is aimed at customers who regularly write documents, answer email, edit content or use their iPad as a primary productivity device.',quickSpecs:['Keyboard + trackpad','Protective cover','Compatible iPad variants'],specs:{'Type':'Keyboard case','Input':'Keyboard / trackpad','Compatibility':'Compatible iPad models','Use':'Productivity / writing / multitasking'}}),
 a({slug:'samsung-s-pen',brand:'Samsung',name:'Samsung S Pen',type:'Tablet accessory',segment:'PREMIUM',shortDescription:'Samsung’s precision pen ecosystem for compatible Galaxy tablets, ideal for notes, drawing and markup.',description:'Samsung S Pen is designed for compatible Galaxy tablets and gives users a more natural way to write, sketch, annotate and interact with creative applications. Compatibility varies by tablet generation, so Amaal will confirm the matching device before sale.',quickSpecs:['Precision pen input','Notes + drawing','Galaxy Tab compatibility'],specs:{'Compatibility':'Selected Galaxy Tab models','Use':'Notes / drawing / markup','Availability':'Model-dependent'}}),
 a({slug:'usb-c-fast-charger-20w',brand:'Amaal',name:'20 W USB-C Fast Charger',type:'Phone accessory',segment:'ESSENTIAL',shortDescription:'A compact USB-C wall charger for compatible phones, tablets and everyday USB-C devices.',description:'A compact 20 W USB-C charger designed for everyday charging of compatible USB-C devices. It is suitable for customers who need an additional charger for home, office, travel or a second charging location.',quickSpecs:['20 W output','USB-C','Compact travel size'],specs:{'Output':'Up to 20 W','Port':'USB-C','Use':'Compatible USB-C devices'}}),
 a({slug:'usb-c-to-usb-c-cable',brand:'Amaal',name:'USB-C to USB-C Charging Cable',type:'Phone accessory',segment:'ESSENTIAL',shortDescription:'A practical USB-C cable for charging and compatible data connections.',description:'A USB-C to USB-C cable for customers who need a reliable everyday cable for compatible phones, tablets, laptops, chargers and power banks. Final charging and data performance depends on the connected devices and charger.',quickSpecs:['USB-C to USB-C','Charging + data','Everyday cable'],specs:{'Connectors':'USB-C to USB-C','Use':'Charging / compatible data transfer','Performance':'Device-dependent'}}),
 a({slug:'wireless-charging-pad',brand:'Amaal',name:'Wireless Charging Pad',type:'Phone accessory',segment:'ESSENTIAL',shortDescription:'A simple wireless charging pad for compatible Qi-enabled devices.',description:'A wireless charging pad provides a convenient cable-free charging position for compatible devices. It is useful on desks, bedside tables and other fixed charging points where customers want to reduce cable clutter.',quickSpecs:['Qi-compatible devices','Desk-friendly','Cable-free charging'],specs:{'Compatibility':'Compatible Qi-enabled devices','Use':'Wireless charging','Placement':'Desk / bedside / office'}}),
 a({slug:'power-bank-10000mah',brand:'Amaal',name:'10,000 mAh Power Bank',type:'Phone accessory',segment:'ESSENTIAL',shortDescription:'A portable backup battery for phones and other compatible USB devices.',description:'A 10,000 mAh power bank gives customers a portable source of backup power when they are travelling, commuting, working away from sockets or simply need a second charging option during the day.',quickSpecs:['10,000 mAh class','Portable backup power','USB charging'],specs:{'Capacity':'10,000 mAh class','Use':'Portable charging','Compatibility':'USB-chargeable devices'}}),
 a({slug:'laptop-sleeve-15-inch',brand:'Amaal',name:'15-inch Laptop Sleeve',type:'Computer accessory',segment:'ESSENTIAL',shortDescription:'A protective everyday sleeve for compatible laptops up to the stated size class.',description:'A slim laptop sleeve designed to help protect a compatible laptop during transport between home, work, school and travel. Customers should confirm their laptop dimensions before selecting a sleeve size.',quickSpecs:['15-inch class','Protective sleeve','Travel friendly'],specs:{'Fit':'15-inch class laptops','Use':'Transport / protection','Note':'Device dimensions should be checked'}}),
 a({slug:'usb-c-multiport-hub',brand:'Amaal',name:'USB-C Multiport Hub',type:'Computer accessory',segment:'PRODUCTIVITY',shortDescription:'A compact expansion hub for compatible USB-C laptops and tablets.',description:'A USB-C multiport hub expands connectivity on compatible laptops and tablets, helping customers connect common peripherals such as USB devices, displays or memory cards depending on the exact hub configuration. Ports vary by model.',quickSpecs:['USB-C host connection','Multiple expansion ports','Laptop + tablet focused'],specs:{'Host':'USB-C','Expansion':'Model-dependent USB / display / card ports','Use':'Connectivity expansion'}}),
 a({slug:'wireless-keyboard-mouse-combo',brand:'Amaal',name:'Wireless Keyboard & Mouse Combo',type:'Computer accessory',segment:'PRODUCTIVITY',shortDescription:'A practical wireless keyboard and mouse set for desks, offices and home workspaces.',description:'A wireless keyboard and mouse combination helps customers create a cleaner desk setup without separate wired peripherals. It is suitable for office work, home computing, school and general productivity.',quickSpecs:['Keyboard + mouse','Wireless desk setup','Everyday productivity'],specs:{'Includes':'Keyboard and mouse','Connection':'Wireless','Use':'Office / home / study'}}),
 a({slug:'1080p-usb-webcam',brand:'Amaal',name:'1080p USB Webcam',type:'Computer accessory',segment:'PRODUCTIVITY',shortDescription:'A USB webcam for video calls, online learning, meetings and content creation.',description:'A 1080p USB webcam is a practical upgrade for laptops, desktops and monitors where the built-in camera is limited or where a dedicated camera position is useful. Exact microphone and autofocus features vary by model.',quickSpecs:['1080p class video','USB connection','Video calls + meetings'],specs:{'Resolution':'Up to 1080p class','Connection':'USB','Use':'Meetings / learning / streaming'}}),
 a({slug:'usb-gaming-headset',brand:'Amaal',name:'USB Gaming Headset',type:'Gaming accessory',segment:'GAMING',shortDescription:'An over-ear gaming headset for game audio, voice chat and everyday media.',description:'A USB gaming headset provides a dedicated audio and microphone setup for gaming, calls and entertainment. Exact surround, lighting and microphone controls depend on the model selected.',quickSpecs:['Over-ear headset','USB connection','Microphone'],specs:{'Connection':'USB','Use':'Gaming / voice chat / media','Microphone':'Integrated'}}),
 a({slug:'gaming-mouse-rgb',brand:'Amaal',name:'RGB Gaming Mouse',type:'Gaming accessory',segment:'GAMING',shortDescription:'A responsive gaming mouse designed for PC gaming and precise everyday control.',description:'An RGB gaming mouse provides a more responsive pointing experience for gaming and can also serve as a general desktop mouse. Sensor, polling rate, programmable buttons and lighting vary by model.',quickSpecs:['Gaming sensor','Programmable controls','RGB lighting'],specs:{'Sensor':'Model-dependent','Controls':'Programmable buttons on selected models','Lighting':'RGB on supported models'}}),
 a({slug:'gaming-mechanical-keyboard',brand:'Amaal',name:'Mechanical Gaming Keyboard',type:'Gaming accessory',segment:'GAMING',shortDescription:'A mechanical keyboard for gaming, typing and performance-focused desktop setups.',description:'A mechanical gaming keyboard is designed for customers who want a more tactile and responsive typing experience. Switch type, layout, connection method and lighting vary by model, so the final configuration is confirmed before purchase.',quickSpecs:['Mechanical switches','Gaming layout','RGB on supported models'],specs:{'Switches':'Model-dependent mechanical switches','Connection':'Wired or wireless depending on model','Lighting':'RGB on supported models'}}),
 a({slug:'gaming-mouse-pad-xl',brand:'Amaal',name:'XL Gaming Mouse Pad',type:'Gaming accessory',segment:'GAMING',shortDescription:'A large mouse surface designed for low-friction gaming and clean desk setups.',description:'An XL gaming mouse pad gives gamers a generous surface for low-sensitivity mouse movement while also helping visually unify a gaming desk. Surface material, edge stitching and dimensions vary by model.',quickSpecs:['XL desk coverage','Smooth control surface','Gaming setup'],specs:{'Size':'XL class','Use':'Gaming / desktop','Surface':'Model-dependent'}}),
 a({slug:'bluetooth-portable-speaker-case',brand:'Amaal',name:'Portable Speaker Carry Case',type:'Audio accessory',segment:'ESSENTIAL',shortDescription:'A protective carry solution for compatible portable speakers during travel and outdoor use.',description:'A speaker carry case helps protect a compatible portable speaker from everyday transport wear and makes it easier to carry to events, trips and outdoor gatherings. Fit is model-specific and should be confirmed before purchase.',quickSpecs:['Portable speaker protection','Carry handle','Model-dependent fit'],specs:{'Compatibility':'Model-dependent','Use':'Transport / protection','Fit':'Confirm speaker dimensions'}}),
];
export const accessoryTypes=['Phone accessory','Computer accessory','Tablet accessory','Audio accessory','Gaming accessory'] as const;
export const accessoryBrands=Array.from(new Set(accessoryProducts.map(x=>x.brand)));
export const accessoryProduct=(slug:string)=>accessoryProducts.find(x=>x.slug===slug);
