export type AudioTier='ENTRY'|'EVERYDAY'|'PARTY'|'PREMIUM';
export type AudioProduct={slug:string;brand:string;name:string;type:string;tier:AudioTier;shortDescription:string;description:string;quickSpecs:string[];specs:Record<string,string>;oemUrl?:string;image?:string;};
const p=(x:AudioProduct)=>x;
export const audioBrands=['Black Ark','Global Star','SPJ','CHiQ Smart Plus','Hisense','Samsung','LG','JBL','Sony'] as const;
export const audioProducts:AudioProduct[]=[
 p({slug:'black-ark-12-inch-bluetooth-woofer',brand:'Black Ark',name:'Black Ark 12-inch Bluetooth Woofer',type:'Woofer',tier:'ENTRY',shortDescription:'A practical Bluetooth woofer for everyday music and home listening.',description:'A compact woofer-style sound system designed for everyday home entertainment, casual music listening and small gatherings.',quickSpecs:['12-inch woofer','Bluetooth','USB / FM'],specs:{'Speaker type':'Woofer','Woofer size':'12-inch','Wireless':'Bluetooth','Inputs':'USB / FM / AUX'}}),
 p({slug:'black-ark-15-inch-bluetooth-woofer',brand:'Black Ark',name:'Black Ark 15-inch Bluetooth Woofer',type:'Woofer',tier:'EVERYDAY',shortDescription:'A larger woofer format for stronger bass and fuller room sound.',description:'A larger Bluetooth woofer format aimed at home entertainment, family gatherings and music playback where stronger bass is preferred.',quickSpecs:['15-inch woofer','Bluetooth','USB / FM'],specs:{'Speaker type':'Woofer','Woofer size':'15-inch','Wireless':'Bluetooth','Inputs':'USB / FM / AUX'}}),
 p({slug:'global-star-12-inch-bluetooth-woofer',brand:'Global Star',name:'Global Star 12-inch Bluetooth Woofer',type:'Woofer',tier:'ENTRY',shortDescription:'An accessible Bluetooth woofer for everyday listening and home entertainment.',description:'An entry-level woofer-style system for music, radio and casual home entertainment.',quickSpecs:['12-inch woofer','Bluetooth','USB / FM'],specs:{'Speaker type':'Woofer','Woofer size':'12-inch','Wireless':'Bluetooth','Inputs':'USB / FM / AUX'}}),
 p({slug:'global-star-15-inch-bluetooth-woofer',brand:'Global Star',name:'Global Star 15-inch Bluetooth Woofer',type:'Woofer',tier:'EVERYDAY',shortDescription:'A larger-format woofer built around stronger bass and room-filling playback.',description:'A 15-inch woofer format for customers looking for a bigger sound system for home entertainment and gatherings.',quickSpecs:['15-inch woofer','Bluetooth','USB / FM'],specs:{'Speaker type':'Woofer','Woofer size':'15-inch','Wireless':'Bluetooth','Inputs':'USB / FM / AUX'}}),
 p({slug:'spj-12-inch-portable-party-speaker',brand:'SPJ',name:'SPJ 12-inch Portable Party Speaker',type:'Party speaker',tier:'EVERYDAY',shortDescription:'Portable party sound with wireless music playback and practical inputs.',description:'A portable party-oriented speaker format suited to home gatherings, outdoor listening and casual events.',quickSpecs:['12-inch speaker','Bluetooth','USB / microphone input'],specs:{'Speaker type':'Portable party speaker','Driver size':'12-inch','Wireless':'Bluetooth','Inputs':'USB / microphone / AUX'}}),
 p({slug:'spj-15-inch-portable-party-speaker',brand:'SPJ',name:'SPJ 15-inch Portable Party Speaker',type:'Party speaker',tier:'PARTY',shortDescription:'A larger portable party format for bigger gatherings and stronger bass.',description:'A larger SPJ party-speaker format for customers who want more physical scale and fuller sound for gatherings.',quickSpecs:['15-inch speaker','Bluetooth','USB / microphone input'],specs:{'Speaker type':'Portable party speaker','Driver size':'15-inch','Wireless':'Bluetooth','Inputs':'USB / microphone / AUX'}}),
 p({slug:'chiq-smart-plus-12-inch-party-speaker',brand:'CHiQ Smart Plus',name:'CHiQ Smart Plus 12-inch Party Speaker',type:'Party speaker',tier:'EVERYDAY',shortDescription:'A practical party speaker for home entertainment and social gatherings.',description:'A 12-inch party-speaker format aimed at music playback, home entertainment and small-to-medium gatherings.',quickSpecs:['12-inch speaker','Bluetooth','USB / microphone input'],specs:{'Speaker type':'Party speaker','Driver size':'12-inch','Wireless':'Bluetooth','Inputs':'USB / microphone / AUX'}}),
 p({slug:'chiq-smart-plus-15-inch-party-speaker',brand:'CHiQ Smart Plus',name:'CHiQ Smart Plus 15-inch Party Speaker',type:'Party speaker',tier:'PARTY',shortDescription:'A larger party speaker format for bigger rooms and lively gatherings.',description:'A 15-inch party-speaker format designed for customers who want a larger cabinet and stronger room-filling presentation.',quickSpecs:['15-inch speaker','Bluetooth','USB / microphone input'],specs:{'Speaker type':'Party speaker','Driver size':'15-inch','Wireless':'Bluetooth','Inputs':'USB / microphone / AUX'}}),
 p({slug:'hisense-party-rocker-one',brand:'Hisense',name:'Hisense PARTY ROCKER ONE',type:'Party speaker',tier:'PARTY',shortDescription:'A 300 W party speaker with Bluetooth, lighting and microphone-friendly connectivity.',description:'Hisense PARTY ROCKER ONE is a 300 W party speaker with Bluetooth 5.0, USB and 3.5 mm audio input, designed for powerful bass and social listening.',quickSpecs:['300 W output','Bluetooth 5.0','USB · AUX'],specs:{'Output power':'300 W','Bluetooth':'5.0','USB':'1 × USB 2.0','Aux input':'1 × 3.5 mm','Power':'100–240 V','Net weight':'9.5 kg'},oemUrl:'https://uk.hisense.com/products/audio/portable-speakers/LOUDSPEAKER-PARTY-ROCKER-ONE-HSN/p/000000000020011156'}),
 p({slug:'samsung-sound-tower-mx-t50',brand:'Samsung',name:'Samsung Sound Tower MX-T50',type:'Sound Tower',tier:'PARTY',shortDescription:'A high-power Samsung Sound Tower built for home parties and powerful playback.',description:'Samsung MX-T50 is a 500 W Sound Tower system intended for powerful home entertainment and party playback.',quickSpecs:['500 W','Sound Tower','Bluetooth'],specs:{'Output power':'500 W','Product type':'Sound Tower','Wireless':'Bluetooth','Model':'MX-T50'},oemUrl:'https://www.samsung.com/eg/support/model/MX-T50/ZN/'}),
 p({slug:'lg-xboom-rnc5',brand:'LG',name:'LG XBOOM RNC5 Party Speaker',type:'Party speaker',tier:'PARTY',shortDescription:'A powerful XBOOM party system with lighting, DJ features and microphone/guitar inputs.',description:'LG XBOOM RNC5 is a 2-way 3-speaker party system with an 8-inch woofer, RGB lighting, DJ features and microphone and guitar inputs.',quickSpecs:['8-inch woofer','RGB lighting','DJ & karaoke'],specs:{'System':'2-way, 3-speaker','Woofer':'8-inch','Tweeters':'2 × 2-inch','Bluetooth':'4.0','USB':'2 inputs','Mic input':'1 × 6.3 mm','Guitar input':'1 × 6.3 mm','Weight':'13.8 kg'},oemUrl:'https://www.lg.com/africa/audio/lg-rnc5'}),
 p({slug:'lg-xboom-rnc7',brand:'LG',name:'LG XBOOM RNC7 Party Speaker',type:'Party speaker',tier:'PREMIUM',shortDescription:'A large XBOOM party system with 8-inch woofer, RGB lighting, DJ and karaoke features.',description:'LG XBOOM RNC7 combines an 8-inch woofer with RGB lighting, DJ and karaoke functions, Wireless Party Link and multiple connection options.',quickSpecs:['8-inch woofer','RGB lighting','DJ & karaoke'],specs:{'System':'3-way, 5-speaker','Woofer':'8-inch','Midrange':'2 × 3-inch','Tweeters':'2 × 2-inch','Bluetooth':'4.0','USB':'2 inputs','Optical':'Yes','Weight':'16 kg'},oemUrl:'https://www.lg.com/africa/audio/lg-rnc7'}),
 p({slug:'lg-xboom-rnc9',brand:'LG',name:'LG XBOOM RNC9 Party Speaker',type:'Party speaker',tier:'PREMIUM',shortDescription:'A larger XBOOM party system for powerful bass, lighting and DJ-focused entertainment.',description:'LG XBOOM RNC9 sits higher in the XBOOM party-speaker range, combining large-format sound with lighting and party controls.',quickSpecs:['High-power XBOOM','RGB lighting','DJ & karaoke'],specs:{'Series':'LG XBOOM','Wireless':'Bluetooth','Lighting':'Multi-colour RGB','Party features':'DJ / karaoke / Juke Box'},oemUrl:'https://www.lg.com/africa/party-speakers'}),
 p({slug:'jbl-partybox-encore-essential-2',brand:'JBL',name:'JBL PartyBox Encore Essential 2',type:'Portable party speaker',tier:'PREMIUM',shortDescription:'100 W RMS portable party sound with lighting, Bluetooth 5.4 and up to 15 hours playtime.',description:'JBL PartyBox Encore Essential 2 combines 100 W RMS output, a 5.25-inch woofer, dual dome tweeters, Bluetooth 5.4, lightshow and up to 15 hours of playtime.',quickSpecs:['100 W RMS','15-hour playtime','Bluetooth 5.4'],specs:{'Output power':'100 W RMS','Woofer':'1 × 5.25-inch','Tweeters':'2 × 0.75-inch dome','Frequency response':'40 Hz–20 kHz','Bluetooth':'5.4','Battery playtime':'Up to 15 hours','Weight':'6.2 kg','Water resistance':'Not specified on cited page'},oemUrl:'https://www.jbl.com/PARTYBOX-ENCORE-ESSENTIAL-2.html'}),
 p({slug:'jbl-partybox-110',brand:'JBL',name:'JBL PartyBox 110',type:'Portable party speaker',tier:'PREMIUM',shortDescription:'160 W RMS party sound with built-in lightshow, Bluetooth 5.1 and up to 12 hours playtime.',description:'JBL PartyBox 110 delivers 160 W RMS through dual woofers and tweeters, with Bluetooth 5.1, built-in lightshow, rechargeable battery and up to 12 hours playtime.',quickSpecs:['160 W RMS','12-hour playtime','Bluetooth 5.1'],specs:{'Output power':'160 W RMS','Woofers':'2 × 5.25-inch','Tweeters':'2 × 2.25-inch','Frequency response':'45 Hz–20 kHz','Bluetooth':'5.1','Battery playtime':'Up to 12 hours','Weight':'10.84 kg','Water resistance':'IPX4'},oemUrl:'https://www.jbl.com/JBLPARTYBOX110AM.html'}),
 p({slug:'jbl-partybox-encore-2',brand:'JBL',name:'JBL PartyBox Encore 2',type:'Portable party speaker',tier:'PREMIUM',shortDescription:'Portable party sound with 100 W RMS, karaoke support, Auracast and up to 15 hours playtime.',description:'JBL PartyBox Encore 2 delivers 100 W RMS, a 5.25-inch woofer, dual tweeters, Bluetooth 5.4, karaoke functions and up to 15 hours of playtime.',quickSpecs:['100 W RMS','15-hour playtime','Karaoke + Auracast'],specs:{'Output power':'100 W RMS','Woofer':'1 × 5.25-inch','Tweeters':'2 × 1-inch dome','Frequency response':'40 Hz–20 kHz','Bluetooth':'5.4','Battery playtime':'Up to 15 hours','Karaoke':'Yes','Auracast':'Yes'},oemUrl:'https://www.jbl.com/PARTYBOX-ENCORE-2.html'}),
 p({slug:'sony-ult-field-7',brand:'Sony',name:'Sony ULT FIELD 7',type:'Portable speaker',tier:'PREMIUM',shortDescription:'A large portable speaker with ULT POWER SOUND, IP67 protection and up to 30 hours battery life.',description:'Sony ULT FIELD 7 is a portable speaker with dual woofers and tweeters, ULT POWER SOUND, Bluetooth 5.2, IP67 water and dust protection and approximately 30 hours battery life.',quickSpecs:['Up to 30 hours','IP67','Bluetooth 5.2'],specs:{'Woofer units':'2','Tweeter units':'2','Bluetooth':'5.2','Codecs':'SBC / AAC / LDAC','Battery life':'Approx. 30 hours','Water protection':'IP67','Weight':'Approx. 13.89 lb','Inputs':'Stereo mini jack / USB / guitar-mic'},oemUrl:'https://www.sony.com/electronics/support/speakers-wireless-speakers/srs-ult70/specifications'}),
];
export const audioTiers=[['ENTRY','Everyday listening'],['EVERYDAY','Home & family sound'],['PARTY','Party & powerful bass'],['PREMIUM','Premium party sound']] as const;
export function audioProduct(slug:string){return audioProducts.find(p=>p.slug===slug)}
export function audioBrandsForProducts(){return Array.from(new Set(audioProducts.map(p=>p.brand)))}
export function audioByBrand(brand:string){return audioProducts.filter(p=>p.brand===brand)}
