export type CategoryNavNode={slug:string;name:string;description:string;href:string;children?:CategoryNavNode[]};
export const amaalCategoryNavigation:CategoryNavNode[]=[
 {slug:'phones',name:'Phones',description:'Flagship phones, everyday smartphones and foldables.',href:'/phones',children:[{slug:'iphones',name:'iPhone',description:'Apple iPhone models.',href:'/phones/brand/apple'},{slug:'samsung-galaxy',name:'Samsung Galaxy',description:'Galaxy S, Z and A series.',href:'/phones/brand/samsung'}]},
 {slug:'tablets',name:'Tablets',description:'Portable screens for work, study and entertainment.',href:'/categories/tablets',children:[{slug:'ipad',name:'Apple iPad',description:'iPad, iPad Air, iPad Pro and iPad mini.',href:'/categories/tablets/ipad'},{slug:'galaxy-tab',name:'Samsung Galaxy Tab',description:'Premium, FE and everyday Galaxy tablets.',href:'/categories/tablets/samsung-galaxy-tab'}]},
 {slug:'computers',name:'Computers',description:'Laptops, desktops and performance machines.',href:'/categories/computers',children:[{slug:'laptops',name:'Laptops',description:'Portable computers for work, study and play.',href:'/categories/computers/laptops'},{slug:'gaming',name:'Gaming laptops',description:'Performance machines for gaming and creation.',href:'/categories/computers/laptops/gaming'},{slug:'macbooks',name:'MacBook',description:'MacBook Air and MacBook Pro.',href:'/categories/computers/laptops/brand/apple'}]},
 {slug:'entertainment',name:'Entertainment',description:'Large-screen viewing and immersive sound.',href:'/categories/entertainment',children:[{slug:'tv',name:'TV',description:'Smart TVs across leading brands and screen sizes.',href:'/tvs'},{slug:'audio',name:'Audio',description:'Woofers, sound towers, party speakers and portable speakers.',href:'/categories/entertainment/audio',children:[{slug:'woofers',name:'Woofers',description:'Bass-focused home and party sound.',href:'/categories/entertainment/audio/woofers'},{slug:'sound-towers',name:'Sound towers',description:'Room-filling tower systems.',href:'/categories/entertainment/audio/sound-towers'},{slug:'party-speakers',name:'Party speakers',description:'Powerful sound for gatherings and celebrations.',href:'/categories/entertainment/audio/party-speakers'},{slug:'portable-speakers',name:'Portable speakers',description:'Portable Bluetooth speakers for everyday and outdoor listening.',href:'/categories/entertainment/audio/portable-speakers'}]}]},
 {slug:'home-appliances',name:'Home Appliances',description:'Refrigeration, laundry, cooling, cleaning and everyday home appliances.',href:'/categories/home-appliances',children:[{slug:'refrigerators-freezers',name:'Refrigerators & Freezers',description:'Cold storage for everyday home needs.',href:'/categories/home-appliances/refrigerators-freezers'},{slug:'washing-machines',name:'Washing Machines',description:'Washers, washer dryers and laundry care.',href:'/categories/home-appliances/washing-machines'},{slug:'air-conditioners',name:'Air Conditioners',description:'Cooling solutions for home spaces.',href:'/categories/home-appliances/air-conditioners'},{slug:'fans-air-care',name:'Fans & Air Care',description:'Fans and air coolers for everyday comfort.',href:'/categories/home-appliances/fans-air-care'},{slug:'vacuum-cleaners',name:'Vacuum Cleaners',description:'Everyday floor and home cleaning.',href:'/categories/home-appliances/vacuum-cleaners'},{slug:'irons-garment-care',name:'Irons & Garment Care',description:'Steam and garment-care appliances.',href:'/categories/home-appliances/irons-garment-care'},{slug:'water-dispensers',name:'Water Dispensers',description:'Water dispensers and hot-water solutions.',href:'/categories/home-appliances/water-dispensers'},{slug:'air-purifiers',name:'Air Purifiers',description:'Cleaner-air solutions for indoor spaces.',href:'/categories/home-appliances/air-purifiers'},{slug:'dishwashers',name:'Dishwashers',description:'Automated kitchen cleanup appliances.',href:'/categories/home-appliances/dishwashers'}]},
 {slug:'kitchen-appliances',name:'Kitchen Appliances',description:'Cooking, preparation, beverages and kitchen cleanup.',href:'/categories/kitchen-appliances',children:[{slug:'microwaves',name:'Microwaves',description:'Fast everyday cooking and reheating.',href:'/categories/kitchen-appliances/microwaves'},{slug:'ovens-cooking',name:'Ovens & Cooking',description:'Ovens and modern cooking appliances.',href:'/categories/kitchen-appliances/ovens-cooking'},{slug:'cookers-hobs',name:'Cookers & Hobs',description:'Gas and built-in cooking solutions.',href:'/categories/kitchen-appliances/cookers-hobs'},{slug:'air-fryers',name:'Air Fryers',description:'Convenient everyday air frying.',href:'/categories/kitchen-appliances/air-fryers'},{slug:'pressure-cookers-multicookers',name:'Pressure Cookers & Multicookers',description:'Pressure cookers, multicookers and rice cookers.',href:'/categories/kitchen-appliances/pressure-cookers-multicookers'},{slug:'blenders-food-preparation',name:'Blenders & Food Preparation',description:'Blending, chopping and food preparation.',href:'/categories/kitchen-appliances/blenders-food-preparation'},{slug:'juicers',name:'Juicers',description:'Juicers for everyday fruit and vegetable preparation.',href:'/categories/kitchen-appliances/juicers'},{slug:'mixers',name:'Mixers',description:'Hand and stand mixers for home baking.',href:'/categories/kitchen-appliances/mixers'},{slug:'coffee-beverage',name:'Coffee & Beverage',description:'Kettles and everyday beverage appliances.',href:'/categories/kitchen-appliances/coffee-beverage'},{slug:'grills-breakfast',name:'Grills & Breakfast',description:'Toasters, sandwich makers, grills and breakfast appliances.',href:'/categories/kitchen-appliances/grills-breakfast'},{slug:'fryers',name:'Fryers',description:'Deep fryers and dual-basket fryers.',href:'/categories/kitchen-appliances/fryers'},{slug:'specialty',name:'Specialty',description:'Ice makers, ice cream makers and other specialty appliances.',href:'/categories/kitchen-appliances/specialty'},{slug:'dishwashers',name:'Dishwashers',description:'Convenient kitchen cleanup.',href:'/categories/kitchen-appliances/dishwashers'}]},
 {slug:'accessories',name:'Accessories',description:'Useful additions for your devices and everyday setup.',href:'/categories/accessories',children:[{slug:'phone-accessories',name:'Phone accessories',description:'Charging, protection and everyday phone essentials.',href:'/categories/accessories'},{slug:'computer-accessories',name:'Computer accessories',description:'Keyboards, mice, hubs, webcams and laptop essentials.',href:'/categories/accessories'},{slug:'tablet-accessories',name:'Tablet accessories',description:'Pens, keyboards, cases and tablet productivity essentials.',href:'/categories/accessories'},{slug:'audio-accessories',name:'Audio accessories',description:'Useful additions for speakers and listening setups.',href:'/categories/accessories'},{slug:'gaming-accessories',name:'Gaming accessories',description:'Peripherals and setup essentials for PC gaming.',href:'/categories/accessories'}]}
];

export function buildCategoryNavigation(_categories:unknown[]):CategoryNavNode[]{
  return amaalCategoryNavigation;
}
