export type ComputerTier = 'EVERYDAY' | 'BUSINESS' | 'PREMIUM' | 'GAMING';
export type ComputerProduct = {
  slug:string; brand:string; family:string; name:string; type:'Laptop'|'Desktop'|'All-in-One'; tier:ComputerTier;
  shortDescription:string; description:string; quickSpecs:string[]; specs:Record<string,string>; image?:string;
};
const p=(x:ComputerProduct)=>x;
export const computerBrands=['HP','Lenovo','Apple'] as const;
export const computerProducts:ComputerProduct[]=[
 p({slug:'hp-15',brand:'HP',family:'HP 15',name:'HP 15 Laptop',type:'Laptop',tier:'EVERYDAY',shortDescription:'A practical everyday laptop for study, work and home computing.',description:'The HP 15 family is designed for everyday productivity, study, browsing and general home computing. Exact processor, memory and storage configurations vary by model and region.',quickSpecs:['15.6-inch display','Intel or AMD processors','SSD storage'],specs:{'Screen':'15.6-inch','Processor':'Intel Core or AMD Ryzen, configuration dependent','Memory':'8GB–16GB, configuration dependent','Storage':'256GB–512GB SSD, configuration dependent','Graphics':'Integrated Intel or AMD graphics','Operating system':'Windows 11','Class':'Everyday laptop'}}),
 p({slug:'hp-probook-440',brand:'HP',family:'ProBook',name:'HP ProBook 440',type:'Laptop',tier:'BUSINESS',shortDescription:'A compact business laptop built for everyday professional work.',description:'The HP ProBook 440 family combines a compact 14-inch format with business-focused features. Specifications vary by generation and regional configuration.',quickSpecs:['14-inch display','Intel Core processors','SSD storage'],specs:{'Screen':'14-inch','Processor':'Intel Core / Core Ultra, generation dependent','Memory':'Up to 32GB on supported configurations','Storage':'SSD, configuration dependent','Graphics':'Integrated Intel graphics; some configurations vary','Operating system':'Windows 11 Pro / Windows 11','Class':'Business laptop'}}),
 p({slug:'hp-probook-450',brand:'HP',family:'ProBook',name:'HP ProBook 450',type:'Laptop',tier:'BUSINESS',shortDescription:'A larger business laptop for office work, administration and professional use.',description:'The HP ProBook 450 family offers a 15.6-inch business laptop format with multiple processor, memory and graphics configurations.',quickSpecs:['15.6-inch display','Up to 32GB RAM','SSD storage'],specs:{'Screen':'15.6-inch','Processor':'Intel Core / Core Ultra, generation dependent','Memory':'Up to 32GB on supported configurations','Storage':'SSD, configuration dependent','Graphics':'Integrated Intel graphics; selected configurations may include NVIDIA graphics','Operating system':'Windows 11 Pro / Windows 11','Class':'Business laptop'}}),
 p({slug:'hp-probook-445',brand:'HP',family:'ProBook',name:'HP ProBook 445',type:'Laptop',tier:'BUSINESS',shortDescription:'A 14-inch AMD-powered business laptop for productive work.',description:'The HP ProBook 445 family uses AMD Ryzen processors in selected generations and is aimed at professional productivity.',quickSpecs:['14-inch display','AMD Ryzen options','SSD storage'],specs:{'Screen':'14-inch','Processor':'AMD Ryzen, generation dependent','Memory':'Up to 32GB on supported configurations','Storage':'SSD, configuration dependent','Graphics':'Integrated AMD Radeon graphics','Operating system':'Windows 11 Pro / Windows 11','Class':'Business laptop'}}),
 p({slug:'hp-elitebook-840',brand:'HP',family:'EliteBook',name:'HP EliteBook 840',type:'Laptop',tier:'PREMIUM',shortDescription:'A premium 14-inch business laptop for professionals who want a refined work machine.',description:'The HP EliteBook 840 family is a premium business line with modern Intel processor options, professional security features and a compact 14-inch design.',quickSpecs:['14-inch WUXGA options','Intel Core Ultra options','Premium business design'],specs:{'Screen':'14-inch, WUXGA options','Processor':'Intel Core Ultra / Intel Core, generation dependent','Memory':'Configuration dependent','Storage':'SSD, configuration dependent','Graphics':'Integrated Intel graphics','Operating system':'Windows 11 Pro','Class':'Premium business laptop'}}),
 p({slug:'hp-pavilion-15',brand:'HP',family:'Pavilion',name:'HP Pavilion 15 Laptop',type:'Laptop',tier:'EVERYDAY',shortDescription:'A versatile everyday laptop for school, work and entertainment.',description:'The HP Pavilion 15 family sits between basic everyday machines and premium consumer laptops, with Intel and AMD configurations depending on generation.',quickSpecs:['15.6-inch display','Intel or AMD options','SSD storage'],specs:{'Screen':'15.6-inch','Processor':'Intel Core or AMD Ryzen, generation dependent','Memory':'Configuration dependent','Storage':'SSD, configuration dependent','Graphics':'Integrated graphics; selected configurations vary','Operating system':'Windows 11','Class':'Everyday laptop'}}),
 p({slug:'hp-envy-14',brand:'HP',family:'Envy',name:'HP Envy 14 Laptop',type:'Laptop',tier:'PREMIUM',shortDescription:'A refined premium laptop for creators, professionals and demanding everyday use.',description:'HP Envy laptops are positioned as premium consumer machines with stronger displays, materials and performance than entry-level ranges.',quickSpecs:['14-inch display','Intel processor options','Premium build'],specs:{'Screen':'14-inch, configuration dependent','Processor':'Intel Core / Core Ultra, generation dependent','Memory':'Configuration dependent','Storage':'SSD, configuration dependent','Graphics':'Integrated or discrete graphics, configuration dependent','Operating system':'Windows 11','Class':'Premium laptop'}}),
 p({slug:'lenovo-ideapad-slim-3-15',brand:'Lenovo',family:'IdeaPad Slim 3',name:'Lenovo IdeaPad Slim 3 15',type:'Laptop',tier:'EVERYDAY',shortDescription:'A dependable 15-inch laptop for everyday productivity, study and home use.',description:'The IdeaPad Slim 3 15 family is available in Intel and AMD configurations. A documented AMD configuration includes Ryzen 5 7520U, 8GB LPDDR5, 512GB SSD and a 15.6-inch FHD display.',quickSpecs:['15.6-inch FHD','Ryzen 5 options','512GB SSD options'],specs:{'Screen':'15.6-inch FHD IPS, configuration dependent','Processor':'AMD Ryzen 5 7520U example configuration','Memory':'8GB LPDDR5 example; 16GB configurations available','Storage':'512GB SSD example configuration','Graphics':'AMD Radeon 610M on Ryzen 5 7520U configuration','Operating system':'Windows 11','Class':'Everyday laptop'}}),
 p({slug:'lenovo-ideapad-slim-3i-15',brand:'Lenovo',family:'IdeaPad Slim 3i',name:'Lenovo IdeaPad Slim 3i 15',type:'Laptop',tier:'EVERYDAY',shortDescription:'A slim 15-inch Intel laptop for everyday work, study and entertainment.',description:'The IdeaPad Slim 3i 15 family provides Intel-powered configurations in a practical 15-inch design.',quickSpecs:['15.6-inch FHD','Intel Core options','512GB SSD options'],specs:{'Screen':'15.6-inch FHD, configuration dependent','Processor':'Intel Core, generation dependent','Memory':'8GB–16GB, configuration dependent','Storage':'256GB–1TB SSD, configuration dependent','Graphics':'Integrated Intel graphics','Operating system':'Windows 11','Class':'Everyday laptop'}}),
 p({slug:'lenovo-v15',brand:'Lenovo',family:'V Series',name:'Lenovo V15',type:'Laptop',tier:'BUSINESS',shortDescription:'A straightforward business-value laptop for office and administrative work.',description:'The Lenovo V15 is a practical 15.6-inch business-value laptop with Intel and AMD configurations across generations.',quickSpecs:['15.6-inch display','Intel or AMD options','SSD storage'],specs:{'Screen':'15.6-inch FHD options','Processor':'Intel Core or AMD Ryzen, generation dependent','Memory':'Up to 16GB on documented configurations','Storage':'SSD, configuration dependent','Graphics':'Integrated graphics','Operating system':'Windows 11','Class':'Business-value laptop'}}),
 p({slug:'lenovo-thinkbook-14',brand:'Lenovo',family:'ThinkBook',name:'Lenovo ThinkBook 14',type:'Laptop',tier:'BUSINESS',shortDescription:'A modern business laptop balancing professional features and portability.',description:'ThinkBook 14 models are designed for small business and professional users, with modern processors and business-oriented connectivity.',quickSpecs:['14-inch display','Modern Intel/AMD options','Business connectivity'],specs:{'Screen':'14-inch, configuration dependent','Processor':'Intel Core / Core Ultra or AMD Ryzen, generation dependent','Memory':'Configuration dependent','Storage':'SSD, configuration dependent','Graphics':'Integrated graphics; selected configurations vary','Operating system':'Windows 11 Pro / Windows 11','Class':'Business laptop'}}),
 p({slug:'lenovo-thinkpad-e14',brand:'Lenovo',family:'ThinkPad E14',name:'Lenovo ThinkPad E14',type:'Laptop',tier:'BUSINESS',shortDescription:'A proven 14-inch business laptop for professionals and organizations.',description:'ThinkPad E14 models focus on business productivity, durability and security, with Intel and AMD generations available.',quickSpecs:['14-inch display','Business-class ThinkPad design','SSD storage'],specs:{'Screen':'14-inch, WUXGA options','Processor':'Intel Core Ultra / Intel Core or AMD Ryzen, generation dependent','Memory':'Configuration dependent','Storage':'SSD, configuration dependent','Graphics':'Integrated graphics; selected configurations vary','Operating system':'Windows 11 Pro','Class':'Business laptop'}}),
 p({slug:'lenovo-thinkpad-t14',brand:'Lenovo',family:'ThinkPad T14',name:'Lenovo ThinkPad T14',type:'Laptop',tier:'PREMIUM',shortDescription:'A premium professional ThinkPad built for serious business workloads.',description:'ThinkPad T14 is a premium business family designed around portability, manageability, security and long-term professional use.',quickSpecs:['14-inch display','Premium business line','Professional security'],specs:{'Screen':'14-inch, configuration dependent','Processor':'Intel Core Ultra / Intel Core or AMD Ryzen PRO, generation dependent','Memory':'Configuration dependent','Storage':'SSD, configuration dependent','Graphics':'Integrated graphics; selected configurations vary','Operating system':'Windows 11 Pro','Class':'Premium business laptop'}}),
 p({slug:'lenovo-loq-15',brand:'Lenovo',family:'LOQ',name:'Lenovo LOQ 15 Gaming Laptop',type:'Laptop',tier:'GAMING',shortDescription:'A gaming laptop family built for high-performance play and demanding creative workloads.',description:'Lenovo LOQ 15 combines performance-oriented processors, dedicated NVIDIA graphics on selected configurations and high-refresh display options.',quickSpecs:['15.6-inch display','NVIDIA RTX options','High-refresh configurations'],specs:{'Screen':'15.6-inch, high-refresh options','Processor':'Intel Core / AMD Ryzen, generation dependent','Memory':'Configuration dependent','Storage':'SSD, configuration dependent','Graphics':'NVIDIA GeForce RTX options on selected configurations','Operating system':'Windows 11','Class':'Gaming laptop'}}),
 p({slug:'lenovo-legion-5',brand:'Lenovo',family:'Legion 5',name:'Lenovo Legion 5 Gaming Laptop',type:'Laptop',tier:'GAMING',shortDescription:'A premium gaming laptop family designed for demanding games and performance work.',description:'Legion 5 models target gamers and performance users with high-performance processors, dedicated graphics and fast displays.',quickSpecs:['15/16-inch options','NVIDIA RTX options','High-refresh displays'],specs:{'Screen':'15/16-inch, generation dependent','Processor':'Intel Core / AMD Ryzen, generation dependent','Memory':'Configuration dependent','Storage':'SSD, configuration dependent','Graphics':'NVIDIA GeForce RTX options','Operating system':'Windows 11','Class':'Premium gaming laptop'}}),
 p({slug:'macbook-neo-13',brand:'Apple',family:'MacBook Neo',name:'MacBook Neo',type:'Laptop',tier:'EVERYDAY',shortDescription:'Apple’s compact Mac laptop for everyday work, study and personal computing.',description:'MacBook Neo is positioned as an accessible Mac notebook, combining a compact design with Apple silicon performance.',quickSpecs:['13-inch class display','Apple silicon','macOS'],specs:{'Processor':'Apple A18 Pro','Display':'13-inch class','Memory':'Configuration dependent','Storage':'Configuration dependent','Graphics':'Integrated Apple GPU','Operating system':'macOS','Class':'Everyday Mac laptop'}}),
 p({slug:'macbook-air-13-m5',brand:'Apple',family:'MacBook Air',name:'MacBook Air 13-inch with M5',type:'Laptop',tier:'PREMIUM',shortDescription:'A thin, light MacBook Air for work, study, creation and everyday performance.',description:'The 13-inch MacBook Air with M5 combines Apple silicon performance with a thin, fanless design and Liquid Retina display.',quickSpecs:['13.6-inch Liquid Retina','M5 chip','16GB unified memory starting point'],specs:{'Display':'13.6-inch Liquid Retina','Chip':'Apple M5','Memory':'16GB unified memory starting point','Storage':'512GB starting configuration','Graphics':'Integrated Apple GPU','Operating system':'macOS','Class':'Premium laptop'}}),
 p({slug:'macbook-air-15-m5',brand:'Apple',family:'MacBook Air',name:'MacBook Air 15-inch with M5',type:'Laptop',tier:'PREMIUM',shortDescription:'A larger-screen MacBook Air for people who want more workspace without moving to Pro.',description:'The 15-inch MacBook Air with M5 offers a larger Liquid Retina canvas while retaining the thin, light Air design.',quickSpecs:['15.3-inch Liquid Retina','M5 chip','16GB unified memory starting point'],specs:{'Display':'15.3-inch Liquid Retina','Chip':'Apple M5','Memory':'16GB unified memory starting point','Storage':'512GB starting configuration','Graphics':'Integrated Apple GPU','Operating system':'macOS','Class':'Premium laptop'}}),
 p({slug:'macbook-pro-14-m5',brand:'Apple',family:'MacBook Pro',name:'MacBook Pro 14-inch with M5',type:'Laptop',tier:'PREMIUM',shortDescription:'A professional 14-inch MacBook for demanding creative and technical workloads.',description:'The 14-inch MacBook Pro with M5 is designed for professional users who need more sustained performance and a Liquid Retina XDR display.',quickSpecs:['14.2-inch Liquid Retina XDR','M5 chip','1TB starting storage'],specs:{'Display':'14.2-inch Liquid Retina XDR','Chip':'Apple M5','Memory':'16GB unified memory starting point','Storage':'1TB starting configuration','Graphics':'Integrated Apple GPU','Operating system':'macOS','Class':'Professional laptop'}}),
 p({slug:'macbook-pro-14-m5-pro',brand:'Apple',family:'MacBook Pro',name:'MacBook Pro 14-inch with M5 Pro',type:'Laptop',tier:'PREMIUM',shortDescription:'A high-performance 14-inch MacBook Pro for demanding professional workloads.',description:'The M5 Pro configuration targets professionals working with code, media, design, data and other demanding applications.',quickSpecs:['14.2-inch Liquid Retina XDR','M5 Pro','Pro performance'],specs:{'Display':'14.2-inch Liquid Retina XDR','Chip':'Apple M5 Pro','Memory':'Configuration dependent','Storage':'Configuration dependent','Graphics':'Integrated Apple GPU','Operating system':'macOS','Class':'Professional laptop'}}),
 p({slug:'macbook-pro-16-m5-pro',brand:'Apple',family:'MacBook Pro',name:'MacBook Pro 16-inch with M5 Pro',type:'Laptop',tier:'PREMIUM',shortDescription:'A large-screen professional MacBook Pro for sustained demanding workloads.',description:'The 16-inch M5 Pro MacBook Pro is built for professionals who value a large workspace and high sustained performance.',quickSpecs:['16.2-inch Liquid Retina XDR','M5 Pro','Pro performance'],specs:{'Display':'16.2-inch Liquid Retina XDR','Chip':'Apple M5 Pro','Memory':'Configuration dependent','Storage':'Configuration dependent','Graphics':'Integrated Apple GPU','Operating system':'macOS','Class':'Professional laptop'}}),
 p({slug:'macbook-pro-16-m5-max',brand:'Apple',family:'MacBook Pro',name:'MacBook Pro 16-inch with M5 Max',type:'Laptop',tier:'PREMIUM',shortDescription:'Apple’s high-end notebook for the most demanding professional workflows.',description:'The M5 Max 16-inch MacBook Pro sits at the top of the Mac notebook range for demanding creative, engineering and technical workloads.',quickSpecs:['16.2-inch Liquid Retina XDR','M5 Max','Maximum MacBook Pro performance'],specs:{'Display':'16.2-inch Liquid Retina XDR','Chip':'Apple M5 Max','Memory':'Configuration dependent','Storage':'Configuration dependent','Graphics':'High-performance integrated Apple GPU','Operating system':'macOS','Class':'High-end professional laptop'}})
];
export const computerTiers=[['EVERYDAY','Everyday computing'],['BUSINESS','Work & business'],['PREMIUM','Premium computing'],['GAMING','Gaming & performance']] as const;
export function computerProduct(slug:string){return computerProducts.find(p=>p.slug===slug)}
export function computerByBrand(brand:string){return computerProducts.filter(p=>p.brand.toLowerCase()===brand.toLowerCase())}
