export type Customer={id:string;customerNo:string;name:string;email:string;phone:string;alternatePhone?:string;city?:string;region?:string;countryCode?:string;preferredCurrency?:string;status:string};
export type CustomerSession={id:string;created_at:string;last_used_at:string;expires_at:string;ip?:string;user_agent?:string};
const api=()=>process.env.NEXT_PUBLIC_API_BASE_URL||process.env.AMAAL_API_BASE_URL||'';
export const CUSTOMER_AUTH_EVENT='amaal-customer-auth-updated';
function csrf(){if(typeof document==='undefined')return '';const m=document.cookie.match(/(?:^|; )amaal_customer_csrf=([^;]+)/);return m?decodeURIComponent(m[1]):''}
export async function customerRequest(path:string,init:RequestInit={}){const headers=new Headers(init.headers);if(init.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const token=typeof localStorage!=='undefined'?localStorage.getItem('amaal_customer_token_v1'):'';if(token)headers.set('X-Amaal-Customer-Token',token);const c=csrf();if(c)headers.set('X-Amaal-Customer-CSRF',c);const r=await fetch(`${api()}${path}`,{...init,headers,credentials:'include',cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.error||'Account request failed.');return data}
export async function me(){try{return await customerRequest('/api/public/auth/me')}catch{return {authenticated:false}}}
export function emitAuth(){if(typeof window!=='undefined')window.dispatchEvent(new Event(CUSTOMER_AUTH_EVENT))}
export async function login(identifier:string,password:string,remember=false){const d=await customerRequest('/api/public/auth/login',{method:'POST',body:JSON.stringify({identifier,password,remember})});emitAuth();return d}
export async function register(payload:{name:string;email?:string;phone?:string;password:string;remember?:boolean}){const d=await customerRequest('/api/public/auth/register',{method:'POST',body:JSON.stringify(payload)});emitAuth();return d}
export async function activateWithAccessToken(token:string,password:string,name?:string){const headers=new Headers({'Content-Type':'application/json','X-Amaal-Customer-Token':token});const r=await fetch(`${api()}/api/public/auth/claim`,{method:'POST',headers,credentials:'include',cache:'no-store',body:JSON.stringify({password,name})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||'Unable to activate your account.');if(typeof localStorage!=='undefined')localStorage.removeItem('amaal_customer_token_v1');emitAuth();return d}
export async function logout(){await customerRequest('/api/public/auth/logout',{method:'POST'}).catch(()=>{});if(typeof localStorage!=='undefined')localStorage.removeItem('amaal_customer_token_v1');emitAuth()}

export function googleSignInUrl(returnTo='/account'){const base=api();return `${base}/api/public/auth/google/start?returnTo=${encodeURIComponent(returnTo)}`;}
